### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by mjlbach** [nvim-orgmode/orgmode#107]
### Does this feature exist in Emacs orgmode core?

N/A

### Orgmode link

Hi Kristijan,

Sorry for the issue, but I couldn't find you on our Matrix (and I'm off reddit now). I wanted to let you know I camped on https://github.com/neovim-org for a future orgmode plugin I had planned. The organization is yours if you want it (in case you want to move plugins for orgmode.nvim under an umbrella organization.

Feel free to reach out on matrix :)

**Comment by mjlbach** [comment]
> I'm not using Matrix, that's why you wasn't able to find me :). I did create it now :)

Wonderful! I hope you'll hang out with us more so we can better support your work in core :) 

> Have you planned to make orgmode yourself or just to create plugins for orgmode.nvim?
What plugins did you have in mind?

I made this organization many months ago, before you announced orgmode.nvim, I had originally wanted to work on an orgmode implementation myself, but then I became more involved in neovim core development which started eating up my time. 

I know org is *huge*, and so I had originally thought for the org plugins, that it would be useful to have an umbrella organization as that is easier to assign reviewer permissions, share secrets for CI, etc. 

> None of the plugins are under my ownership, so moving them to an organization would involve more people. I don't plan to create any of the plugins, but only to work on the core and to expose an API for plugin developers. 

That's true, but having a central place for them to be hosted might improve discovery. I think to some extent GNU does this with Savannah/contrib in the org repository. 

Anyways, just a thought and wanted to give you the option of taking the organization in case you were interested :) I don't have any suggestions, as my org mode needs are fairly minimal and anything that isn't met is more on the lack of a neovim GUI with nice latex embedding/babel which I used to use frequently when I was an emacser.

**Comment by kristijanhusak** [comment]
Hey @mjlbach , since I merged TS support to master, I'm now considering this option.
As I asked in previous comment, would you agree to renaming the organization to something like `neovim-orgmode` or `nvim-orgmode`? As I see both options are still available, so I could make them myself, but if you don't want to keep yours, I can take it over and rename it. What do you think?

**Comment by mjlbach** [comment]
I invited you as owner. I renamed it to nvim-orgmode (this matches nvim-treesitter, nvim-lspconfig, etc. although feel free to rename). You can feel free to kick everyone (including me), wipe the repos, and make it public.

**Comment by kristijanhusak** [comment]
Thanks @mjlbach! That's the name I wanted to use, so it's perfect. I hope to set everything up this weekend.
