### ISSUE TITLE
make dot command (repeat command) work with org-archive-subtree

### ISSUE THREAD

**Issue by grepinsight** [nvim-orgmode/orgmode#160]
### Does this feature exist in Emacs orgmode core?

N/A

### Orgmode link

NA

### Feature value

dot command is useful to repeat the previous action without having to type the shortcut.
Currently the org-archive-subtree shortcut is `<leader>o$`.

If we have a dot command, archiving mutliple subtrees can be done via `<leader>o$.....`(the number of dots depending on the number of subtrees you want to acrhive)

### Additional context

I found the comment that Kristijan made  <https://neovim.discourse.group/t/how-to-make-a-dot-repeat-with-lua-function/435/3>

:)

**Comment by kristijanhusak** [comment]
This was fairly simple, and I wanted to do it for some time now. I added a section to docs for this https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#dot-repeat, but basically you just need Tpope's https://github.com/tpope/vim-repeat plugin to achieve this.

**Comment by grepinsight** [comment]
Thank you so much!
