### ISSUE TITLE
Implement `org-toggle-heading` functionality

### ISSUE THREAD

**Issue by grepinsight** [nvim-orgmode/orgmode#164]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

https://orgmode.org/manual/Structure-Editing.html

### Feature value

Ability to quickly turn arbitrary text into org headings will improve UX

### Additional context

`org-toggle-item` which is  `C-c -` in emacs would be also nice to have. This converts text into a list.

**Comment by jgollenz** [comment]
@kristijanhusak I started working on this and am stuck on how to determine the parent headline of a paragraph. Is there an easy way from the current line of the cursor to the treesitter node that line belongs to? 

PS: I thought of mapping this to `<Leader>oh`, since it's still free. Let me know if you think a different mapping would make more sense (since e.g. checkbox toggling is done with `<C-Space>`).

**Comment by kristijanhusak** [comment]
@jgollenz This should give you the closest headline from your current position: https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/org/mappings.lua#L61

**Comment by jgollenz** [comment]
> the closest headline from your current position

Ah, the naming of that function confused me. I though it will return the headline with the lowest line diff from my current position. Thank you!

**Comment by jgollenz** [comment]
@grepinsight do you mind having a look at this #198? One thing I'm not sure how to handle is tags. Would you expect tags to disappear or should they just remain at the end of the line without any impact? I'd prefer the latter, because it is non-destructive (should you decide to turn the line back into a headline) and already works

**Comment by jgollenz** [comment]
Org-mode also allows toggling a checkbox item into a headline:

`- [ ] item` becomes `* TODO item`
but then
`* TODO item` becomes `TODO item`

In general: toggling a list item to a headline and toggling that headline again will result in a paragraph line. Can you think of any other cases besides paragraph lines and list items that I need to consider?

Aside from that, Org-mode does not insert any spaces in front of a headline that was toggled to a paragraph line. However, I think it makes sense to insert them according to [org_indent_mode](https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_indent_mode)

**Comment by grepinsight** [comment]
Thank you for implementing this! Turning simple text into heading works and vice versa.

> Would you expect tags to disappear or should they just remain at the end of the line without any impact? I'd prefer the latter, because it is non-destructive (should you decide to turn the line back into a headline) and already works

I just confirmed with my emacs that emacs does the latter (at least in my setting, which is doom emacs). I think as a user, that's a sensible default because it's non-destructive as you said

> In general: toggling a list item to a headline and toggling that headline again will result in a paragraph line.

This is also the behavior I observed in emacs as well.


One thing I wished the feature branch had that was missing was ability to toggle multiple lines of text into multiple headings by visual mode

<img width="437" alt="Screen Shot 2022-01-08 at 2 01 17 PM" src="https://user-images.githubusercontent.com/3666080/148661375-e4af6c94-2082-4e7b-8948-0df9b6fcceee.png">
<img width="462" alt="Screen Shot 2022-01-08 at 2 01 35 PM" src="https://user-images.githubusercontent.com/3666080/148661389-d79364c7-2627-402f-8a52-1265e9d530e6.png">

Other than this, it looks pretty solid

**Comment by jgollenz** [comment]
@grepinsight Thank you for testing it :) 

> toggle multiple lines of text into multiple headings by visual mode

I assume selecting multiple lines in visual mode is the Vim equivalent of what Emacs/Orgmode calls "regions", correct? I have a look at this, but please tell me what happens in Emacs when there is both normal lines and headlines in the region: 
![toggle_region](https://user-images.githubusercontent.com/12050098/148673953-f81c0b47-b4c0-4851-a530-ade4ea21bdf9.png)

**Comment by grepinsight** [comment]
# case1: normal line and headlines
<img width="134" alt="Screen Shot 2022-01-09 at 8 37 06 PM" src="https://user-images.githubusercontent.com/3666080/148718935-6278b8ac-a965-4336-87b7-edfe17a2e6f0.png">

<img width="211" alt="Screen Shot 2022-01-09 at 8 37 21 PM" src="https://user-images.githubusercontent.com/3666080/148718953-667dc57f-3d70-4d07-ac7a-15211a99bb61.png">

<img width="197" alt="Screen Shot 2022-01-09 at 8 37 30 PM" src="https://user-images.githubusercontent.com/3666080/148718962-8c17601c-091f-42f1-a62e-a60882e00488.png">

# case2 : normal lines and list

<img width="202" alt="Screen Shot 2022-01-09 at 8 38 38 PM" src="https://user-images.githubusercontent.com/3666080/148719030-50865dc2-fa25-4263-973c-e415ff30f699.png">

<img width="353" alt="Screen Shot 2022-01-09 at 8 38 57 PM" src="https://user-images.githubusercontent.com/3666080/148719043-8b0efb49-add9-460e-a3eb-e6178b475250.png">
<img width="300" alt="Screen Shot 2022-01-09 at 8 39 06 PM" src="https://user-images.githubusercontent.com/3666080/148719056-db2ce9d4-ccdf-471f-be7e-08ba8113ca59.png">

# case2b: list and normal lines
<img width="172" alt="Screen Shot 2022-01-09 at 8 40 03 PM" src="https://user-images.githubusercontent.com/3666080/148719108-6be1d437-4460-4ea2-be78-a569c3bd0421.png">
<img width="276" alt="Screen Shot 2022-01-09 at 8 40 16 PM" src="https://user-images.githubusercontent.com/3666080/148719119-e3feb3f8-f48b-4e95-aaa4-f373677a964f.png">
<img width="250" alt="Screen Shot 2022-01-09 at 8 40 25 PM" src="https://user-images.githubusercontent.com/3666080/148719128-ff6fdd8c-de50-438e-8390-f60e8d229a01.png">


**conclusion**: Looks like if there are mixed types in visual selection, only first type in the visual selection is affected

cc @jgollenz

**Comment by jgollenz** [comment]
@grepinsight thanks for clarifying :) I'll see what I can do

**Comment by jgollenz** [comment]
@grepinsight one more thing: could you please let me know how it behaves when you have a blank line as the first line in the visual selection?

**Comment by grepinsight** [comment]
Thanks for being thorough @jgollenz 

When you have a blank line(s) as the first line in the visual selection, they are simply ignored and the first non blank lines are used for toggle
<img width="407" alt="Screen Shot 2022-01-11 at 6 36 21 PM" src="https://user-images.githubusercontent.com/3666080/149053761-cc46f9e9-b439-4709-858b-fb5b08466d85.png">

<img width="343" alt="Screen Shot 2022-01-11 at 6 36 35 PM" src="https://user-images.githubusercontent.com/3666080/149053784-35072492-bd1f-4cb6-872b-64924c04145d.png">

**Comment by jgollenz** [comment]
@kristijanhusak support for toggling multiple lines would entail a visual mode mapping. As far as I can see we are only using normal mode mappings right now, hard-coded in the `setup_mappings` function if I'm not mistaken. I don't know how many emacs orgmode features rely on regions/visual selections, but IF we want to support them, we should think of how to do it properly. I'd prefer to do that in a different PR then. What's your opinion on this?

**Comment by kristijanhusak** [comment]
@jgollenz for now implement only the normal mode mapping. At one point I'll figure out how to set up multiple mode mappings and we can introduce it then. I don't think it's a big of an issue without the visual mapping here.
