### ISSUE TITLE
Run Function for capture template

### ISSUE THREAD

**Issue by joshpetit** [nvim-orgmode/orgmode#167]
### Does this feature exist in Emacs orgmode core?

N/A

### Orgmode link

*I'm not sure if this exists in orgmode as nvim-orgmode is my first experience with orgmode.*

Hey! Thanks a lot for this, I've never used orgmode before in emacs, and using this has made organizing a lot easier. 

One thing I would like to do is run a function for specific captures. What I specifically want is to be able to create notes for the text I have selected that way it could create something like
```org
*** [[books/myBook.md:234:5] begRef] - [[books/mybook.md:235:8] endRef]
**** <Some Date>
Write notes about it here
```

So being able to run a function to create the object for a specific capture would let me be able to get the current selection and use it in the template.

If this is already possible then I'd appreciate pointers on how to do this! Thanks a lot!

**Comment by kristijanhusak** [comment]
You can check the section in Docs to see available markers for template https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_agenda_templates.

For your use case, you can use `%(EXP)` which evaluates a lua code inside the parentheses.

**Comment by joshpetit** [comment]
@kristijanhusak That'll do thank you!
