### ISSUE TITLE
Week number is incorrect when first day of the week is set to 0

### ISSUE THREAD

**Issue by joshpetit** [nvim-orgmode/orgmode#172]
### Describe the bug

I set my first day of the week to be `0` so that it starts with Sunday rather than monday. Because of this, when I pull up the agenda view for the week (W47 as of now), it will show Nov 28 - Dec 04. 

### Steps to reproduce

1. Set `org_agenda_start_on_weekday = 0`
2. Be at the start of a new week

### Expected behavior

I expect it to show this new week (W48).

### Minimal init.lua

```
require('orgmode').setup({
    org_deadline_warning_days = 31,
    org_agenda_start_on_weekday = 0,
})


### Screenshots and recordings

_No response_

### OS / Distro

Arch Linux

### Neovim version/commit

0.6

### Additional context

_No response_

**Comment by kristijanhusak** [comment]
Orgmode uses ISO weekdays to determine the weekday, this means it goes from 1 (Monday) to 7 (Sunday). Emacs orgmode does support setting it to a value that's under 1, and it properly handles the "negative" value, but I didn't add support for that.

To use Sunday as your start day, set `org_agenda_start_on_weekday` to `7`.

**Comment by joshpetit** [comment]
Oh ok that makes sense, thanks for the clarification!
