### ISSUE TITLE
Docs: What is this?

### ISSUE THREAD

**Issue by zalegrala** [nvim-orgmode/orgmode#173]
### Does this feature exist in Emacs orgmode core?

N/A

### Additional context

I just came here from a Lunarvim issue that was filed, but I can't tell what this project is used for.  The docs show me how to set it up and show some Gifs doing something, but I can't tell what.  So perhaps the docs could answer this; what is this project and why should someone use it?

**Comment by kristijanhusak** [comment]
If you don't know what it is, most likely you don't need it. Simple google search for "orgmode" would clarify a lot of things. If you need to keep up discussing this please create a discussion in the "Discussions" section.

**Comment by zalegrala** [comment]
Ohh, its an emacs thing.  https://en.wikipedia.org/wiki/Org-mode
