### ISSUE TITLE
Agenda ignores plain timestamps

### ISSUE THREAD

**Issue by petRUShka** [nvim-orgmode/orgmode#174]
### Describe the bug

There are plain timestampts:

> Plain timestamp; Event; Appointment
> 
>     A simple timestamp just assigns a date/time to an item. This is just like writing down an appointment or event in a paper agenda. In the agenda display, the headline of an entry associated with a plain timestamp is shown exactly on that date.
> 
>     * Meet Peter at the movies
>       <2006-11-01 Wed 19:15>
>     * Discussion on climate change
>       <2006-11-02 Thu 20:00-22:00>

But plain timestamps are ignored by week agenda.

P.S. Actually now all timestamps are ignored. Previously SCHEDULED and DEADLINE timestamps were presented in agendas.

### Steps to reproduce

1. Create `~/org/test.org` file:
```org
* Tasks
** TODO Heading
** TODO DDD
   CLOSED: [2021-10-31 Sun 00:32]
** TODO Heading<2021-11-27 Sat>
* Level 1
** TODO Heading
   DEADLINE: <2021-11-28 Sun>
```
2. Open week agenda with `<localleader>oaa`
3. Get empty week agenda:

```
Week-agenda (W49):
Monday     06 December 2021
Tuesday    07 December 2021
Wednesday  08 December 2021
Thursday   09 December 2021
Friday     10 December 2021
Saturday   11 December 2021
Sunday     12 December 2021
```

### Expected behavior

Something like vim-orgmode does when press `caA`:

```
Week Agenda:
<2021-11-27 Sat>
  test (1)  TODO  Heading<2021-11-27 Sat>
<2021-11-28 Sun>
  test (1)  TODO  Heading
```

### Emacs functionality

> A timestamp is a specification of a date (possibly with a time or a range of times) in a special format, either ‘<2003-09-16 Tue>’ or ‘<2003-09-16 Tue 09:39>’ or ‘<2003-09-16 Tue 12:00-12:30>’59. A timestamp can appear anywhere in the headline or body of an Org tree entry. Its presence causes entries to be shown on specific dates in the agenda (see Weekly/daily agenda).

https://orgmode.org/manual/Timestamps.html

### Minimal init.lua

It is acutally minimal_vimrc:

```vim
set nocompatible
set runtimepath^=~/.vim runtimepath+=~/.vim/after
call plug#begin('~/.vim/plugged')
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'kristijanhusak/orgmode.nvim'
call plug#end()
"let &rtp  = '~/.vim/plugged/vim-orgmode,' . &rtp
"let &rtp .= ',~/.vim/plugged/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

lua << EOF
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.org = {
    install_info = {
        url = 'https://github.com/milisims/tree-sitter-org',
        revision = 'main',
        files = {'src/parser.c', 'src/scanner.cc'},
        },
    filetype = 'org',
    }

require'nvim-treesitter.configs'.setup {
    -- If TS highlights are not enabled at all, or disabled via `disable` prop, highlighting will fallback to default Vim syntax highlighting
    highlight = {
    enable = true,
    disable = {'org'}, -- Remove this to use TS highlighter for some of the highlights (Experimental)
    additional_vim_regex_highlighting = {'org'}, -- Required since TS highlighter doesn't support all syntax features (conceal)
    },
  ensure_installed = {'org'}, -- Or run :TSUpdate org
  }

require('orgmode').setup({
org_agenda_files = {'~/org/*'},
org_default_notes_file = '~/org/test.org',
})
EOF
```

### OS / Distro

Arch Linux

### Neovim version/commit

NVIM v0.6.0

**Comment by levouh** [comment]
Do you have the latest `treesitter` parser installed @petRUShka? There were some changes recently to have the node for the "type" of node to just be generic, rather than named specifically (so instead of the node being named `scheduled`, it is now just a `name` and the text can be grabbed to discern what type of timestamp it is).

This breaks all agenda functionality if you don't have your `treesitter` parser up to date. For me, I had to `:TSUninstall org` and then `:TSInstall org`, rather than just `:TSUpdate org` (pretty sure in hindsight that this is due to my lazy loading of packages, but regardless).

---

Seeing as you've noted that:

>Actually now all timestamps are ignored

can you try updating your parser @petRUShka and see if that doesn't solve it?

**Comment by petRUShka** [comment]
Thanks Uninstall and Install works! Thanks.

But now it ignores expired DEADLINEs:

```
Week-agenda (W49):
Monday     06 December 2021
Tuesday    07 December 2021
Wednesday  08 December 2021
  test:       10 d. ago: TODO Heading
Thursday   09 December 2021
Friday     10 December 2021
Saturday   11 December 2021
Sunday     12 December 2021
```

P.S. You were right:

`:TSUpdate` yields:

```
Parsers are up-to-date!
```

**Comment by kristijanhusak** [comment]
@petRUShka can you check the org file that should report these if it has any diagnostic errors? Just open the file and run `:OrgDiagnostics`.

**Comment by petRUShka** [comment]
I've updated TreeSitter, so with upgraded one I see 

```
[orgmode] No errors.
```

with `:OrgDiagnostics`

**Comment by kristijanhusak** [comment]
@petRUShka can you re-test the minimal vimrc and some test file that you can upload here so I can try to reproduce it?

**Comment by petRUShka** [comment]
@kristijanhusak, right now there is only one problem: one cannot see expired DEADLINE in agenda.

Thanks to @levouh and his advice other timestamps are in agenda now.

test.org: https://gist.github.com/2a5fca9b2257dcf1b4f0e7ab91dc84c2

**Comment by kristijanhusak** [comment]
@petRUShka you don't see this one?
```
* TODO Heading with plain timestamp<2021-11-27 Sat>
```
I don't think dates were ever parsed from the headline. Maybe before tree-sitter support, but with tree-sitter that never worked.

I know that emacs does support this, so lets have a separate feature issue opened for this, if other issues are solved.

**Comment by petRUShka** [comment]
@kristijanhusak no, I was wrong. It works not as good as I thought.

I added several new lines  to file:

```
** TODO Heading with plain timestamp in heading <2021-12-10 Fri>
** TODO Heading with plain timestamp in heading without space<2021-12-10 Fri>
** TODO Heading with plain timestamp in body
<2021-12-10 Fri>
** TODO Heading with plain timestamp in body expired
<2021-11-10 Wed>
```

And most of them are ignored by agenda:

```
Week-agenda (W49):
Monday     06 December 2021
Tuesday    07 December 2021
Wednesday  08 December 2021
Thursday   09 December 2021
  test:       Scheduled: TODO Heading SCHEDULE
  test:       30 d. ago: TODO Heading with expired DEADLINE
  test:       In 1 d.:   TODO Heading with DEADLINE
Friday     10 December 2021
  test:       Deadline: TODO Heading with DEADLINE
  test:      TODO Heading with plain timestamp in body
Saturday   11 December 2021
Sunday     12 December 2021
```

**Comment by petRUShka** [comment]
What should I do with separate issue?

**Comment by kristijanhusak** [comment]
These two should properly appear on their dates:
```
** TODO Heading with plain timestamp in body
<2021-12-10 Fri>
** TODO Heading with plain timestamp in body expired
<2021-11-10 Wed>
```

But the first two are not working because date is in the headline line (TODO line). Treesitter doesn't recognize these as timestamp.

Create an issue for first two items in your example.

**Comment by petRUShka** [comment]
@kristijanhusak, I've created #177.

But there is also a bug. Expired plain timestamp in body is ignored.

**Comment by kristijanhusak** [comment]
@petRUShka body timestamps are shown only on the day they occur, they do not appear on any other days like schedule and deadline. In your example above, the "expired" heading is set to 11th November. Go back and check that date.

**Comment by petRUShka** [comment]
@kristijanhusak, is it correct behavior? I thought it should behave like SCHEDULED (at list it behaves this way in vim-orgmode).

**Comment by kristijanhusak** [comment]
@petRUShka Yes, that's correct behavior, at least that's how Emacs orgmode works.

**Comment by chmanie** [comment]
Yeah, I got confused by it as well (especially that the app I'm using - beorg) does seem to have a different understanding and does not show `SCHEDULED` items after the day they're scheduled.

From the [orgmode docs](https://orgmode.org/manual/Deadlines-and-Scheduling.html):

> Important: Scheduling an item in Org mode should not be understood in the same way that we understand scheduling a meeting. Setting a date for a meeting is just a simple appointment, you should mark this entry with a simple plain timestamp, to get this item shown on the date where it applies. This is a frequent misunderstanding by Org users. In Org mode, scheduling means setting a date when you want to start working on an action item.
