### ISSUE TITLE
 wrap mode turned off by default in org capture

### ISSUE THREAD

**Issue by Josiah-tan** [nvim-orgmode/orgmode#176]
Just wondering how can I turn on wrap mode by default when I open up my org capture window?

**Comment by TravonteD** [comment]
Orgcapture uses the `org` filetype. Any settings you make for org will apply.

```vimscript
autocmd Filetype org setlocal wrap
```

**Comment by kristijanhusak** [comment]
I pushed a change that removes `nowrap` setting on capture window. Should be working fine for you now without the need to overwrite it.
