### ISSUE TITLE
Parsing timestamps in headings

### ISSUE THREAD

**Issue by petRUShka** [nvim-orgmode/orgmode#177]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

> A timestamp is a specification of a date (possibly with a time or a range of times) in a special format, either ‘<2003-09-16 Tue>’ or ‘<2003-09-16 Tue 09:39>’ or ‘<2003-09-16 Tue 12:00-12:30>’59. A timestamp can appear anywhere in the headline or body of an Org tree entry. Its presence causes entries to be shown on specific dates in the agenda (see Weekly/daily agenda).

https://orgmode.org/manual/Timestamps.html

### Additional context

Issue #174 has full details on subject.

Quotation:

These two should properly appear on their dates:

** TODO Heading with plain timestamp in body
<2021-12-10 Fri>
** TODO Heading with plain timestamp in body expired
<2021-11-10 Wed>

But the first two are not working because date is in the headline line (TODO line). Treesitter doesn't recognize these as timestamp.

Create an issue for first two items in your example.

**Comment by kristijanhusak** [comment]
Timestamps are not parsed from headlines. They are not highlighted, but properly parsed as a plain timestamp.
