### ISSUE TITLE
...plugged/orgmode.nvim/lua/orgmode/agenda/views/agenda.lua:13: invalid order function for sorting

### ISSUE THREAD

**Issue by steigerth** [nvim-orgmode/orgmode#179]
### Describe the bug

If I open the agenda with `leader` oa the following error is displayed:
`[orgmode] ...r/start/orgmode.nvim/lua/orgmode/agenda/views/agenda.lua:13: invalid order function for sorting`

### Steps to reproduce

1. open agenda with `leader` oa
2. press key 'a'

The org file is here attached: [work.txt](https://github.com/nvim-orgmode/orgmode/files/7694871/work.txt)
 

### Expected behavior

agenda view should open

### Minimal init.lua

I could reproduce the error with the provided minimal init.lua file. I only added `org_agenda_files`
[init.zip](https://github.com/nvim-orgmode/orgmode/files/7694880/init.zip)

### OS / Distro

Debian bullseye

### Neovim version/commit

NVIM v0.6.0-dev+461-g88e16a7f3

**Comment by jmrussell** [comment]
I get the same issue on the latest release.

**Comment by kristijanhusak** [comment]
Reproduced. Looking at it.

**Comment by kristijanhusak** [comment]
I pushed a fix. Shouldn't be happening any more. Let me know if everything is ok.

**Comment by steigerth** [comment]
I can confirm, that it works again. Thank you very much for your hard work on moving on with this project. Looking forward for further improvements!
