### ISSUE TITLE
Source code block gets parsed as org syntax

### ISSUE THREAD

**Issue by Maltimore** [nvim-orgmode/orgmode#186]
### Describe the bug

I have a source code block, which contains in some lines an asterisk (*) at the beginning. nvim-orgmode thinks this is the beginning of a new orgmode-heading.

### Steps to reproduce

Use the following file

some_file.org
```
* heading 1
#+BEGIN_SRC txt

* this gets parsed as another heading
#+END_SRC
```
You will see that the block gets folded until the "second" (false) heading. If there's no newline before the "second" heading, the code block doesn't get folded at all. If there's no asterisk, everything gets folded as expected.

### Expected behavior

The entire code (text) block should not be treated as having org-syntax and should get folded away.

### Minimal init.lua

I was getting an error when using the provided minimal_init.lua. Probably best to open another issue for this.

### OS / Distro

Ubuntu 20.04, alacritty

### Neovim version/commit

master

**Comment by levouh** [comment]
The source block needs to be indented @Maltimore, here is how it works in vanilla _Emacs_:

https://user-images.githubusercontent.com/31262046/147841231-298eb6a8-03de-402a-b7e9-745eee3d32ef.mp4

and in _Neovim_:

https://user-images.githubusercontent.com/31262046/147841245-6b92e2f9-ff1b-48b5-b20c-20aaecca2413.mp4

**Comment by Maltimore** [comment]
Hi @levouh,
sorry for not answering immediately. I really appreciate your help, thanks!
It works like a charm when indenting.
