### ISSUE TITLE
Link Concealing

### ISSUE THREAD

**Issue by jgollenz** [nvim-orgmode/orgmode#188]
I've read that this is a known limitation, but I'd like to get more info on the actual problem. Is it an issue with tree-sitter? nvim-treesitter? Is there already an issue at the respective repo?

**Comment by levouh** [comment]
The only problem I'm aware of as far as link concealing goes is some stuff with regards to when `:set wrap` is on (the text wraps based on the non-concealed content length, rather than the concealed content length). As far as regular folding goes, do you mean anything beyond something like this:

https://user-images.githubusercontent.com/31262046/147841118-449c1bb0-8c3c-4aef-b1fa-3e7cc0413a07.mp4

@jgollenz?

**Comment by jgollenz** [comment]
> do you mean anything beyond something like this

No, that's the behavior I would expect. Works with `<leader>oo` to open, correct?

**Comment by levouh** [comment]
Yup, it does.

Were you having problems with it (either the concealing or open actions)?

**Comment by jgollenz** [comment]
> Were you having problems with it (either the concealing or open actions)?

The former. Is there a mapping that forces the link to be concealed or should it conceal automatically? It just stays in the `[[link][name]]` syntax for me

**Comment by levouh** [comment]
At the end of the video I `:echo &conceallevel`, can you do the same?

**Comment by jgollenz** [comment]
> `:echo &conceallevel`

Returns `0` for me

**Comment by levouh** [comment]
Set it to `2`.

**Comment by jgollenz** [comment]
Oh, right. Thank you! I would have expected that to work out of the box. I'd also expect this to work for links in headings:
![heading-links](https://user-images.githubusercontent.com/12050098/147868468-25844f84-903c-4a54-bfd9-c26e4eca7575.gif)

**Comment by levouh** [comment]
It does work as far as I'm aware, mind sharing your configuration? You likely need:

```lua
  require("nvim-treesitter.configs").setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { "org" }, -- < This one
    },
    ensure_installed = { "org" },
  })
```

this setup.

---

As far as concealing goes, we could probably update the `ftplugin` to set the conceal by default, however I'm not entirely sure what people would want, hence no default. `2` seems reasonable to start, as `3` is a bit magical if you don't understand what it is doing. We can see what @kristijanhusak thinks.

---

>and I also would expect the links to not show when conceallevel=3. Yet they still show when I'm on the same line

`:h concealcursor`

**Comment by jgollenz** [comment]
> mind sharing your configuration?

It's identical to what you posted. But I just figured out that apparently I'm not using tree-sitter at all right now, since `config:ts_highlights_enabled()` is false. Have to do some digging on why that's the case.

> update the `ftplugin` to set the conceal by default

I'm not sure either, but I'd mention it somewhere in the README at least.

> `:h concealcursor`

Thanks! That does the trick

**Comment by kristijanhusak** [comment]
> As far as concealing goes, we could probably update the ftplugin to set the conceal by default, however I'm not entirely sure what people would want, hence no default. 2 seems reasonable to start, as 3 is a bit magical if you don't understand what it is doing. We can see what @kristijanhusak thinks.

I didn't want to set it in ftplugin because that would require double override for people who wants it differently: on a global config level, and on a filetype specific level.

I think adding it to the [Troubleshoot](https://github.com/nvim-orgmode/orgmode#troubleshoot) section should suffice.

**Comment by jgollenz** [comment]
I have tree-sitter enabled now. This gives me concealed links in headlines, but only when they are not folded. Is that expected or am I missing another option?

![heading-links2](https://user-images.githubusercontent.com/12050098/147985774-0a921b05-78f7-45a3-bc93-2c03bff23304.gif)

**Comment by levouh** [comment]
Expected, folded text has its own syntax so it doesn't respect the same concealing, etc. as far as I'm aware.

**Comment by kristijanhusak** [comment]
@levouh is correct. There's no way to use Conceal feature on folded text. Only thing that could be done is to set up foldtext to know how to conceal this. I'm not sure how complicated it would be.
I think that generally people are not putting links in the headlines. Those usually go inside the content.

**Comment by jgollenz** [comment]
> There's no way to use Conceal feature on folded text

Is that one of the limitations that is mentioned in the README?

> Only thing that could be done is to set up foldtext to know how to conceal this

Any suggestions/resources on how to `set up foldtext`? I have not much experience in this area.

> I think that generally people are not putting links in the headlines

Unfortunately I'm doing this a lot. I'll see what I can do

**Comment by kristijanhusak** [comment]
I didn't add this limitation to readme, I didn't even thought about it until now.

You can see how foldtext is currently set: https://github.com/nvim-orgmode/orgmode/blob/master/ftplugin/org.vim#L28
And actual logic that is applied: https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/org/indent.lua#L93-L100

**Comment by jgollenz** [comment]
> I didn't add this limitation to readme

Then which concealing limitations are meant [here](https://github.com/nvim-orgmode/orgmode#known-highlighting-issues-and-limitations)? `org_hide_emphasis_markers` works for me as well.

Thanks, I'll have a look at it. Could you just link to where the logic for link-concealing outside of headings can be found

**Comment by jgollenz** [comment]
Might [this](https://github.com/nvim-orgmode/orgmode/blob/master/syntax/org.vim#L56-L59) be the right place?

**Comment by kristijanhusak** [comment]
@jgollenz yeah that's the place. Limitation mentions that concealing is done via Vim's syntax instead of tree-sitter highlighter. Once Neovim supports some kind of concealing outside of old Vim's way (I hope it will), we could have concealing everywhere, even in the folded content.

**Comment by levouh** [comment]
@jgollenz you can try #191, just messing with it to show it is pretty simple there.

**Comment by jgollenz** [comment]
@levouh thanks a lot :) sems to work with `[[named][links]]` but not with `[[unnamed]]` links

**Comment by jgollenz** [comment]
> concealing is done via Vim's syntax instead of tree-sitter highlighter

Oh, now I understand. Concealing is not yet possible with tree-sitter, so you just use the Vim-way instead. I thought concealing is not possible at all. My bad

**Comment by jgollenz** [comment]
> If both people have access to push to the same source as where the PR comes from, then yes. I'll update the PR I have with your comments.

That does not apply to the general `Fork-PR-Merge` workflow on Github, since I don't have push rights on other people's forks. So if people want to work together on a PR on public Github, they basically need to know each other. Can't fork a fork, right? At least not in the Github-sense of 'fork'.

> I'll update the PR I have with your comments

Thank you :)

**Comment by levouh** [comment]
Looking around a bit, it looks like the best way to do it would be for you to fork someone else's _PR_, and when creating a merge request (to their fork) you can do:

![image](https://user-images.githubusercontent.com/31262046/148490756-e0525e28-2e9c-40a8-aee7-a7461dfcd329.png)

to allow them to edit it. No asking for permission, just submitting changes on top of theirs as needed. They can merge it into their for (assuming that is the source of the original _PR_) and changes will be reflected as expected.

**Comment by kristijanhusak** [comment]
I think leaving constructive comments on the original PR is sufficient. Original author can use those to update the PR.

**Comment by jgollenz** [comment]
> I think leaving constructive comments on the original PR is sufficient. Original author can use those to update the PR.

I agree. Encourages thinking more about the size of a PR and people giving feedback instead of `here, I fixed it for you` (which I kinda did, sorry @levouh). Was just curious how collaboration in such a case would work ;)

**Comment by jgollenz** [comment]
This is already merged. Thanks @levouh

**Comment by Maltimore** [comment]
I'm not sure, but maybe with the following PR merged, link concealing on a fold could work out of the box now?
https://github.com/neovim/neovim/commit/1233ac467de7504b277425988ef9be7f8d3a9626
The commit description specifically lists `conceal` as one of the things that is respected.

**Comment by kristijanhusak** [comment]
@Maltimore yes, that change solves the issue. I'll officially document it once 0.10 is out.
