### ISSUE TITLE
Toggle Checkbox not functioning

### ISSUE THREAD

**Issue by Haadi-Khan** [nvim-orgmode/orgmode#189]
### Describe the bug

Toggling checkbox doesn't work. No matter the heading level (including no heading at all) the checkbox doesn't toggle using <C-Space>. Alternative keybinds also seem not to work. This exists in all modes (Normal, Insert, etc.). Typically nothing will happen at all, obviously in visual mode it just advances the cursor.

Sidenote, all other commands I've tested (changing date, changing heading level, etc.) have worked perfectly fine.

### Steps to reproduce

It's hard to describe since I've only seen this on my own machine, and haven't seen this issue on the github before. I haven't tested my laptop yet since I haven't gotten the time to yet. I don't know how to reproduce besides setting up a .org file and using the command. If it matters, I'm using alacritty on Arch Linux.

### Expected behavior

When <C-Space> is activated, the space between [ ] should toggle between an X and an empty space. Instead, nothing happens.

### Minimal init.lua

I'm using init.vim instead of init.lua, and I have my files split up. This is the section for vim plugs and the lua setup. Here's a pastebin for the page with the orgmode config, if it's not correct please let me know so I can update it. (The pastebins kept breaking for some strange reason, I'll just paste it here. Sorry that it's a lot, idk how to properly use a minimal config with .vim)
```
call plug#begin('~/.config/nvim/plugged')
	" Themes and Airline
	Plug 'git@github.com:joshdick/onedark.vim' 							 		" Colors
	Plug 'git@github.com:vim-airline/vim-airline' 								" Status Bar
	Plug 'git@github.com:Yggdroot/indentLine.git'                 				" Indent Guides
	Plug 'git@github.com:tc50cal/vim-terminal' 									" Integrated Terminal
	Plug 'git@github.com:scrooloose/nerdcommenter' 								" Comment Out Code
	Plug 'git@github.com:tiagofumo/vim-nerdtree-syntax-highlight' 				" File Tree Coloring
	Plug 'git@github.com:ryanoasis/vim-devicons' 				  				" File Icons in Tree

	" Git Stuff
	Plug 'git@github.com:tpope/vim-fugitive'                               		" Git Plugin
	Plug 'git@github.com:airblade/vim-gitgutter' 								" Edited Lines

	" Code Autocomplete and support
	Plug 'git@github.com:neoclide/coc.nvim', {'branch': 'release'}         		" Auto Complete
	Plug 'git@github.com:sheerun/vim-polyglot'                             		" Syn. Highlight
	Plug 'git@github.com:bfrg/vim-cpp-modern.git'                 				" C++ Syntax Highlight 
	Plug 'git@github.com:numirias/semshi', { 'do': ':UpdateRemotePlugins' } 	" Python Syntax Highlight
	" File navigation and searching
	Plug 'git@github.com:BurntSushi/ripgrep.git'                  				" Fast Grep
	Plug 'git@github.com:mbbill/undotree'                                  		" Undo History
	Plug 'git@github.com:preservim/nerdtree.git'                  				" File Tree
	Plug 'git@github.com:kien/ctrlp.vim.git'                      				" File Search

	" Org Mode Setup
	Plug 'git@github.com:nvim-treesitter/nvim-treesitter' 						" Needed for Org Mode
	Plug 'git@github.com:nvim-orgmode/orgmode' 									" Org Mode
	Plug 'git@github.com:akinsho/org-bullets.nvim' 								" Org Mode Bullets
	Plug 'git@github.com:dhruvasagar/vim-table-mode' 							" Org Mode Table
call plug#end()

" Treesitter crap for org mode
lua << EOF
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.org = {
  install_info = {
    url = 'https://github.com/milisims/tree-sitter-org',
    revision = 'f110024d539e676f25b72b7c80b0fd43c34264ef',
    files = {'src/parser.c', 'src/scanner.cc'},
  },
  filetype = 'org',
}

require'nvim-treesitter.configs'.setup {
  -- If TS highlights are not enabled at all, or disabled via `disable` prop, highlighting will fallback to default Vim syntax highlighting
  highlight = {
    enable = true,
    disable = {'org'}, -- Remove this to use TS highlighter for some of the highlights (Experimental)
    additional_vim_regex_highlighting = {'org'}, -- Required since TS highlighter doesn't support all syntax features (conceal)
  },
  ensure_installed = {'org'}, -- Or run :TSUpdate org
}

require('orgmode').setup({
  org_agenda_files = {'/run/media/haadi/Storage/Documents/org/agenda/*'},
  org_default_notes_file = '/run/media/haadi/Storage/Documents/org/*',
})
EOF
```

### OS / Distro

Arch Linux

### Neovim version/commit

0.6

### Additional context

Sorry if this is a stupid question on my end, I haven't seen anything for the nvim version, only regular vim. Hopefully this is rather easy to fix.

**Comment by levouh** [comment]
@Haadi-Khan do you have a sample `.org` file where you are experiencing this behavior?

**Comment by Haadi-Khan** [comment]
Here's my todo list. The X's present were manually entered by me. Sorry if the formatting's a bit wonky, I'm still relatively new to org mode, and this was a simple thing I threw together the other day. Thanks in advance
```
* School Work
** Daily Work
   * 
** APUSH
*** [ ] Document Assignment
** AP Stat
*** [ ] Daily HW
** AP Calc BC
*** [ ] Take Home Quiz
** IS Multi
*** [X] Tangents/Normal
*** [X] Curvature
*** [ ] Vector Test Part B
** IS CS
*** [ ] Substring Search
*** [ ] Regex
*** [X] Del Del Giudice Program
** Misc.
*** [ ] Stat HW
* Robotics
** [ ] Finish Template Program
** [ ] 
* Science Olympiad
** Detector
*** Binder
*** Build
**** [ ] Fix Circuit
**** [ ] Test with Lower Voltage
**** [ ] Install into proper container
**** [ ] Testing and create model
** Wifi Lab
*** Binder
*** Build
**** [ ] Create basic model
**** [ ] Test with parabolic dish
**** [ ] Refinement and testing
** It's About Time
*** Binder
*** Build
**** [ ] Refine testing apparatus
**** [ ] Practice testing
```

**Comment by levouh** [comment]
Based on the pattern that we use (which matches how _Emacs_ functions), the toggling of checkboxes would only work for bullet items under a headline. Headlines are anything that start with a `*`, whereas bullet items are either `-` or `+`. The pattern is:

```^(%s*[%-%+]%s*%[([%sXx%-]?)%])```

which basically boils down to:

`^`: Beginning of line
`(`: Start match group
`%s*`: Zero or more whitespaces
`[%-%+]`: Either a `-` or `+`
`...`

Given that pattern then, your sections should work given:

```
* Robotics
  - [ ] Finish Template Program
```

where the _headline_ is a section (e.g. _Robotics_), and specific items under that are "bullet". You can read more about how _Emacs_ handles these [here](https://orgmode.org/manual/Checkboxes.html).

Just to note the behavior is as expected, here is a cast of vanilla _Emacs_:

https://user-images.githubusercontent.com/31262046/147841329-e28f1b6a-ec80-42c7-8f9b-83a7a699af18.mp4

where the first action I do is toggle a "proper" checkbox item a few times (using the default binding noted in the aforementioned link) and then try to do the same on a headline item, which doesn't work as expected.

Hope this helps.

**Comment by Haadi-Khan** [comment]
Thank you very much, I probably should've checked with my installation of emacs to see if I was doing something wrong like that lol. Thanks for making this great plugin btw, forgot to mention earlier. Have a nice day

**Comment by levouh** [comment]
100% of the credit goes to @kristijanhusak, but glad we got this one figured out.
