### ISSUE TITLE
Feat: Refile to heading from capture

### ISSUE THREAD

**Issue by joshpetit** [nvim-orgmode/orgmode#196]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

https://orgmode.org/manual/Template-elements.html
```
(setq org-capture-templates
      '(("w" "Work time (file+headline "~/org/refile.org" "Work Timesheet")
         "** Working on %?\n%T")))
```

### Discussed in https://github.com/nvim-orgmode/orgmode/discussions/184

<div type='discussions-op-text'>

<sup>Originally posted by **joshpetit** December 13, 2021</sup>
I'm not sure if this is implemented yet, but I'd like to refile a template to a heading. For example having something like this:

```lua
    org_agenda_templates = {
        w = {
            description = 'Work time',
            template = '** Working on  %<%Y-%m-%d>\n%?',
            target = 'refile.org/Work Timesheet'
        },
    },
```

I'm not sure if I just do't have to syntax correct, if it's not implemented yet I can file a feature request.</div>

**Comment by joshpetit** [comment]
@kristijanhusak  I could get started working on this, the API I had in mind would be:

```lua
    org_agenda_templates = {
        w = {
            description = 'Work time',
            template = '** Working on  %<%Y-%m-%d>\n%?',
            target = 'refile.org'
            headline= 'Work Timesheet'
        },
    },
```
I think it would make sense to make the target include the header (i.e `refile.org/Work Timesheet`) just as you do for refiling within captures, but I think it matches the original API more by having it as a property. Thoughts?

**Comment by jgollenz** [comment]
Neat! With this path-like syntax you could also extend it for non-unique headlines (e.g. `refile.org/Work Timesheet/2022/projectA`), as long as there are no headlines with the same name on the same level. That would work regardless of it being a property or not. The property variant makes it a bit more clear imo.

Not really your focus with this issue, but how would this scale if we were to include the other target possibilities that orgmode offers (e.g. regex, id, etc.)?

**Comment by kristijanhusak** [comment]
@joshpetit that looks ok. Should be fairly simple to implement since refile prompt already supports something similar.

**Comment by joshpetit** [comment]
finished
