### ISSUE TITLE
Improper folding and error on whole buffer.

### ISSUE THREAD

**Issue by brongulus** [nvim-orgmode/orgmode#211]
### Describe the bug

Improper folding around `#+CAPTION`, `#+NAME` tags and not recognizing `+` as a subtopic indicator under a heading. Also the entire buffer is highlighted with having errors.

### Steps to reproduce

1. Open an Org file.
2. :TSInstall org
3. Use `Shift+Tab` to see the overview of an org file.

### Expected behavior

Using [orgmode] overview should fold all the things and only show the headings

### Emacs functionality

Proper folding around `#+CAPTION`, `#+NAME` tags and recognizing `+` as a subtopic indicator under a heading

### Minimal init.lua

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('nvim-treesitter.configs').setup({})

  local parser_config = require('nvim-treesitter.parsers').get_parser_configs()

  parser_config.org = {
    install_info = {
      url = 'https://github.com/milisims/tree-sitter-org',
      revision = 'f110024d539e676f25b72b7c80b0fd43c34264ef',
      files = {'src/parser.c', 'src/scanner.cc'},
    },
    filetype = 'org',
  }
  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[TSUpdate]]

  require('orgmode').setup()
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
vim.opt.conceallevel = 2
vim.opt.concealcursor = 'nc'
```

### Screenshots and recordings

Not folding content under `#+CAPTION` and `#+NAME` keywords
![image](https://user-images.githubusercontent.com/53148859/152500877-6f67f2bb-704b-49f5-b366-c54f5bf0503c.png)

Not Folding `+` statements
![Not Folding + statements](https://user-images.githubusercontent.com/53148859/152501194-b4fd0cbf-694e-4dac-acec-b6c706d70606.png)

Screenshot from minimal init:
![image](https://user-images.githubusercontent.com/53148859/152504318-9f2ad442-8056-4838-ad11-a76ee0035754.png)

### OS / Distro

EndeavourOS (Arch)

### Neovim version/commit

0.6.1

**Comment by oacar** [comment]
This might be already solved as I don't have `+` folding issue. Could you check https://github.com/nvim-orgmode/orgmode/issues/217#issuecomment-1030902346 and update tree-sitter org?

**Comment by kristijanhusak** [comment]
Please double check with latest master

**Comment by brongulus** [comment]
I did update org, used the instructions from the readme and the linked comment and did `TSUpdate` but there's still improper folding due to `#+CAPTION:` blocks.

**Comment by gerritvreeman** [comment]
I can reproduce this with the following file:
```org
#+title: A title here

* First heading
Some text.

#+caption: This is a caption
#+name: This is a label
[[file:img.png]]

* A second heading
Some more text.
```
Collapsing the first heading only folds up until the `#+caption:` line for me. I have `org_indent_mode` set to `noindent`, but it appears to occur regardless.

Does the `OrgmodeFoldExpr()` use treesitter? This might fall under a separate issue/request, but can we optionally choose to use treesitter folding? It may solve this issue and would also be nice to allow for folding src blocks.

**Comment by kristijanhusak** [comment]
This should be fixed now. I had hardcoded "directives" to not fold, but I didn't consider this case.

**Comment by kristijanhusak** [comment]
@Rational-Curiosity fix was pushed upstream.
Pull latest `nvim-orgmode`, run `:TSUpdate org`, restart nvim.
Thanks!

**Comment by Rational-Curiosity** [comment]
Nice. Thank you very much
