### ISSUE TITLE
Mapping with <leader> cannot work with which-key plugin of neovim. How to use the vim command or lua function bound with the key mapping.

### ISSUE THREAD

**Issue by meicale** [nvim-orgmode/orgmode#212]
### Describe the bug

It is a great job. I just find out a problem. I am use neovim with a bunch of plugins such as [which-key](https://github.com/folke/which-key.nvim), which is also helpful to me. Which-key is triggered automatically by the <leader> key in any buffer. So I cannot use the key mapping of this org-mode plugin in org file  buffer, too. I just wonder do you guys using which-key and how you guys solve this problem. Or How can I find out the actual command or lua function bound with the key mappings. Thank you so much.

### Steps to reproduce

1. nvim 6.0
2. which-key

### Expected behavior

properly activated and perform the action.

### Minimal init.lua

Quite a bunch of things. I follow this one https://github.com/LunarVim/Neovim-from-scratch

### OS / Distro

ubuntu 20.04

### Neovim version/commit

0.6.0

**Comment by jgollenz** [comment]
I use both which-key and orgmode and I don't have any issues. 

![image](https://user-images.githubusercontent.com/12050098/152587573-bd3f35e3-8eb6-462f-97e0-e8c37ba27afc.png)

Could you please elaborate on what you mean by `cannot use the key mapping of this org-mode plugin in org file buffer, too`? Do you mean that pressing <leader> will bring up which-key?

**Comment by psiho** [comment]
Me too. No issues with which-key and orgmode. I had no <Leader>o mapped to enything before though. But now, which-key automagically shows orgmode actions on <leader>o. Works quite well out of the box actually.

**Comment by meicale** [comment]
> I use both which-key and orgmode and I don't have any issues.
> 
> ![image](https://user-images.githubusercontent.com/12050098/152587573-bd3f35e3-8eb6-462f-97e0-e8c37ba27afc.png)
> 
> Could you please elaborate on what you mean by `cannot use the key mapping of this org-mode plugin in org file buffer, too`? Do you mean that pressing `<leader>` will bring up which-key?
Yes, When the  is pressed, the pop-up menu of which-key show up and I cannot finish the "hot-key"/key mapping in this plugin. Can you share your which-key setups?

**Comment by meicale** [comment]
> Me too. No issues with which-key and orgmode. I had no `<Leader>o` mapped to enything before though. But now, which-key automagically shows orgmode actions on `<leader>o`. Works quite well out of the box actually.

I have a bunch of setup / key mapping in which-key.  Would you mind sharing your  configs of vim? Thx!

**Comment by jgollenz** [comment]
My which-key config is identical to the [default](https://github.com/folke/which-key.nvim), except that I uncommented the lines about `key_labels`

The actual usage in my init.lua looks something like this:

```lua
-- Which-Key
local wk = require("which-key")
wk.register({
    ...       
    o = {
        name = "orgmode",
        a = { "agenda" },
        c = { "caption" },
    },
    ...
}, { prefix = "<Leader>" })
```

`...` is just indicating that I have a few more mappings defined

**Comment by meicale** [comment]
> @meicale my which-key config is identical to the [default](https://github.com/folke/which-key.nvim), except that I uncommented the lines about `key_labels`
> 
> The actual usage in my init.lua looks something like this:
> 
> ```lua
> -- Which-Key
> local wk = require("which-key")
> wk.register({
>     ...       
>     o = {
>         name = "orgmode",
>         a = { "agenda" },
>         c = { "caption" },
>     },
>     ...
> }, { prefix = "<Leader>" })
> ```
> 
> `...` is just indicating that I have a few more mappings defined

Thank you！ Follow your advice, I can set up some key mapping, but there are still some cannot be used. such as 
ih : select inner heading, etc. Can you use that?
Thank you all the same.

**Comment by jgollenz** [comment]
> select inner heading

Haven't used that before, so I got confused about the usage at first. But yes, when you use it correctly it works and it also shows up in the which-key popup. Those mappings are concerned with text objects. Try `vih`, that should select the inner heading.

**Comment by jgollenz** [comment]
@meicale do you still have issues with the key mappings?

**Comment by jgollenz** [comment]
@kristijanhusak probably safe to close this one

**Comment by kristijanhusak** [comment]
Thanks @jgollenz .
