### ISSUE TITLE
Minimal config doesn't work properly on Windows

### ISSUE THREAD

**Issue by Kyllingene** [nvim-orgmode/orgmode#218]
### Describe the bug

I experienced some issues with nvim-orgmode, and was trying to submit an issue; in doing so, however, I found that the minimal configuration doesn't seem work on Windows. I installed Neovim through the Windows installer.

### Steps to reproduce

1. Run Neovim with `nvim test.org -u minimal.lua`
2. Close update window once complete
3. Type `:w<Enter>`
4. At the bottom of the screen, a treesitter error pops up, stating there is "no parser for the 'org' language"

### Expected behavior

Neovim should write `test.org` without erroring.

### Minimal init.lua

<details><summary>minimal.lua</summary>

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('nvim-treesitter.configs').setup({})

  local parser_config = require('nvim-treesitter.parsers').get_parser_configs()

  parser_config.org = {
    install_info = {
      url = 'https://github.com/milisims/tree-sitter-org',
      revision = 'f110024d539e676f25b72b7c80b0fd43c34264ef',
      files = {'src/parser.c', 'src/scanner.cc'},
    },
    filetype = 'org',
  }
  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[TSUpdate]]

  require('orgmode').setup()
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```
</details>

### Screenshots and recordings

https://user-images.githubusercontent.com/69094702/153739916-277ca6aa-c072-4943-89b5-b17a67a6f123.mp4

### OS / Distro

Windows 11

### Neovim version/commit

0.6.1

### Additional context

The prior issue I was experiencing was keybindings doing nothing; however, they still do nothing with the minimal configuration, so it would seem something is wrong with nvim-orgmode on Windows in general.

**Comment by ashishvinayak** [comment]
@Kyllingene Did you install the org parser ?

`:TSInstall org`

**Comment by robclancy** [comment]
This really should be in the setup docs.

**Comment by jgollenz** [comment]
@robclancy installing it should be handled by [this line](https://github.com/nvim-orgmode/orgmode/blob/4647d20e33bf14c70fd44e1a4ee071ce1351d139/README.md?plain=1#L113).
