### ISSUE TITLE
The agenda view resizes it self on updates

### ISSUE THREAD

**Issue by blakesweeney** [nvim-orgmode/orgmode#219]
### Describe the bug

If you open the agenda view and update it it will resize itself. This is very annoying when it is moved into a vertical pane as it shrinks the area to work in. It would ideal if the view did not try to resize itself when it was updated.

### Steps to reproduce

1. Open your agenda
2. Move the agenda to a vertical pane (`<C-W>L`)
3. Refresh the agenda `r`

### Expected behavior

The agenda should not resize itself. 

### Minimal init.lua

Works with the provided minimal init.

### OS / Distro

mac OS

### Neovim version/commit

NVIM v0.7.0-dev

**Comment by kristijanhusak** [comment]
This should be fixed now. It will still resize automatically if you do not resize a window. Once it is resized, both vertically or horizontally, it will disable automatic resize.

**Comment by blakesweeney** [comment]
Thanks for the quick fix!
