### ISSUE TITLE
How to turn off automatic folding

### ISSUE THREAD

**Issue by Leiyi548** [nvim-orgmode/orgmode#221]
When I open the new .org file, it will collapse automatically. I don't want this effect.
![image](https://user-images.githubusercontent.com/76139422/154284590-a2a3cb71-091b-4774-8edc-d9fc4e249d05.png)
The effect I want：
![image](https://user-images.githubusercontent.com/76139422/154284701-cb8863be-6350-4d4a-bb5e-eebe27603cf5.png)

**Comment by kristijanhusak** [comment]
```vim
autocmd FileType org setlocal nofoldenable
```

**Comment by Leiyi548** [comment]
@kristijanhusak Thankyou!!!
