### ISSUE TITLE
Failed to setup treesitter grammar

### ISSUE THREAD

**Issue by mgoral** [nvim-orgmode/orgmode#222]
### Describe the bug

Hi, after updating my config from a manual setup of tree-sitter-org grammar to `require('orgmode').setup_ts_grammar()`, the following error is visible after `:TSUpdate org`

```
nvim-treesitter[org]: Failed to execute the following command:                          
{
  cmd = "mv",
  opts = {
    args = { "tree-sitter-org-tmp/tree-sitter-org-master", "tree-sitter-org" },
    cwd = "/home/mgoral/.local/share/nvim",
    stdio = {
      [2] = <userdata 1>,
      [3] = <userdata 2>
    }
  }
}
```

I believe the reason for the error is that tree-sitter-org uses "main" for its default branch, instead of "master" and according to https://github.com/nvim-treesitter/nvim-treesitter/issues/2260, it should be marked as `branch="main"`. I added it locally to `setup_ts_grammar` and it helped:

```
--- @param revision string?
local function setup_ts_grammar(revision)
  setup_ts_grammar_used = true
  local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
  parser_config.org = {
    install_info = {
      url = 'https://github.com/milisims/tree-sitter-org',
      revision = revision or _G.orgmode.ts_revision,
      branch = 'main',
      files = { 'src/parser.c', 'src/scanner.cc' },
    },
    filetype = 'org',
  }
end
```

Frankly, I don't know why it broke, because my manual configuration also didn't have the branch specified. Possibly it's some strange configuration of grammar, orgmode and treesitter's versions.

### Steps to reproduce

Use setup_ts_grammar to setup org-mode treesitter grammar.

### Expected behavior

`:TSUpdate org` should work

### Minimal init.lua

n/a

### OS / Distro

Debian Stable

### Neovim version/commit

0.6.1

**Comment by kristijanhusak** [comment]
Can you give me previous setup that you used?

**Comment by mgoral** [comment]
```
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.org = {
  install_info = {
    url = 'https://github.com/milisims/tree-sitter-org',
    files = {'src/parser.c', 'src/scanner.cc'},
    revision = 'f110024d539e676f25b72b7c80b0fd43c34264ef',
    -- branch = "main",
  },
  filetype = 'org',
}
```

**Comment by mgoral** [comment]
Hmm, the reason might be slightly different. I tried changing `require('orgmode').setup_ts_grammar()` to `require('orgmode').setup_ts_grammar('1c3eb533a9cf6800067357b59e03ac3f91fc3a54')` and it also worked.

I also have this configuration of orgmode:

```
loaded, orgmode = pcall(require, 'orgmode')
if not loaded then
    return
end

orgmode.setup({
...
})
```

where my `setup()` doesn't define `ts_revision`. Is it possible that this overrides `_G.orgmode`, which nvim-orgmode uses in `setup_ts_grammar()`? If so, do you think this should be somehow detected by the plugin?

**Comment by kristijanhusak** [comment]
What do you get when you execute `:lua print(_G.orgmode.ts_revision)` ? Looks like something messes up the value.

**Comment by mgoral** [comment]
I get `nil`. If I change my `orgmode` to `orgmode_local`, the correct revision is printed, so I guess that the output of pcall overwrites the global orgmode table.

I'll rename it in my config, or maybe declare as local. Strangely enough, I'm not able to reproduce the issue anymore, even without this rename. The issue might be closed, I guess, thanks for your help! :)

Nevertheless, I think that plugin could check if `ts_revision` is set and report an error in case that neither `ts_revision` nor the parameter passed to `setup_ts_grammar` is set.

**Comment by kristijanhusak** [comment]
I'll just make the revision private variable. There's no need for it to live on the global table. It can always be overridden through parameter.

**Comment by kristijanhusak** [comment]
Should be fixed now.
