### ISSUE TITLE
Naming: "agenda templates" is "capture templates" in emacs-orgmode

### ISSUE THREAD

**Issue by Maltimore** [nvim-orgmode/orgmode#223]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

https://orgmode.org/manual/Capture-templates.html

### Additional context

Why are the emacs-orgmode `capture templates` called `agenda templates` here? As far as I can see they don't really have much to do with the agenda (but I'm rather new to org-mode).

**Comment by kristijanhusak** [comment]
You are right. I don't know why I misnamed it. I'll fix it for now to support both ways so I don't introduce big BC break. Thanks.
