### ISSUE TITLE
Refile doesn't work correctly from one file to another

### ISSUE THREAD

**Issue by aareman** [nvim-orgmode/orgmode#224]
### Describe the bug

Refile doesn't work correctly from one org file to another. It works as expected within the same file, but not from capture or from another org file.

# Within same file
**before** 
![image](https://user-images.githubusercontent.com/10500823/155420616-1c60245f-dfb0-491f-81f8-2617c5e6ee2a.png)
**after**
![image](https://user-images.githubusercontent.com/10500823/155420673-ebad0d36-d3be-4208-92ac-e7626a54b99e.png)

# From another org file
**before**
![image](https://user-images.githubusercontent.com/10500823/155421018-f3a38c8e-69ad-4c82-bb82-9f1d26c9e364.png)

**after**
![image](https://user-images.githubusercontent.com/10500823/155421095-55802ba3-6ce0-4e68-a6ff-e815a1cf9ffb.png)

# From capture
does the same thing as from another org file (which makes sense that the behavior would match)

### Steps to reproduce

1. create an org file with outline like in images above
2. try refiling it to a new location (in my case main file was `dynamics.org` so I refiled it to `dynamics.org/h1`)
3. Do same for other case

### Expected behavior

It should behave like the first instance where it refiles to sub heading of the new heading you chose to refile it to.

# Also a feature request related to this :)

(As an aside, I think the refile menu should provide completion like a file path instead of having all headers within a file "flat" at same level of completion. This way you could tab it out `file.org/h1/h1.2/h1.2.3` which is better if you have subheadings with the same name as another, and is more intuitive as an organizational mechanism as it makes it like a file heirarchy)

NOTE- I am not sure how this feature lines up with emacs version of refiling.

### Minimal init.lua

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('nvim-treesitter.configs').setup({})
  vim.cmd[[packadd nvim-treesitter]]
require('orgmode').setup_ts_grammar()
  vim.cmd[[TSUpdate]]

  require('orgmode').setup({

  org_agenda_files =  "~/notes/org/**/*",
  org_default_notes_file = "~/notes/org/refile.org",
    })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

v0.7.0-dev+1027-gf02a5a7bd

**Comment by aareman** [comment]
I think the offending line might be 

https://github.com/aareman/orgmode.nvim/blob/17f770930be177f939f8e567f4590598cbcd8355/lua/orgmode/capture/init.lua#L88

**Comment by kristijanhusak** [comment]
The bug should be fixed now. Regarding the feature request, I implemented it how Emacs Orgmode works, even though emacs is much more restrictive about refile destination options (needs more configuration there). This would also drastically complicate autocompletion because of the nesting and figuring out the context.

**Comment by kristijanhusak** [comment]
This should be fixed now. Let me know if you find any other issues.
