### ISSUE TITLE
Exclude cat/tag from filter in agenda

### ISSUE THREAD

**Issue by aareman** [nvim-orgmode/orgmode#232]
### Does this feature exist in Emacs orgmode core?

YES

![image](https://user-images.githubusercontent.com/10500823/160185101-cde22df3-316f-4dd8-98d5-ce283d7dce9b.png)

### Orgmode link
https://www.gnu.org/software/emacs/manual/html_node/org/Filtering_002flimiting-agenda-items.html
### Feature value

Ability to exclude categories and tags in a filter

so `-refile` would exclude anything in the refile.org file or `-tasks+refile` would give everything in refile.org without the tasks tag.

My own use case is, I have a `personal.org` file that contains all personal related stuff, but then i have a lot of other files for work stuff including the main refile.org. however, when I'm at work and have my agenda open, I don't want personal things showing up in it. Being able to filter out personal would be very helpful.

Thank you for this awesome plugin, helps me a lot in team management. :)

**Comment by kristijanhusak** [comment]
Filter wasn't working properly for exclusion, so I tweaked it now to work both ways. Give it a test and let me know if it's not working as expected

**Comment by aareman** [comment]
Thank you. looks like its working. I will let you know if I come across anything.
