### ISSUE TITLE
Popup windows do not properly close

### ISSUE THREAD

**Issue by rahul13ramesh** [nvim-orgmode/orgmode#238]
### Describe the bug

Floating windows like help/calendar do not close properly when orgmode is opened from a startup screen like [startify](https://github.com/mhinz/vim-startify) or [alpha-nvim](https://github.com/goolord/alpha-nvim). The bug doesn't always occur but is frequent enough to reproduce.

### Steps to reproduce

1. Open editor: `nvim`
2. Open agenda: `<leader>oa` then `a`
3. Open help: `g?`
4. Close help: `q`

### Expected behavior

The floating window should close as expected

### Minimal init.lua

https://gist.github.com/rahul13ramesh/d49576ae3f4dc2fcdc9fa59db2019460

### Screenshots and recordings

![Screenshot-28-03-22-11:57:17](https://user-images.githubusercontent.com/15090318/160463580-558a0b87-132a-41c9-822d-dcdfcafbf190.png)
![Screenshot-28-03-22-11:57:31](https://user-images.githubusercontent.com/15090318/160463594-b3477142-1a47-4225-8e8f-7147c5a69202.png)

### OS / Distro

Manjaro 5.10.96

### Neovim version/commit

0.7.0

**Comment by kristijanhusak** [comment]
Your minimal init is using different commit hash. Can you use `require('orgmode').setup_ts_grammar()` and see if it still happens?

**Comment by rahul13ramesh** [comment]
I call `require('orgmode').setup_ts_grammar()` in line 41 of the minimal init

**Comment by kristijanhusak** [comment]
Replace [these lines](https://gist.github.com/rahul13ramesh/d49576ae3f4dc2fcdc9fa59db2019460#file-minimal_init-lua-L26-L37) with the `require('orgmode').setup_ts_grammar()`. Setup ts grammar does the same thing, but it sets the proper revision. I assume you copied this from my minimal init, so I'll fix it.

**Comment by rahul13ramesh** [comment]
I replaced the lines and the issue still persists.

**Comment by kristijanhusak** [comment]
Startify is doing some [shenanigans to preserve buffers](https://github.com/mhinz/vim-startify/blob/master/autoload/startify.vim#L1007-L1017). Should be fixed now.
