### ISSUE TITLE
org_capture_templates not picked up

### ISSUE THREAD

**Issue by caasi-dev** [nvim-orgmode/orgmode#244]
### Describe the bug

I am trying to add Journal entry to capture mode, and the settings are not being picked up

### Steps to reproduce

1. <Leader>oc
2. **j** key binding not listed

### Expected behavior

to list j keybinding so I can use template

### Emacs functionality

org_capture_templates

### Minimal init.lua

```
require('orgmode').setup({
    org_agenda_files = {'/data/NC/ORG/**/*'},
    org_default_notes_file = '/data/NC/ORG/agenda.org',
    org_todo_keywords = {'TODO(t)', 'WAITING(w)', '|', 'DONE(d)'},
    org_todo_keyword_faces = {
        WAITING = ':background #806731 :foreground #0b1610 :weight bold',
        DONE = ':background #416644 :foreground #0b1610 :slant italic',
        TODO = ':background #326777 :foreground #0b1610 :weight bold',
    },
    org_capture_templates = {
        t = {
            description = 'Task',
            template = '* TODO %?\n  %u',
        },
        j = { 
            description = 'Journal', 
            template = '\n*** %<%Y-%m-%d> %<%A>\n**** %U\n\n%?',
            target = '/data/NC/ORG/journal.org' 
        },
  },
})
```

### OS / Distro

Fedora 35

### Neovim version/commit

NVIM v0.7.0-dev+1379-gfce0d54eb

**Comment by kristijanhusak** [comment]
Does `org_agenda_templates` instead of `org_capture_templates` work? Are you using latest master?

**Comment by caasi-dev** [comment]
Yes that was the issue. I've missed the update 2 days ago, sorry to waste time, and thank you for rapid response!

![image](https://user-images.githubusercontent.com/60949037/161716166-be34e99f-2e64-4527-aa8f-fe45061993af.png)
