### ISSUE TITLE
Agenda only pulls from one file

### ISSUE THREAD

**Issue by schultzter** [nvim-orgmode/orgmode#247]
### Describe the bug

I have a bunch of org files, typically one per client and also a corporate one and a personal one. When I create my weekly agenda view it only pulls from Personal.org and none of my other org files. 

### Steps to reproduce

1. Configure orgmode to use all the files in a given directory (i.e.: org_agenda_files = 'C:/Users/user/Documents/Notebooks/*.org')
1. Create multiple org files with TODO that have SCHEDULED and  DEADLINE dates
2. Generate the agenda

### Expected behavior

The agenda will include TODO items from all the org files I have.

### Emacs functionality

The same org files work perfectly with Emacs. 

### Minimal init.lua

```lua
require('orgmode').setup({
  org_agenda_files = 'C:/Users/user/Documents/Notebooks/*.org',
  org_default_notes_file = 'C:/Users/user/Documents/Notebooks/refile.org',
  org_todo_keywords = {'TODO', 'INPROGRESS', 'BLOCKED', 'DONE'}
})
```

### OS / Distro

Windows 10

### Neovim version/commit

0.6.1

### Additional context

I've been flipping back and forth between Emacs and Neovim using the same set of files. I would really prefer to use Neovim ('cuz vi rocks).

**Comment by Maltimore** [comment]
My guess is it is a Windows issue, since for me the agenda consists of all org files.

**Comment by kristijanhusak** [comment]
@schultzter  what's the output for `echo &shellslash` for you?

**Comment by schultzter** [comment]
`echo &shellslash` returns 0 (zero)

**Comment by schultzter** [comment]
If I change the forward-slash to a back-slash in my init.lua file do I need to escape them somehow? 

Or is it okay like this? 

```lua
require('orgmode').setup({
  org_agenda_files = 'C:\Users\eric.schultz\Documents\Notebooks\*.org',
  org_default_notes_file = 'C:\Users\eric.schultz\Documents\Notebooks\refile.org',
  org_todo_keywords = {'TODO', 'INPROGRESS', 'BLOCKED', 'DONE'}
})
```

**Comment by kristijanhusak** [comment]
You can write them in double square bracket like this:
`[[ C:\Users\eric.schultz\Documents\Notebooks\*.org ]]`.

Let me know if converting to backslash worked out

**Comment by schultzter** [comment]
Thanks for the tip, but now I don't even get the the contents of my Personal.org in the Agenda!!!

Is there some way to turn on detailed logs so I can see what nvim-orgmode and possibly even Neovim are doing when I generate the agenda? 

```lua
require('orgmode').setup({
  org_agenda_files = [[ C:\Users\eric.schultz\Documents\Notebooks\*.org ]],
  org_default_notes_file = [[ C:\Users\eric.schultz\Documents\Notebooks\refile.org ]],
  org_todo_keywords = {'TODO', 'INPROGRESS', 'BLOCKED', 'DONE'}
})
```

**Comment by schultzter** [comment]
Here you go:

[image: image.png]

-- 
Headed for the second star to the right and straight on 'til morning...

  Eric Schultz

**Comment by kristijanhusak** [comment]
I can't see the image. Can you re-post it or just send the output content?

**Comment by schultzter** [comment]
It's the list of org files in the that directory:

![image](https://user-images.githubusercontent.com/30871/162637117-9c960e26-eb0f-4dfe-9ab8-ae31c20ed669.png)

![image](https://user-images.githubusercontent.com/30871/162637182-fb46e15b-848d-48a3-8ff2-bc31f4367e7a.png)

**Comment by andreadev-it** [comment]
Hi schultzter,
I've tested this in my local machine (running windows 10 with nvim 0.7.0) but I cannot seem to reproduce the problem.
Are all the org files correctly parsed by the plugin?
Have you tried upgrading to neovim 0.7 (if possible)?

**Comment by seantwie03** [comment]
I am also unable to reproduce this issue using nvim 0.7.0 in pwsh.exe.

**Comment by tricktux** [comment]
I confirm @seantwie03.

PSA: If you have folder structures in your org folder make use of the `**/*.org` `:h startstart-wildcard`

So the example below becomes:

```lua
require('orgmode').setup({
  org_agenda_files = [[ C:\Users\eric.schultz\Documents\Notebooks\**\*.org ]],
  org_default_notes_file = [[ C:\Users\eric.schultz\Documents\Notebooks\refile.org ]],
  org_todo_keywords = {'TODO', 'INPROGRESS', 'BLOCKED', 'DONE'}
})
```

**Comment by kristijanhusak** [comment]
Closing as inactive. If issue happens again, please open another issue and link this one in there.
