### ISSUE TITLE
Support Multi-Key Capture shortcuts

### ISSUE THREAD

**Issue by TravonteD** [nvim-orgmode/orgmode#248]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

https://orgmode.org/manual/Template-elements.html

> When using several keys, keys using the same prefix key must be sequential in the list and preceded by a 2-element entry explaining the prefix key

### Additional context

This would be a great addition since it would allow for categories of captures. For example, a "p" prefix for project-level captures that write to a readme.org within a source repo.

**Comment by jgollenz** [comment]
Ah nice! I didn't know that orgmode offers that. I just thought about adding this in my personal fork recently, as I already have some collisions for capture shortcut chars. Have not looked into it yet, but I strongly second this feature :+1:

**Comment by TravonteD** [comment]
I'm working on a PR to add this functionality

**Comment by kristijanhusak** [comment]
This was added by @TravonteD in https://github.com/nvim-orgmode/orgmode/pull/253. Thanks!
