### ISSUE TITLE
Paragraph navigation differs in normal & visual modes

### ISSUE THREAD

**Issue by iexos** [nvim-orgmode/orgmode#249]
### Describe the bug

I like using `{` and `}` to navigate from heading to heading, and it works well in normal mode. However, in visual mode it is using the regular vim behaviour and is thus inconsistent.

### Steps to reproduce

File:
```
* Heading 1
Text
* Heading 2
* Heading 3
Text

Text
* Heading 4

```
- From first line, press `}` in normal mode
- Go back to first line, press `v` and then `}`

### Expected behavior

Both times, the cursor should go to line 3. However, in visual mode it jumps to line 6.

### Minimal init.lua

https://gist.github.com/kristijanhusak/a0cb5f4eb2bad3e732a1d18d311ebe2f

### OS / Distro

Arch linux

### Neovim version/commit

0.6.1

**Comment by jgollenz** [comment]
@kristijanhusak is this likely to be a bug inside nvim-orgmode or does this come from treesitter (or the grammar)?

**Comment by kristijanhusak** [comment]
@jgollenz there is no mappings for visual mode, that's why it's not working.

**Comment by jgollenz** [comment]
Ah, thanks :) I vaguely recall a conversation about visual mode mappings. Is that a `wontfix` or can I take a look at it?

**Comment by kristijanhusak** [comment]
It's not a `wontfix`, you can look at it.

**Comment by jgollenz** [comment]
Found the convo: #164 (at the bottom). Hence my question about wontfix. Do you have a general vision on how this should play out? Just so I know what to keep in mind ;)

**Comment by kristijanhusak** [comment]
I think we could go with something like this. Taking this mapping from this issue as an example https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/config/mappings.lua#L70.
We could extend the right hand side to be a table with mode as key, and value as a path to a function that needs to be called (as it is working now). So for example this is how we would have normal, visual and operator mapping for this:
```lua
    org_previous_visible_heading = { 
      n = 'org_mappings.previous_visible_heading',
      x = 'org_mappings.previous_visible_heading_visual', -- different function if needed. If not, use the same value as for normal mapping
      o = {'org_mappings.previous_visible_heading_operator', true }, -- pass down the arguments to a function if needed.
      i = { callback = 'org_mappings.previous_visible_heading_insert', args = { true }, opts = { expr = true }, -- In case we need to provide something to the 4th argument of `vim.keymap.set`, like `expr` or `silent`
    },
    org_next_visible_heading = { 'org_mappings.next_visible_heading' } -- This behaves exactly as it behaves now. Only normal mapping
```

I would put this structure only where necessary, and use the old structure where the change is not needed. When parsing the config it just needs to be handled accordingly.

On the config side, we would do something similar.

```lua
require('orgmode').setup({
  mappings = {
    org = {
      org_previous_visible_heading = { n = '{', x = '[', o = '{' } -- custom mapping for each mode if needed
      org_next_visible_heading = '}' -- This would map the same key to all avaialble modes for the mapping
    }
  }
}
```

I think that would cover all necessary things to be able to extend the mappings. If you think updating everything in the `config/mappings.lua` to a specific structure would simplify things around parsing the mappings when defining them, you can give it a go. I wanted to keep it as readable as possible in the beginning, but I don't think that can be that easily achieved at this point. Maybe explicitness will be more understandable.

**Comment by jgollenz** [comment]
In this case, where we only need a mapping for normal- and visual-mode, would we just omit operator- and insert-mode or should we explicitly set them to a null value? I'd prefer the former

**Comment by jgollenz** [comment]
fyi I'm splitting this up into two PRs, one for this issue and one for the mapping in general

**Comment by kristijanhusak** [comment]
> In this case, where we only need a mapping for normal- and visual-mode, would we just omit operator- and insert-mode or should we explicitly set them to a null value? I'd prefer the former.
> 
> edit: you already did that for the config part, where you omitted insert-mode

Definitely former. I want to keep these things as slim as possible, because there's a lot of mappings.
