### ISSUE TITLE
How can I set the indent width?

### ISSUE THREAD

**Issue by cstsunfu** [nvim-orgmode/orgmode#256]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

The indentation width I am used to is 4 characters, and &shiftwidth==4. But orgmode seems to only support indentation of 2 characters, which becomes very inconvenient when I use some built-in shortcuts such as <leader>oxe to insert Effort in orgmode.

Could this plugin provide a way to configure the indent level or set indent width == &shiftwidth ?

### Additional context

![image](https://user-images.githubusercontent.com/24812659/163689931-9d88c3d3-f6e6-4357-8bc8-63c0db6f3e96.png)

**Comment by kristijanhusak** [comment]
Things are actually aligned according to the headline. If you would have a level 3 headline like this:
```
*** This is headline
```

Next line indentation will align with the headline title:
```
*** This is headline
    This is content
```

That's just how Orgmode works. If you indent content line manually to 4 spaces, it should continue using that indentation.

**Comment by cstsunfu** [comment]
> Things are actually aligned according to the headline. If you would have a level 3 headline like this:
> 
> ```
> *** This is headline
> ```
> 
> Next line indentation will align with the headline title:
> 
> ```
> *** This is headline
>     This is content
> ```
> 
> That's just how Orgmode works. If you indent content line manually to 4 spaces, it should continue using that indentation.

Thanks, I see the logic of the indent.
