### ISSUE TITLE
Support the new conceal support for tree-sitter

### ISSUE THREAD

**Issue by theHamsta** [nvim-orgmode/orgmode#261]
### Does this feature exist in Emacs orgmode core?

N/A

### Orgmode link

Emacs concealing works different to what Vim does. Emacs can do proper formatting

### Feature value

>> Known highlighting issues and limitations

>>   Anything that requires concealing ([org_hide_emphasis_markers](https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_hide_emphasis_markers), links concealing) is not (yet) supported in TS highlighter

I just wanted to give an update: concealing is now supported in Neovim 0.7 (https://github.com/neovim/neovim/pull/17776). So the feature could be added or the README updated.

**Comment by kristijanhusak** [comment]
With treesitter highlighting enabled, markup is now parsed and highlighted through tree-sitter + extmark. This now also allows having mixed highlights , like **~strikethrough~ in bold**, and having markup support where we didn't have it before, like in headline line.

Thanks for letting me know about this.
