### ISSUE TITLE
Some mappings cannot be deleted

### ISSUE THREAD

**Issue by ribelo** [nvim-orgmode/orgmode#276]
### Describe the bug

Deleting the default key mapping in some cases causes the plugin to load incorrectly, nevertheless the mapping remains unchanged.

### Steps to reproduce

C-x

### Expected behavior

Pressing C-x should not trigger any action.

### Minimal init.lua

```lua 
{mappings = {org = {org_timestamp_down = ""}}}
```

### OS / Distro

nixos

### Neovim version/commit

0.7

**Comment by kristijanhusak** [comment]
There is no built in option to unmap stuff, but you should be able to do something like this to achieve same thing:
```lua
  mappings = {
    org = {
      org_timestamp_down = '<nop>'
    },
  },
```

**Comment by kristijanhusak** [comment]
You can now fully skip setting up specific mapping by setting it to false.

```lua
  mappings = {
    org = {
      org_timestamp_down = false
    },
  },
```
