### ISSUE TITLE
org_timestamp_down/up changes the first number found in the line

### ISSUE THREAD

**Issue by ribelo** [nvim-orgmode/orgmode#277]
### Describe the bug

org_timestamp_down/up changes the first number found in the line

### Steps to reproduce

Standing on the line with the number in any position, press `<C-x>`.

### Expected behavior

The action should probably only be performed if the cursor is on the date. Also, strings of digits that are not dates should not be changed.

### Minimal init.lua

Not relevant

### OS / Distro

nixos

### Neovim version/commit

0.7

**Comment by kristijanhusak** [comment]
That is actually how vim behaves by default. For example, try opening up js file with this content:
```js
module.exports = {
  test: 1
}
```

Put cursor at the beginning of the second line, and press `<C-x>`. It will reduce 1 to 0 and jump cursor to it.
