### ISSUE TITLE
Folding causes invisible headings

### ISSUE THREAD

**Issue by oacar** [nvim-orgmode/orgmode#278]
### Describe the bug

Hi, I have an org file with several headings and some of them are invisible when folded. In terms of folding/unfolding functionality there is not any issues, it is just the visuals. See the screenshots. I'd appreciate any help.

Here is the test file I am using: 
```
* Header1
  foo
* Header2
  bar
** Subheader
   fofo2f1
* Header 3
  zet
```

### Steps to reproduce

1. Open file
2. Shift-tab to fold everything
3. Observe some headings are not visible

### Expected behavior

Headings should be visible when folded

### Emacs functionality

Parsing is fine on Emacs. 

### Minimal init.lua

```lua



require('packer').startup(function()
	use {'wbthomason/packer.nvim'}
	use {'nvim-treesitter/nvim-treesitter'}
	use {'nvim-orgmode/orgmode', config = function()
			require('orgmode').setup{}
		end
	}

end
)

require('orgmode').setup()
require('orgmode').setup_ts_grammar()
require'nvim-treesitter.configs'.setup {
	highlight = {
		enable=true,
		-- disable={'org'},
		additional_vim_regex_highlighting={'org'},
	},
	ensure_installed ={'org'},
}
vim.wo.foldmethod="expr"
vim.opt.foldexpr="nvim_treesitter#foldexpr()"

```

### Screenshots and recordings

<img width="115" alt="folded" src="https://user-images.githubusercontent.com/13300870/166517546-7bffdfe2-b692-4aea-95b7-88bec9163f1c.png">
<img width="125" alt="unfolded" src="https://user-images.githubusercontent.com/13300870/166517549-6242f4c7-fa77-4667-b8d0-a26a234c0d4b.png">

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

0.8.0-dev

**Comment by kristijanhusak** [comment]
This seems like a color scheme issue.
Try running this in cmd line:
```
:hi Folded guifg=#FFFFFF
```

**Comment by oacar** [comment]
Thanks for your reply. I guess it was caused by `headlines.nvim` . After updating it, the issue resolved. Closing.
