### ISSUE TITLE
Highlighing issues: Strikethrough and code highlights are conflicting

### ISSUE THREAD

**Issue by gzagatti** [nvim-orgmode/orgmode#279]
### Describe the bug

Write a text with an inline markup that mixes inline code or verbatim with another inline markup like bold or italic. This text will end up stricken through making it hard to read and against the writer's intentions:

![image](https://user-images.githubusercontent.com/11043156/166642226-9c58824b-e3c5-45ad-af38-865653abaab2.png)

### Steps to reproduce

Activate `tree-sitter` and write something like:

```org
Let's sum two numbers =(+ 1 2)= and again =(+ 3 4)=
```

This will cause the faulty strike.

### Expected behavior

I would expect code or verbatim markup to take precedence over other inline markups like bold or italic.

### Emacs functionality

In Emacs code or verbatim take precedence:

![image](https://user-images.githubusercontent.com/11043156/166642818-74718ee8-c744-4c52-83b6-ccd87edb845f.png)

Also note that the [orgmode manual](https://orgmode.org/manual/Emphasis-and-Monospace.html) is explicit about not processing code or verbatim string:

> You can make words ‘*bold*’, ‘/italic/’, ‘_underlined_’, ‘=verbatim=’ and ‘~code~’, and, if you must, ‘+strike-through+’. Text in the code and verbatim string is not processed for Org specific syntax; it is exported verbatim. 

### Minimal init.lua

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({})
  
  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[TSUpdate]]

  require('orgmode').setup()
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### Screenshots and recordings

Screenshots provided above.

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

0.7.0

**Comment by kristijanhusak** [comment]
Good catch. Should be fixed now.
Thanks.

**Comment by gzagatti** [comment]
Thanks for the quick fix. I can confirm that the issue has been fixed on my side.

Out of curiosity, I have noticed that you use `extmark` to highlight inline markups. Would it be even possible to use `treesitter`? If so, is that something that you plan to add? 

I just want to understand when `treesitter` is being used in this plugin to highlight text and when it is not.

**Comment by kristijanhusak** [comment]
I'm working on a separate branch to use treesitter to figure out the places where highlights are needed. Using only tree-sitter grammar to add the highlights is not possible, since org tree-sitter grammar doesn't support it. Under the hood Neovim also uses `extmark` to highlight tree-sitter nodes, just in a bit different way.

**Comment by kristijanhusak** [comment]
Just a heads up that I just updated markup highlighting to use tree-sitter parser to figure out which nodes to highlight. Let me know if you run into any issues.

**Comment by gzagatti** [comment]
Thanks for the updates!
