### ISSUE TITLE
Opening links with targets

### ISSUE THREAD

**Issue by andreadev-it** [nvim-orgmode/orgmode#281]
I'm not an expert on org mode, but from some searches I've made it looks like you can create a link to a specific part of a page with a syntax similar to this one:
```
[[file:./projects.org::10][Get to line 10 of file "projects.org"]]
[[file:./todo.org::Keyword][Move to file "todo.org" and do a search for "Keyword"]] 
```

I've tried both this syntax using this plugin, but it doesn't seem to work. The only thing I could do was pointing to a specific file, which works correctly.
Is this supported?

**Comment by kristijanhusak** [comment]
Those cases are not supported, but you can create link to headline by title, or by `CUSTOM_ID`.

```org
# projects.org

* My first headline
  :PROPERTIES:
  :CUSTOM_ID: my_id
  :END:
* My second headline
```

```
By headline title
[[file:./projects.org::*My second headline]]
```

```
By custom id:
[[file:./projects.org::#my_id]]
```

**Comment by andreadev-it** [comment]
Hi kristijan,
Thank you for the explanation! It would be perfect for my use-case, but even that doesn't seem to work on my pc...
This is what I wrote in my todo.org file:

```
[[file:~/Dropbox/org/progetti.org::#amazon_fb][Project link]]

[[file:~/Dropbox/org/progetti.org::**Migrations][Work website migrations]]
```

And this is what I have in my "progetti.org" file:
```
** Amazon-fallback
   :PROPERTIES:
   :CUSTOM_ID: amazon_fb
   :END:

** Migrations
   :PROPERTIES:
   :CUSTOM_ID: migrations
   :END:
```

Still, when using the shortcut it doesn't work. If I remove the "targets" it works fine.

**Comment by kristijanhusak** [comment]
Did you give it a try with minimal configuration?
Please provide information about your system and configuration. You can follow bug template for this.

**Comment by andreadev-it** [comment]
Just tried with a minimal config, keeping just treesitter and org. I've only set the leader key and the "conceallevel" and "concealcursor" options as intended by this plugin.
Still not working.
However, I checked the same situation on my ubuntu laptop (running debian) and there it's working, so it's probably a windows-related issue.

OS: Windows 10
Terminal emulator: Windows Terminal (Windows App)

nvim --version:
```
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az320-113

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
         fallback $VIM : "C:/Program Files/nvim/share/nvim"
```

**Comment by andreadev-it** [comment]
I've troubleshooted the problem and found out the "solution".
The problem is the way paths are handled by windows vs linux. Windows uses "\\" while linux uses "/".
If I set the file path the way I did it, it will work in linux but not in windows, while if I exchange all slashes with backslashes, the file will work on windows, but not in linux.

The problem becomes clear here: https://github.com/nvim-orgmode/orgmode/blob/b9de38e8ddb61832d24fcb8db460d7f811a3c936/lua/orgmode/org/hyperlinks.lua#L25
After this line, the returned file path has mixed backslashes and forward slashes on windows.

One way that a user can solve it, is to set the following option in init.lua on the windows machine:
```
vim.opt.shellslash = true
```
This way, expanding using the fnamemodify function will always return forward slashes.

Fixing this in the plugin seems trivial, but I'm not exactly sure what would be the best way to do it.

Hope that I was of some help :)

**Comment by kristijanhusak** [comment]
Thanks for figuring it out!

> Fixing this in the plugin seems trivial, but I'm not exactly sure what would be the best way to do it.

I agree, but maybe not everyone wants this behavior. 
I would just update readme [troubleshoot](https://github.com/nvim-orgmode/orgmode#troubleshoot) section with this information so people know how to fix it.

**Comment by andreadev-it** [comment]
Yes, indeed it seems like a good idea.
I was thinking about a function that would return properly formatted paths, but I'm not sure that's even possible, to be honest. Adding it to the troubleshooting section will be very helpful for sure!

**Comment by kristijanhusak** [comment]
Troubleshoot section added: https://github.com/nvim-orgmode/orgmode#jumping-to-file-path-is-not-working-for-paths-with-forward-slash

Thanks for our help!

**Comment by andreadev-it** [comment]
I'm sorry to open this again. I just wanted to give a warning: after setting the "shellslash" option, Packer.nvim stopped working correctly. I currently [opened an Issue on their github repo](https://github.com/wbthomason/packer.nvim/issues/911) to address this, but up until then, if someone is using packer, it's probably better not to set that variable.
