### ISSUE TITLE
field 'day' missing in date table

### ISSUE THREAD

**Issue by jgollenz** [nvim-orgmode/orgmode#284]
### Describe the bug

Opening a org file will produce the error seen in the screenshot below. It can be shushed away and I have at least one file that will show the error three times before going back to the actual buffer

### Steps to reproduce

See minimal `init.lua`

### Expected behavior

No error

### Minimal init.lua

@kristijanhusak sorry, but my setup is getting more elaborate by the day. Before I go down this rabbit-hole, do you have any hunch what could cause this? The `minimal_init.lua` does not reproduce the issue. 

edit: actually, `minimal_init.lua` does reproduce the error, but only on my large, personal files. Will see if I can isolate the cause.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/12050098/167502492-d1e0ef78-a250-401a-a7dd-e2834aa9787c.png)

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

0.7.0

### Additional context

Not sure if related, but at the same time this issue popped up, the time to load the agenda exploded. It takes roughly 5 seconds, same for other agenda commands (forward, backward, view month, etc.)

edit: also not sure if related, but I cannot fold headlines once they have been opened

**Comment by jgollenz** [comment]
Found it.

`echo "* <2022-5-09>" > foo.org`
`nvim -u minimal_init.lua ./foo.org`

Apparently the missing zero in front of the month makes it go haywire

**Comment by kristijanhusak** [comment]
I wasn't properly ignoring invalid dates. Should not happen any more.
