### ISSUE TITLE
Error when adding tags

### ISSUE THREAD

**Issue by gerazov** [nvim-orgmode/orgmode#295]
### Describe the bug

I press `<leader>ot` to add a tag and the following error message appears:
```
[orgmode] ....vim/plugged/orgmode/lua/orgmode/treesitter/headline.lua:66: start is higher than end 
```

I've tried reinstalling the parser for `org` in Treesitter, but the issue is still there. 

### Steps to reproduce

It only triggers on some of my org files. I've tried to reproduce it on a test file, but there it works, I don't really know why it triggers. 

Here's a zip with the file it's not working on:
[tag_bug.zip](https://github.com/nvim-orgmode/orgmode/files/8706251/tag_bug.zip)

### Expected behavior

Tag is added.

### Minimal init.lua

/

### Screenshots and recordings

![tags_bug](https://user-images.githubusercontent.com/15214418/168753660-67654b3c-67d0-4c60-9ea6-5e6071710b65.gif)

### OS / Distro

Manjaro 21.2.6

### Neovim version/commit

NVIM v0.8.0-dev+60-ga75efc237

**Comment by pureume** [comment]
I actually came here to file this same bug. I have only experienced this bug when the headline contains CJK/unicode text. So, for example, a headline with the phrase "안녕하세요" will trigger this behavior, but a headline with "Hello" does not.

I am using the stable release of Neovim 0.7 and fully updated tresitter etc.

**Comment by gerazov** [comment]
That's right - it triggers only when there's unicode in the headline :+1: 

![tags_bug 2](https://user-images.githubusercontent.com/15214418/169323397-a138ad45-37a2-4aa1-85e6-9da2a667e7ec.gif)

**Comment by cands** [comment]
I also experience this bug (headline including a word with umlaut character, if that is removed it works).

**Comment by jgollenz** [comment]
The error is because there is a mismatch between what treesitter thinks is the length of the headline title is and what neovim tells us when we do `vim.api.nvim_strwidth` on the title: 
![unicode](https://user-images.githubusercontent.com/12050098/171285169-5c15e33a-f97d-4c1e-89dd-c32a70d236db.gif)

as you can see in TSPlayground on the left, every unicode character entered counts towards two characters with treesitter.

@kristijanhusak what do you think, is that a problem with tree-sitter-org?

**Comment by kristijanhusak** [comment]
@jgollenz I don't think it's tree-sitter-org issue. I think [this line](https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/treesitter/headline.lua#L49) is the culprit. I'm just not sure why it was used. @joaomsa do you remember if you used `nvim_strwidth` for any specific reason here?

**Comment by jgollenz** [comment]
but how come `nvim_strwidth` returns a different value than treesitter? :thinking:

**Comment by kristijanhusak** [comment]
Unicode chars are generally a double width char, an treesitter returns them like that. strwidth returns a Unicode as 1 char instead of 2

**Comment by resolritter** [comment]
FWIW the `end_col` of a line can be gotten with `col([lnum, '$'])` (or `virtcol` or `charcol` if that's more appropriate).

**Comment by kristijanhusak** [comment]
I pushed some changes to master that should fix this. Can you give it a try?

**Comment by cands** [comment]
I can confirm that it works now on my machine (macOS 12.4).

**Comment by gerazov** [comment]
Confirming on my side - works :+1: 

Thanks :pray:
