### ISSUE TITLE
Suport for LaTex Environments, Fragments and Math 

### ISSUE THREAD

**Issue by gzagatti** [nvim-orgmode/orgmode#300]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

The Org syntax defines [LaTex Environments](https://orgmode.org/worg/dev/org-syntax.html#LaTeX_Environments) as a lesser environment and [LaTex Fragments](https://orgmode.org/worg/dev/org-syntax.html#LaTeX_Fragments) as an object. 

Both of these elements are important for writing mathematical formulas, like in the example below:

```org
I want to compute a sum \(1 + 1\) and another \(3 + 3\). 
Or even a block equation:

\[
2 + 2 
\]

Sometimes, I need to write multiple equations:

\begin{align*}
2x - 5y &= 8 \\
3x + 9y &= -12
\end{align*}
```

However, they are currently not supported in Vim and might cause bugs such as:

![image](https://user-images.githubusercontent.com/11043156/169942520-142f365c-bfa9-4890-9067-1c5c81ac6306.png)

and:

![image](https://user-images.githubusercontent.com/11043156/169942580-dd6a8de6-f9c5-4253-90d5-d5faabe1bd03.png)

**Comment by kristijanhusak** [comment]
From what I see in the tree-sitter grammar, only something like this is parsed like latex:
```
\begin{align}
2x - 5y &= 8 \\
3x + 9y &= -12
\end{align}
```
This is example from the docs, but without the `*` in the align.

I don't have any experience with LaTex, so I can barely help with anything.
I'll open up issue upstream and see what we can do.

**Comment by gzagatti** [comment]
I'm not yet completely familiar with syntax highlighting, but what I would expect based on the behavior of similar blocks in org is the following:

The `\begin{<block-name>} ... \end{<block-name}` as well as `\[ ... \]` should be highlighted in a similar format as `#+begin_src python ... #+end_src`. In both cases, the contents of fragment should be highlighted with TreeSitter using Latex as the source. To get the syntax correct it would be necessary to pass the whole block including the openings.

The `\begin{<block-name>*}` should be valid as is a valid LaTex block.

Finally, the `\( ... \)` element should be highlighted the same way as `~ ... ~` to distinguish it from the rest of the text. Anything inside of this block should be treated as it is.

I don't think you need any knowledge of LaTex. The good thing is that beside the lack of highlighting features. The document is exported correctly as you can see below. So the problem is only on the highlighting side.

![image](https://user-images.githubusercontent.com/11043156/170171197-ec885742-f2f3-416f-a5b9-acccd215dcee.png)

**Comment by kristijanhusak** [comment]
I just pushed a change that updates ts grammar to the latest version. Just get latest master and do `:TSUpdate org`.
This should make this chunk be highlighted properly (Also linked hlgroup for this to `Statement`, you can check [here](https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#highlight-groups) how to override):

```
\[
2 + 2 
\]

Sometimes, I need to write multiple equations:

\begin{align*}
2x - 5y &= 8 \\
3x + 9y &= -12
\end{align*}
```

But this is still treated as regular plain text
```
I want to compute a sum \(1 + 1\) and another \(3 + 3\). 
Or even a block equation:
```

I need to tweak some of the markup highlights to not make that strikethrough though.

**Comment by gzagatti** [comment]
That's perfect! It's all working well on my side. As always, thanks for the quick reaction as this is a package I use daily.
