### ISSUE TITLE
<TAB> not working in Agenda

### ISSUE THREAD

**Issue by steigerth** [nvim-orgmode/orgmode#306]
### Describe the bug

If I press the <TAB> key on my keyboard to open the selected TODO entry from my agenda nothing happens. Interestingly if I press <ENTER> key the TODO is opened in the current window.

### Steps to reproduce

1. Open Agenda with <leader>oa
2. Select a TODO entry and press <TAB>

### Expected behavior

TODO entry is openend in another window.

### Minimal init.lua

I used the following init.lua file: https://gist.github.com/kristijanhusak/a0cb5f4eb2bad3e732a1d18d311ebe2f

### OS / Distro

Debian 11

### Neovim version/commit

0.7

**Comment by kristijanhusak** [comment]
This bug was introduced with recent changes to mappings. Should be fixed now.
