### ISSUE TITLE
Non-ascii categories break agenda alignment

### ISSUE THREAD

**Issue by pureume** [nvim-orgmode/orgmode#308]
### Describe the bug

Entries in the agenda become misaligned if one or more entries for a given day has a category containing unicode characters. That is, on days where one or more entries have a unicode category name, all other non-unicode entries will receive extra padding between the category name and the "Scheduled: " label, causing them to appear misaligned.  This behavior occurs in all views of the agenda (daily, weekly, etc.).

### Steps to reproduce

1. Schedule (or set a deadline for) a task that has a unicode category name
2. Schedule (or set a deadline for) another task with a non-unicode category name on that same day

### Expected behavior

All entries in the agenda should "align" regardless of whether or not their category contains unicode characters or not. In other words, the presence of an entry in the agenda with a unicode category name should not cause the other entries of that same day to overcompensate the space between their category name and the "Scheduled: " label.

### Emacs functionality

In Emacs any mixture of ascii and unicode categories does not break alignment. All agenda entries display as expected.

### Minimal init.lua

Minimal init.lua, with basic `org_agenda_files` declaration:

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
	print('LOADINGCONFIG')
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({})

  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[runtime plugin/nvim-treesitter.lua]]
  vim.cmd[[TSUpdateSync org]]

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup{ org_agenda_files = {'~/org/*'} )

  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd[[edit!]]
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerCompileDone ++once lua load_config()]]
```

### Screenshots and recordings

A daily agenda view with two entries, both with ascii catetogry names and properly aligned:

![aligned](https://user-images.githubusercontent.com/105529568/170714243-98c15055-1ece-4903-8e72-dd32efbd075a.png)

A daily agenda view with two entries, one ascii and one Korean, improperly aligned:

![misaligned](https://user-images.githubusercontent.com/105529568/170714251-017d18b6-2600-4195-95f0-4d20c772c9d7.png)

### OS / Distro

Debian 11 (Bullseye)

### Neovim version/commit

0.7

### Additional context

I'm sorry if my description is unclear, but I think the screenshots I included explain the behavior I am reporting. Thanks again for all your hard work! :)

**Comment by gerazov** [comment]
Might be related to #295 :thinking: ?

**Comment by kristijanhusak** [comment]
I pushed some changes to master that should fix this. Can you give it a try?

**Comment by pureume** [comment]
It seems to be fixed, thank you :)
