### ISSUE TITLE
Add desc to orgmode keymap

### ISSUE THREAD

**Issue by danielnehrig** [nvim-orgmode/orgmode#314]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

Which Key access the "desc" property to display set keymaps
it would be great to have proper descriptions for orgmode mappings
```lua
vim.keymap.set(mode, command, { desc = "Description of the mapping" })
```

**Comment by jgollenz** [comment]
Does (n)vim expose a way to access the `desc` for all keymaps that are currently set?

**Comment by jgollenz** [comment]
Oh, you mean this [Which-Key](https://github.com/folke/which-key.nvim), right? Sure, we could add that :+1:

**Comment by jgollenz** [comment]
@kristijanhusak this can be done via the multi-mode mappings I added: 
```
    org_insert_todo_heading_respect_content = {
        n = {
            callback = 'org_mappings.insert_todo_heading_respect_content',
            args = {},
            opts = { desc = "foobar" },
        },
    },
```
buuuut doing that for every command is a bit overkill on how large that file should be. I propose to either:

1) allow that special case in `mappings.og`: `org_insert_todo_heading_respect_content = { org_mappings.insert_todo_heading_respect_content', desc = "foobar" }`


2) put the information into `defaults.lua`, as this is already the place where you put that information now:
    `org_insert_todo_heading_respect_content = { <Leader>oit', "Add new todo headling after current heading block on same level" } `

I think option two is more sensible
