### ISSUE TITLE
Links inside bullet lists are not highlighted and concealed

### ISSUE THREAD

**Issue by sarmong** [nvim-orgmode/orgmode#316]
### Describe the bug

When I put a link into a bullet list, it is not recognized by treesitter or syntax

### Steps to reproduce

1. Add the following lines to org file
```
- [[github.com][GitHub]]

 [[github.com][GitHub]]
```
2. Observe first line not being highlighted and concealed

### Expected behavior

Links inside bullet lists are parsed correctly

### Emacs functionality

In default doom-emacs config this works as expected

### Minimal init.lua

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"

local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{ "nvim-treesitter/nvim-treesitter" },
			{ "kristijanhusak/orgmode.nvim", branch = "master" },
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
		},
	})
end

_G.load_config = function()
	print("LOADINGCONFIG")
	require("orgmode").setup_ts_grammar()
	require("nvim-treesitter.configs").setup({})

	vim.cmd([[packadd nvim-treesitter]])
	vim.cmd([[runtime plugin/nvim-treesitter.lua]])
	vim.cmd([[TSUpdateSync org]])

	-- Close packer after install
	if vim.bo.filetype == "packer" then
		vim.api.nvim_win_close(0, true)
	end

	require("orgmode").setup()

	-- Reload current file if it's org file to reload tree-sitter
	if vim.bo.filetype == "org" then
		vim.cmd([[edit!]])
	end
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])

vim.opt.conceallevel = 3
vim.opt.concealcursor = "nc"
```

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/42828375/171174061-bc57eb31-68a6-4f39-be95-880350fed641.png)

### OS / Distro

Arch Linux

### Neovim version/commit

v0.8.0-dev

**Comment by kristijanhusak** [comment]
To get proper link concealing everywhere you need to use treesitter highlights. I updated minimal init to enable that by default now https://gist.github.com/kristijanhusak/a0cb5f4eb2bad3e732a1d18d311ebe2f

**Comment by kristijanhusak** [comment]
Yes. Make sure you are using latest minimal init from the link I provided in [previous comment](https://github.com/nvim-orgmode/orgmode/issues/316#issuecomment-1142194703), since I updated it when you reported this.

**Comment by sarmong** [comment]
@kristijanhusak

https://user-images.githubusercontent.com/42828375/171215015-2b8756c6-0c41-49ee-aace-c6f75eb3af36.mp4

**Comment by sarmong** [comment]
Tested on 0.7 - same result

**Comment by jgollenz** [comment]
@sarmong I can't open that video, Github says the file is corrupted.

I also tried with the minimal init and the concealing works as expected for me.

**Comment by kristijanhusak** [comment]
For me it happens randomly, but only if I use same minimal init every time. If i comment out packer installation every time, and just use what's already installed, it doesn't happen at all.
@sarmong is this happening with your regular configuration? IF you have treesitter highlights set up it should work fine.

**Comment by sarmong** [comment]
@jgollenz , please use chromium to watch the video. It doesn't for in Firefox for me either

**Comment by sarmong** [comment]
@kristijanhusak , yes, it is happening with my regular configuration. You can see [treesitter config here](https://github.com/sarmong/dotfiles/blob/master/nvim/.config/nvim/plugins/treesitter.lua#L38)

When I comment out the `disable = {'org'}`, conceal stops working completely in my config for some reason

**Comment by sarmong** [comment]
Same result. 

And when I ran `;TSUpdate org` - it said that all parsers were up-to-date.


Btw, shouldn't it be disabled as per Readme? If it's enabled, then both treesitter and regex highlighting run at the same time?

**Comment by kristijanhusak** [comment]
Readme is a bit outdated, since treesitter highlights now supports most of the things that were not available before. 
These settings should work fine:
```lua
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = { 'org' },
  },
```
Treesitter has bigger priority over regex syntax hl, so it will highlight treesitter, and what's left with syntax highlighting.

**Comment by sarmong** [comment]
If I do this in the minimal config, I do get the expected result as well. Which might make sense, because treesitter loads befor `PackerCompileDone` and loads without the right configuration. However, it's weird, that it doesn't work in my config

```diff
- vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]]
+ load_config()
```

**Comment by sarmong** [comment]
I found the reason. I wasn't properly loading orgmode config. Sorry for taking your time.

**Comment by petRUShka** [comment]
@sarmong what was the reason?

**Comment by sarmong** [comment]
@petRUShka man, I have no idea, it's been 1.5 years and I no longer use the plugin.
