### ISSUE TITLE
Tag Autocompletion

### ISSUE THREAD

**Issue by jgollenz** [nvim-orgmode/orgmode#317]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

I often forget the wording of certain tags and whether I created them already. This leads to me not finding all relevant headlines via tag search due to them being fragmented over multiple tags that are marginally different (and should really be only one tag). E.g. I want to tag something about programming language development. I'm not sure if the tag I used in the past is `lang_dev`, `language_dev` or `lang_development`. Ofc I can look up all those tags in the agenda search, but that's a hassle. Perhaps I named it something else altogether. 

Sticking with that example, the desired behavior would be identical to how refiling works now:

1. `<Leader>ot`
2. Prompt prints `Tags: `
3. OPTIONAL: Hit `<tab>` to see all tags (perhaps to resource demanding, have to test)
4. Enter `lang`
5. Hit `<tab>` and see only tags that start with (contain?) `lang`
6. Select the appropriate tag

Offtopic: another nice thing would be a custom agenda view that shows me all the tags in all my org-files and the number of headlines that have that tag, listed in descending order. Opening one tag with `<tab>` opens the same buffer as if I would have searched explicitly for that tag

**Comment by kristijanhusak** [comment]
This is already supported. Try pressing <tab> once the "Tags: " Prompt show up. It should show you all. Once you type letter or two, it should narrow down the results.

**Comment by jgollenz** [comment]
I must be seeing ghosts. Thought that didn't work but you're absolutely right. My bad
