### ISSUE TITLE
Non-Global Multiple Mappings Don't Work

### ISSUE THREAD

**Issue by TimCummings** [nvim-orgmode/orgmode#318]
### Describe the bug

Following the [mapping instructions here](https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#mappings), I've been unable to get non-global multiple mappings to work. So far, I've tried some agenda mappings and org mappings, for example:

```
mappings = {
  agenda = {
    org_agenda_quit = { 'q', '<ESC>' }
  }
```

Single mappings (not a table) work, eg. `org_agenda_quit = '<ESC>'`. But a table, as above, doesn't work for any of the specified keys.

Multiple mappings (with a table), do seem to work for global mappings, eg.:

```
global = {
  org_agenda = {'gA', '<Leader>oa'},
  org_capture = {'gC', '<Leader>oc'}
}
```

### Steps to reproduce

1. Specify a custom non-global multiple mapping (like agenda's `org_agenda_quit` or org's `org_cycle`.)
2. None of the keys specified in the multiple mapping will perform the mapped function.

### Expected behavior

When specifying a custom non-global multiple mapping, all specified keys will perform the mapped function.

### Emacs functionality

N/A

### Minimal init.lua

For this example, `q` or `<ESC>` should quit out of orgmode agenda (task view), but neither do.

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })

  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[runtime plugin/nvim-treesitter.lua]]
  vim.cmd[[TSUpdateSync org]]

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup({
    mappings = {
      agenda = {
        org_agenda_quit = { 'q', '<ESC>' }
      }
    }
  })

  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd[[edit!]]
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerCompileDone ++once lua load_config()]]
```

### OS / Distro

Pop!_OS 21.10, MacOS 12.3.1

### Neovim version/commit

0.7.0

**Comment by jgollenz** [comment]
I can confirm that bug. Will have a look at it

**Comment by jgollenz** [comment]
@TimCummings could you please checkout [this branch](https://github.com/jgollenz/orgmode/tree/fix/multi-key-mappings) and see if it works now? Thanks

**Comment by TimCummings** [comment]
It's working now, thanks so much!
