### ISSUE TITLE
minimal_init.lua into this repository?

### ISSUE THREAD

**Issue by Maltimore** [nvim-orgmode/orgmode#325]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

1. It is more convenient to get the up-to-date `minimal_init.lua` from this repository (especially when one has a local clone of it), than to search via the github web interface for the newest one. The way I get the newest one is to start creating a github issue, and in the issue look for the link to the gist.
2. Makes it possible to update the `minimal_init.lua` by other contributors via pull requests.

**Comment by kristijanhusak** [comment]
Added in https://github.com/nvim-orgmode/orgmode/blob/master/scripts/minimal_init.lua
