### ISSUE TITLE
Capture deletes first line of previous buffer

### ISSUE THREAD

**Issue by Maltimore** [nvim-orgmode/orgmode#326]
### Describe the bug

Doing a capture deletes the first line in the file from which I started the capture.

### Steps to reproduce

1. Open nvim and load any file into, say, buffer `a`
2. `<leader>oc`
3. In the capture window: `:wq`
4. Observe that the first line of buffer `a` has been deleted.

### Expected behavior

No deletion.

### Minimal init.lua

All I changed from the `minimal_init.lua` is that I added a capture template, capturing to `~/tmp/test.org`.
(As an aside, I would suggest updating the `minimal_init.lua` such that a capture template and/or a default notes file is already set up).
```
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })

  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[runtime plugin/nvim-treesitter.lua]]
  vim.cmd[[TSUpdateSync org]]

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup({
    org_capture_templates = {
      t = {description = 'Todo', template = '* TODO %?', target = '~/tmp/test.org'},
    },
  })


  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd[[edit!]]
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerCompileDone ++once lua load_config()]]

```

### OS / Distro

Fedora 36 with alacritty 0.10.1

### Neovim version/commit

latest master

**Comment by kristijanhusak** [comment]
Confirmed. Will look into it.
Temporary workaround is to close the capture buffer with `Ctrl + c`.

**Comment by jgollenz** [comment]
Interesting. It deletes the first two lines for me, if they're top level headlines and a single headline if it has sub-headlines:

![capture-deletes-lines](https://user-images.githubusercontent.com/12050098/172576743-2c57273c-a440-496d-8d1b-c00e22ba1815.gif)

that's my full config mind you

**Comment by kristijanhusak** [comment]
[These lines](https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/capture/init.lua#L277-L279) are causing the issue, but fix would be a bit hacky. I want to refactor this class

**Comment by kristijanhusak** [comment]
I managed to find a simple fix until this gets refactored. Let me know if it's still broken.
