### ISSUE TITLE
Detect whether cursor is within closed fold?

### ISSUE THREAD

**Issue by Maltimore** [nvim-orgmode/orgmode#328]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

A typical problem is this: you load a new file. Vim remembers where your last cursor position was and puts the cursor there. Say the cursor position is within the body of some headline. But when a new file is loaded, the headline is folded, so the cursor appears to be at the headline itself, because the cursor is on the line indicating that there's a fold. Now when you do some org command like creating a new headline, you will be surprised that you might create some kind of intermediate headline, because you don't know that "in reality" your cursor is not on the headline, but somewhere in its body.

Hopefully the following makes it clear: https://asciinema.org/a/b9zg7fiHCl35E2xgsJYzz0Iu7

My proposal is this: if it's possible to detect that the cursor is on a fold, then org should "pretend" that the cursor is on the headline itself, not somewhere in the folded body. This way the user won't be surprised because she doesn't know where the cursor really is.

**Comment by jgollenz** [comment]
@Maltimore how do you load a new file and end up inside a fold? When I `:e <file>` the cursor will jump to the top of the file

**Comment by jgollenz** [comment]
I agree, your point is valid. However, `zc` not changing the line number until any vertical movement happens is default vim behavior and I'm not sure if we want to change that. Another option that comes to mind is to use `<tab>` for toggling the current fold, whether one is inside the fold or not

**Comment by Maltimore** [comment]
Yep! I also don't think we should move the cursor when closing the fold, that would go against the vim way. My suggestion is only that if the user does some org-action, like changing the TODO state or creating another headline, we should pretend that the cursor is on the headline line which determines the fold. So if the user changes TODO state, it changes the TODO state of the headline determining the fold, and not any other headline within the fold.

**Comment by jgollenz** [comment]
Sorry, I misunderstood you then. Thanks for clarifying. If there is a way to check whether the current line is within a fold, your suggestion sounds sensible. We would then need to find out which headline is the one responsible for the fold we're currently in, as we can fold up to the top-level with `zC`. Just thinking out loud here

**Comment by kristijanhusak** [comment]
When headline is opened from agenda, we do `zv` (see [here](https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/agenda/init.lua#L368)). I'm not sure how we would handle a case when file is opened outside of org (directly). This autocmd should do the trick, but I'm not sure if we should add it to the plugin, or let user decide if they want it or not:

```lua
vim.api.nvim_create_autocmd('BufReadPost', {
  pattern = '*.org',
  callback = function ()
    -- vim.schedule needed to make sure org is fully loaded
    vim.schedule(function()
      vim.cmd[[norm! zv]]
    end)
  end
})
```

**Comment by Maltimore** [comment]
Ah! This is really nice and really simple! Thanks a lot.
I would be in favor of including this in the plugin. But if not, we could add it to some sort of "Tips and Tricks" section in the docs.

**Comment by Maltimore** [comment]
In the interest of keeping the bug tracker lean and mean (not full of open issues), I am going to close this as it has been 95% fixed for me with the suggested workaround. The only remaining issue is the part where you close a fold but the cursor is still somewhere inside, and then you perform an org-action. This doesn't really happen that often. Once we work on some kind of "tips and tricks" section in the docs or on the website, I'll suggest the workaround there.
