### ISSUE TITLE
Add Evaluate Time Range

### ISSUE THREAD

**Issue by joshpetit** [nvim-orgmode/orgmode#333]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

`org-evaluate-time-range`

https://orgmode.org/manual/Creating-Timestamps.html

### Feature value

Whenever you need to update a clocked time, you can change the time stamp and then run evaluate time range to recompute the value

**Comment by kristijanhusak** [comment]
You should be already able to do this with `gq`. Go to the line where timestamps are and do `gqgq`

**Comment by joshpetit** [comment]
> You should be already able to do this with `gq`. Go to the line where timestamps are and do `gqgq`

This works thank you, but I don't see any documentation on it. Could it be added? Could it also be added to the help when you run `g?`? Is there an additional place that documents this keybinding?

**Comment by joshpetit** [comment]
Sorry, I was looking in the readme but see that it is [here](https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md). Thank you!
