### ISSUE TITLE
Recurring event leads to wrong sort order in agenda view

### ISSUE THREAD

**Issue by Maltimore** [nvim-orgmode/orgmode#337]
### Describe the bug

Recurring event leads to wrong sort order in agenda view.

### Steps to reproduce

Following org file:
``` org
* first event
<2022-06-16 Thu 11:00-13:30>
* second event
<2022-06-09 Thu 17:00-18:00 +1w>
```
leads to this agenda view:
```
Week-agenda (W24):
Monday     13 June 2022
Tuesday    14 June 2022
Wednesday  15 June 2022
Thursday   16 June 2022
  test:       17:00-18:00  second event
  test:       11:00-13:30  first event
Friday     17 June 2022
Saturday   18 June 2022
Sunday     19 June 2022
```
Note that this only happens if this is the 2nd or higher occurrence of the recurring event.
### Expected behavior

Second event should be displayed after first event.

### Minimal init.lua

used provided minimal init.lua with 1 additional line to define agenda files.

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

master

**Comment by kristijanhusak** [comment]
This issue should be fixed now. Let me know if it's still broken.
