### ISSUE TITLE
Agenda tag query with "M" doesn't exclude non-TODO headings

### ISSUE THREAD

**Issue by adwaymalhotra** [nvim-orgmode/orgmode#349]
### Describe the bug

When I search for TODO items using <leader>oaM, I still see Headings which are not TODOs.
[I think it's the same screen as when pressing "m"(screenshot)](https://user-images.githubusercontent.com/9569615/175063619-89228ede-63da-4400-b95e-a8a4567299c4.png)

### Steps to reproduce

Press <leader>oam; notice results
Press <leader>oaM; notice it's the same result as before

### Expected behavior

Non-TODO headings shouldn't be shown

### Emacs functionality

non-TODO headings are not shown on "M"

### Minimal init.lua
```
-- orgmode and notes plugins
require("orgmode").setup_ts_grammar()
require("orgmode").setup {
  org_agenda_files = "~/.local/share/org/orgmode/*",
  org_default_notes_file = "~/.local/share/org/orgmode/refile.org",
}
require("org-bullets").setup {
  concealcursor = true, -- If false then when the cursor is on a line underlying characters are visible
  symbols = {
    headlines = { " ", " ", " ", " ", " ", " " },
  },
}
require("pretty-fold").setup {}
```

### Screenshots and recordings

![(screenshot)](https://user-images.githubusercontent.com/9569615/175063619-89228ede-63da-4400-b95e-a8a4567299c4.png)

### OS / Distro

MacOS, Debian

### Neovim version/commit

0.8

**Comment by kristijanhusak** [comment]
Should be fixed now. Thanks for reporting.

**Comment by adwaymalhotra** [comment]
awesome! thanks!
