### ISSUE TITLE
Agenda shows nothing "TODO"s but "List fo all TODO entries" show all entries 

### ISSUE THREAD

**Issue by VolkovIlia** [nvim-orgmode/orgmode#351]
### Describe the bug

If I create any TODO task inside agenda menu or by commands, agenda view shows nothing.
Also <CR> does not work in agenda view.

### Steps to reproduce

1. press `gA` and `a` (for agenda menu)
2. press `gC` and `t` (for task creation)
3. Create task for next date and `:wq`
4. press `r` in agenda mode.
5. nothing but week days shown

### Expected behavior

Show the 'TODO' entry under the day

### Minimal init.lua
```lua
lua << EOF

-- Load custom tree-sitter grammar for org filetype
require('orgmode').setup_ts_grammar()

-- Tree-sitter configuration
require'nvim-treesitter.configs'.setup {
  -- If TS highlights are not enabled at all, or disabled via `disable` prop, highlighting will fallback to default Vim syntax highlighting
  highlight = {
    enable = true,
    disable = {'org'}, -- Remove this to use TS highlighter for some of the highlights (Experimental)
    additional_vim_regex_highlighting = {'org'}, -- Required since TS highlighter doesn't support all syntax features (conceal)
  },
  ensure_installed = {'org'}, -- Or run :TSUpdate org
}

require('orgmode').setup({
  org_agenda_files = '~/Orgmode/*',
  org_default_notes_file = '~/Orgmode/refile.org',
  mappings = {
        global = {
          org_agenda = 'gA',
          org_capture = 'gC'
        }
      }
})
EOF
```
### Screenshots and recordings

Here agenda view and tasks

![image](https://user-images.githubusercontent.com/43730119/175311682-f07de788-3f7f-4ce5-9c78-3b7b4f266cc2.png)

![image](https://user-images.githubusercontent.com/43730119/175312643-75d01b22-778b-4e0d-9198-f1c9df31bf96.png)

### OS / Distro

Artix Linux x86_64, Kernel: 5.15.48-1-lts

### Neovim version/commit

NVIM v0.7.0

**Comment by stoladev** [comment]
@VolkovIlia as said above, it is not showing up in your agenda because you have not scheduled / deadlined that TODO, so Agenda doesn't have anywhere specific to put it.

**Comment by VolkovIlia** [comment]
Thx a lot. my fault. Did not find any instructions for "DEADLINE" in starting guide.
