### ISSUE TITLE
Preceding <TAB> breaks timestamps

### ISSUE THREAD

**Issue by jgollenz** [nvim-orgmode/orgmode#362]
### Describe the bug

A <TAB> character that precedes a timestamp somehow breaks it. It does no longer show up in the agenda, one can't do `<Leader>oo` on it, `ctrl-[x|a]` is broken, `org_timestamp_[up|down]_day` is not working.

### Steps to reproduce

See screenshot. `foo` is not working, all the others are (except for `duh`, here only the highlighting is broken).

### Expected behavior

Would not expect any special behavior from preceding <TAB>

### Minimal init.lua

default

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/12050098/177094764-acdafbd9-8ab5-49ec-ac1a-9539321e85ea.png)

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

0.7.0

**Comment by kristijanhusak** [comment]
This seems like a tree-sitter-org grammar issue. I'll open upstream.

**Comment by kristijanhusak** [comment]
This was fixed in the grammar so should be working fine now after the update.
