### ISSUE TITLE
Vim error when opening agenda with <Leader>oa

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-orgmode/orgmode#364]
### Describe the bug

![Screenshot from 2022-07-04 09-48-45](https://user-images.githubusercontent.com/17055027/177158423-1ef29847-3708-4f2b-831c-a6f44dd78149.png)

### Steps to reproduce

Just pressing <Leader>oa

### Expected behavior

Not to have this bug...

### Minimal init.lua

```
```

### Screenshots and recordings

![Screenshot from 2022-07-04 09-48-45](https://user-images.githubusercontent.com/17055027/177158319-2505db64-e78f-43ab-9b12-c475a0af6163.png)

### OS / Distro

Fedora 36

### Neovim version/commit

NVIM v0.8.0-dev

**Comment by hrqmonteiro** [comment]
This is just all buggy...

When i try to navigate through the TODOs, i receive all of this errors in the windows:

![Screenshot from 2022-07-04 09-53-23](https://user-images.githubusercontent.com/17055027/177159004-d9fb9307-4f87-49ae-b974-982e85938fb5.png)

**Comment by jgollenz** [comment]
Do the errors also appear when you open neovim with `nvim -u /path/to/minimal_init.lua your_file.org`? The `minimal_init.lua` can be found in the `scripts` folder of this repo.

**Comment by kristijanhusak** [comment]
You are using newer version of the tree-sitter grammar. Please follow installation instructions.

**Comment by SemyonDunaev** [comment]
> You are using newer version of the tree-sitter grammar. Please follow installation instructions.

I got the same error. I tried `:TSUpdate org` but it doesn't fix the error.

**Comment by kristijanhusak** [comment]
@SemyonDunaev how are you setting up installation of tree sitter grammar for org?

**Comment by SemyonDunaev** [comment]
> how are you setting up installation of tree sitter grammar for org?

Oh, God!
When I carefully copied the settings to show them - I found a small mistake...( that was `cofnig` )
Now it works.
Thank you! 👍🏻
