### ISSUE TITLE
None of the key bindings work

### ISSUE THREAD

**Issue by refaelsh** [nvim-orgmode/orgmode#367]
### Describe the bug

None of the key bindings defined by the plugin work. For example, one of the keybindings: https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_capture instead of opening the capture promt, just starts a new line in insert mode (because of the `o`) with the letter c in it (because of the `c`).

### Steps to reproduce

Just press `<Leader>oc`.

### Expected behavior

I expected the capture prompt to open.

### Emacs functionality

N/A

### Minimal init.lua

I just used the default settings as instructed here: https://github.com/nvim-orgmode/orgmode#setup.

### OS / Distro

NixOS

### Neovim version/commit

NeoVim 0.7.0

**Comment by refaelsh** [comment]
> @refaelsh may I ask what your leader key is and if it works fine for non-orgmode mappings?

Sure. My leader is the default, e.g., `\`. And yes, non-orgmode mappings work with the leader key.
I also tried remapping my leader to some thing else (`space`, `,`), it did not help.

**Comment by refaelsh** [comment]
@jgollenz Sorry for the delay. I will do it asap. My main machine died and I am trying to revive it from a back up.

**Comment by refaelsh** [comment]
> vim.keymap.set("n", "<Space>", "<NOP>", {noremap = true, silent = true})
> vim.g.mapleader = " "

This is working!
Hmm... that is probably means the problem is with me.
Got any idea?

**Comment by kristijanhusak** [comment]
@refaelsh what happens if you change your leader key to `,` in your own configuration, does that help?

**Comment by refaelsh** [comment]
> @refaelsh what happens if you change your leader key to `,` in your own configuration, does that help?

I already tried it, it does not help.

**Comment by kristijanhusak** [comment]
Oh, I didn't saw above comment about that. I'm assuming there's some clashing with other plugin(s), so you can debug it by disabling each plugin and see if that makes it work. If you figure it out please let us know.

**Comment by kristijanhusak** [comment]
Oh, I didn't saw above comment about that. I'm assuming there's some clashing with other plugin(s), so you can debug it by disabling each plugin and see if that makes it work. If you figure it out please let us know.

**Comment by refaelsh** [comment]
> Oh, I didn't saw above comment about that. I'm assuming there's some clashing with other plugin(s), so you can debug it by disabling each plugin and see if that makes it work. If you figure it out please let us know.

Good idea. I will try it and report back.

**Comment by jgollenz** [comment]
Interestingly enough, I'm not able to do `\oc` in the default `minimal_init.lua` either. It only works once I explicitly assign a leader key. Isn't backslash the default leader key?

**Comment by refaelsh** [comment]
> Interestingly enough, I'm not able to do `\oc` in the default `minimal_init.lua` either. It only works once I explicitly assign a leader key. Isn't backslash the default leader key?

As far as I googled, backlash (`\`) is indeed the default leader.

**Comment by refaelsh** [comment]
> > Oh, I didn't saw above comment about that. I'm assuming there's some clashing with other plugin(s), so you can debug it by disabling each plugin and see if that makes it work. If you figure it out please let us know.
> 
> Good idea. I will try it and report back.

I found the problematic plugin by disabling them one by one as you suggested.
Everything is fine now. Sorry for bother. I will close this.

Thank you all :-)

**Comment by kristijanhusak** [comment]
@refaelsh can you tell us which plugin caused the issue? In case someone else gets the similar issue.

**Comment by refaelsh** [comment]
It was `vim-fugitive`, but I dont have any explanation as to why - thats why I did not posted the name.
I highly suspect that some other interaction between `vim-fugitive` and my huge init.vim cause the problem.

P.S.
`my huge init.vim` - this is the reason I am exploring this plugin. Org Mode is an excellent way to write dotfiles.

**Comment by jgollenz** [comment]
I also use `vim-fugitive` and it works fine for me.

**Comment by SimonAM** [comment]
I had the same issue. 
I had to change vim.opt.timeoutlen to something higher than 100.
