### ISSUE TITLE
Incorrect priorities

### ISSUE THREAD

**Issue by jubnzv** [nvim-orgmode/orgmode#375]
### Describe the bug

I found two minor issues when setting a priority to the item.

They are small and have the same scope, so I report them in the single issue.

If an org-mode item doesn't have a priority, you could try to set either an empty priority or just press a `<Space>` in priorities prompt. In these cases you'll get `#[nil]` and `#[ ]` priorities accordingly.

### Steps to reproduce

1. Create a new org-mode element: `* test1`
2. Enter `<leader>o,` to open the priorities prompt
3. Just press `Enter`
4. You'll get `#[nil]`

1. Create a new org-mode element: `* test2`
2. Enter `<leader>o,` to open the priorities prompt
3. Enter ` ` (space) and press `Enter`
4. You'll get `#[ ]`

### Expected behavior

In the both cases we shouldn't add a new priority at all.

### Minimal init.lua

It is reproducible with the suggested [minimal_init.lua](https://github.com/nvim-orgmode/orgmode/blob/master/scripts/minimal_init.lua).

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/12023585/181028357-bb7d1b91-5d28-480e-9bb6-e22bd141d51c.png)

### OS / Distro

Debian testing

### Neovim version/commit

NVIM v0.8.0-dev+448-g7b2b44bce

**Comment by jgollenz** [comment]
Thanks @jubnzv, I can confirm this bug. It seems that one can also specify a priority that starts with one of the valid default letters we have for priorities. So 'abc', 'bar', 'ccccc' will result in `[#ABC]`, `[#BAR]` and `[#CCCCC]` respectively, but `duh` will result in `[#nil]`.

**Comment by jgollenz** [comment]
In Emacs orgmode it's only possible to add a single character. If it's valid, this priority gets assigned. If it's invalid, nothing gets insert and the user gets informed that the priority must be between `A` and `C`. This might be different when the priorities are multi-character strings, which I'm not sure is possible ([see here](https://orgmode.org/manual/Priorities.html)).

**Comment by jgollenz** [comment]
For the record, multi-character strings should™ be possible (according to [this](https://orgmode.org/manual/Priorities.html)) when one uses a numerical priority-scheme with above nine states. See #382
