### ISSUE TITLE
Please add support for `noweb` syntax

### ISSUE THREAD

**Issue by refaelsh** [nvim-orgmode/orgmode#377]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

Hi,

This is a feature suggestion. Can you please add support for the `noweb` syntax for Literate Programming?

[Here is the link to the requested feature in Org docs](https://orgmode.org/manual/Noweb-Reference-Syntax.html)

Thanks.

**Comment by kristijanhusak** [comment]
Basic support for tangle and noweb syntax was added in https://github.com/nvim-orgmode/orgmode/pull/685. 
For now I'm closing this issue. If anything else you want to report/request, please open up a separate issue.
