### ISSUE TITLE
Treesitter bug

### ISSUE THREAD

**Issue by mcepl** [nvim-orgmode/orgmode#381]
### Describe the bug

With the latest neovim, orgmode, and treesitter, all updated to the very latest, I get this error on the opening of org file:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/quer
y.lua:174: query: invalid structure at position 1148
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:174: in function 'parse_query
'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:121: in function 'set_query'
        ...er/start/orgmode/lua/orgmode/colors/todo_highlighter.lua:53: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

Just open org file.

### Expected behavior

No error messages.

### Minimal init.lua

NA

### OS / Distro

Linux/openSUSE/Tumbleweed (rolling distro as of 2022-07-30)

### Neovim version/commit

e59bc078

**Comment by kristijanhusak** [comment]
I cannot reproduce it. Please provide minimal init with some example org file.

**Comment by mcepl** [comment]
There was something wrong and it is OK now.
