### ISSUE TITLE
Telescope support

### ISSUE THREAD

**Issue by tott** [nvim-orgmode/orgmode#386]
### Does this feature exist in Emacs orgmode core?

N/A

### Orgmode link

First off - I love the plugin and just switched over to it after using todotxt for a long time. 

While the plugin does everything i need I'm wondering if there are any plans or existing implementations for better telescope support. For example when refiling it would be great to have the suggestions populate through telescope and have them easily be selectable.

I know that it all can be coded through the available APIs but wondering if there are any existing community implementations or plans to get this and other support into the plugin.

### Feature value

Enhanced productivity and speed as well as ease of use

**Comment by jgollenz** [comment]
I'm not aware of any existing plugins or plans. But I agree, it sounds worthwhile to add support for telescope. Do you mind adding a list of all the places you think it would be beneficial?

**Comment by tott** [comment]
Sure thing - here are some suggestions
- agenda.prompt
- capture.prompt
- capture.refile_headline_to_destination
- org_mappings.set_tags (suggestion of already used tags for easy adding)
- Match TAGS/PROP/TODO query suggestions

**Comment by ray-x** [comment]
May not be telescope, one idea I have is using vim.ui.input/vim.ui.select and hook 3rd UI (telescope, nui etc)  so user can select the target.
Also there is a telescope plugin : https://github.com/joaomsa/telescope-orgmode.nvim

**Comment by lyz-code** [comment]
The plugin suggested by @ray-x is not maintained. I've opened several issues and PR without answer, and for me is currently broken for the latest version of orgmode :(

Trying to fix it right now without any lua knowledge `(╥﹏╥)`

**Comment by lyz-code** [comment]
I managed to make it work in [my fork](https://github.com/lyz-code/telescope-orgmode.nvim) in case anyone is interested

**Comment by kristijanhusak** [comment]
I would suggest to open up suggestions/PRs on https://github.com/lyz-code/telescope-orgmode.nvim since this will not be implemented here.
