### ISSUE TITLE
Change calendar popup start day like ORG_AGENDA_START_DAY

### ISSUE THREAD

**Issue by Johnsonnn64** [nvim-orgmode/orgmode#390]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

Better visuals and ease of navigation

### Additional context

I've been searching through the docs for almost an hour but couldn't find anything else than changing the starting day of Org Agenda. Since I've only seen calendars starting with Sundays my whole life, it feels completely off seeing a week start with Mondays and it is really hard getting used to it.

**Comment by refaelsh** [comment]
I am a Sunday guy too :-)

**Comment by kristijanhusak** [comment]
I think having Sunday and Monday is good enough. I never saw anyone wanting to start from anything beside those two :)

**Comment by jgollenz** [comment]
Me neither, but oh was it great to see those modulos work :joy: next time I'll leave a note when I start working on something, to avoid races like these ;)

**Comment by Maltimore** [comment]
Let me know if this is too nitpicky.
I think we have too similar options now:

CALENDAR_WEEK_START_DAY
ORG_AGENDA_START_ON_WEEKDAY
ORG_AGENDA_START_DAY

The latter two exist also in emacs orgmode, so they shouldn't be changed. But I didn't find the first one (introduced here)  in emacs orgmode (I was just searching the web, not actually using emacs).
I suggest to rename `CALENDAR_WEEK_START_DAY` to `DATE_PICKER_START_DAY`.

And this is a bit more adventurous and probably not needed: One could also, if `CALENDAR_WEEK_START_DAY` is not set, use the setting of `ORG_AGENDA_START_ON_WEEKDAY` (if that is not set to `false`).

**Comment by kristijanhusak** [comment]
I found `calendar_week_start_day` from here https://emacs.stackexchange.com/a/42574. I tested it in emacs, and it works, so this is good to go.

**Comment by Maltimore** [comment]
Ah ok, I didn't find that!
Forget everything I said then, sorry for the noise! :)
