### ISSUE TITLE
[Expose Api Functions] suggestion expose more api functions

### ISSUE THREAD

**Issue by hiberabyss** [nvim-orgmode/orgmode#392]
### Does this feature exist in Emacs orgmode core?

No

### Feature value

For example, could expose `refile_to_end(dest)` function without needing user input, thus user could choose the dest file with fzf.vim.

**Comment by kristijanhusak** [comment]
This can now be done through api https://github.com/nvim-orgmode/orgmode/blob/master/doc/orgmode_api.txt#L27
