### ISSUE TITLE
Headlines behaving strangely

### ISSUE THREAD

**Issue by 19Doors** [nvim-orgmode/orgmode#395]
![ok](https://user-images.githubusercontent.com/82603504/184808908-fe3308ca-4710-4cd7-bfd7-3a0e1ab9756e.png)

Headline 1 works fine but headline 2 behaves strangely...

**Comment by jgollenz** [comment]
This looks like an issue with bullets to me. Can you confirm that the issue still persists without the bullets plugin enabled?

**Comment by 19Doors** [comment]
nope on removing my org-bullets it still remains the same

**Comment by refaelsh** [comment]
I might be mistaken, but it looks a bit similar to this issue: https://github.com/lukas-reineke/headlines.nvim/issues/41.

**Comment by 19Doors** [comment]
yes seems like the issue thanks
