### ISSUE TITLE
'edit' or 'tabnew' option for win_split_mode

### ISSUE THREAD

**Issue by Johnsonnn64** [nvim-orgmode/orgmode#398]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

I believe it would be better to have options to view the org-agenda in one full tab

### Additional context

`full = string.format('edit %s', name)` or `tab = string.format('tabnew %s', name)`
in orgmode/lua/orgmode/utils/init.lua `local cmd_by_split_mode`

**Comment by kristijanhusak** [comment]
You can easily achieve this if you set `win_split_mode = 'tabnew'` or `win_split_mode = 'edit'`.  You can read all options here https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#win_split_mode

**Comment by Johnsonnn64** [comment]
Thank you! Must have missed that part while reading the the documentations
