### ISSUE TITLE
[Bug] highlighting broken on neovim nightly

### ISSUE THREAD

**Issue by akinsho** [nvim-orgmode/orgmode#406]
### Describe the bug

Since neovim refactored the behaviour of treesitter highlights to remove the implicit highlight generation and allow hierarchical highlights, orgmode's highlights have not been working in nightly. This I believe is likely because highlights were defined using `@Org*` syntax, which no longer automagically creates highlights on nightly.

See https://github.com/neovim/neovim/issues/14090#issuecomment-1228444035. This was tweaked to work in nvim treesitter using https://github.com/nvim-treesitter/nvim-treesitter/pull/3365 for reference.

This currently looks like
<img width="906" alt="image" src="https://user-images.githubusercontent.com/22454918/189477297-273b668f-eb41-433c-8f99-7525b485a8e9.png">

### Steps to reproduce

1. Update to latest nightly
2. Ensure orgmode and parser are installed
3. Open ormode file

### Expected behavior

Highlighting should appear as normal

### Minimal init.lua

This doesn't require a specific config, as it is a global problem on all nightly builds.

### OS / Distro

macOS 12

### Neovim version/commit

NVIM v0.8.0-dev-2512-g30ca6d23a-dirty

**Comment by kristijanhusak** [comment]
Thanks for the references, it saved me some research time. I noticed the breaking change on the Neovim BC issue, but I hoped it won't affect us here :D

**Comment by akinsho** [comment]
Thanks for the quick fix 🙌🏿

**Comment by hgigas** [comment]
Very quick fix, nice.

Only default faces working now on nvim 0.8:

```
      org_todo_keyword_faces = {
        TODO = ':foreground DarkRed :weight bold',
        DONE = ':foreground DarkGreen :weight bold',
        WAIT = ':foreground cyan :weight bold',
        HOLD = ':foreground cyan :weight bold :underline t',
      },
```

![orgmode_highlight](https://user-images.githubusercontent.com/100573434/189502880-06a98099-7177-46d7-9fa2-c87beef93431.png)

**Comment by kristijanhusak** [comment]
> org_todo_keyword_faces = {
>         TODO = ':foreground DarkRed :weight bold',
>         DONE = ':foreground DarkGreen :weight bold',
>         WAIT = ':foreground cyan :weight bold',
>         HOLD = ':foreground cyan :weight bold :underline t',
>       },

Good catch, pushed a fix.

**Comment by hgigas** [comment]
Awesome, thanks a lot :-)
