### ISSUE TITLE
Floating window backround color

### ISSUE THREAD

**Issue by tcftbl** [nvim-orgmode/orgmode#412]
Hi,
Iooked through the documentation and browsed the source code, but didn't find how to change the backround color of the floating windows in agenda and capture modes. I'd like it to be the same color as the normal backround.

![screenshot](https://user-images.githubusercontent.com/29033868/190382989-8e0e88e0-432b-49ab-be42-96e6ae58ad34.png)

Other floating windows such as fzf have the correct backround color. I tested this with default colorscheme also, but the problem persist there. Thanks!

**Comment by kristijanhusak** [comment]
How is the background on the floating windows for signature help, diagnostics, etc?
We are not overriding any colors for this window (or any other floating window), so whatever is set to your `NormalFloat` highlight color should be used.
If you don't want to override it everywhere, but only for the org buffer, you can add something like this to your init.lua:

```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'org',
  command = 'set winhl=NormalFloat:Normal'
})
```

Note that I haven't test the code above, but it should work. You can read more about it on `:help winhl`.

**Comment by tcftbl** [comment]
That fixed it! Thanks for pointing me in the right way. Help windows and calendar work as expected, which is weird.

![screenshot](https://user-images.githubusercontent.com/29033868/190400124-bd8318c8-402f-4bb2-ac08-59d47b788567.png)

**Comment by kristijanhusak** [comment]
Yeah, because those automatically do what I wrote above. I edited my initial comment with that notice.
