### ISSUE TITLE
Paragraph starting with inline math causes error on Treesitter

### ISSUE THREAD

**Issue by gzagatti** [nvim-orgmode/orgmode#427]
### Describe the bug

A paragraph that starts with in-line math:

```org
\(1 + 1\) foobar
```

Causes a parsing error in Treesiter. The whole paragraph then fails to parse correctly.

### Steps to reproduce

Write any paragraph that starts with in-line math:

```org
\(1 + 1\) foobar
```

Highlight fails. Open `:TSNodeUnderCursor` and inspect the paragraph to find the error.

### Expected behavior

Correct parsing of paragraphs with in-line math.

### Emacs functionality

This functionality works in emacs.

### Minimal init.lua

N/A

### OS / Distro

Ubuntu 22.04

### Neovim version/commit

v0.8.0

**Comment by kristijanhusak** [comment]
I'll open up an issue upstream in the tree-sitter grammar.

**Comment by kristijanhusak** [comment]
This should be fixed now. Pull latest master and do `:TSUpdate org`.

**Comment by gzagatti** [comment]
Perfect! It's working for me too.
