### ISSUE TITLE
`g?` shows the same mappings for every agenda view

### ISSUE THREAD

**Issue by jgollenz** [nvim-orgmode/orgmode#445]
### Describe the bug

Mappings like `f - Go forward one span` are displayed in views that don't have spans (search, match tags, ...)

### Steps to reproduce

Open any agenda view that is not the actual agenda (list tags, search, match tags) and type `g?` to open the help

### Expected behavior

Only the key-mappings that are actually applicable to that view should be displayed

### Emacs functionality

-

### Minimal init.lua

scripts/minimal_init.lua

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

0.7.0

**Comment by jgollenz** [comment]
Started working on this. Would be easy in theory, if we could tell which of the different agenda views is displayed currently. The logic atm just checks the filetype, which is `orgagenda` for all of the views. In fact, we would just need to figure out whether it is the "default" agenda view or not, as its only mappings for the former that are not applicable to all the other views. I would divide the `orgagenda` table (in `help.lua`) into `agenda_specific` and `generic` mappings and then load both in the agenda view and just `generic` in the oher views. @kristijanhusak any ideas how we could tell them apart?

**Comment by kristijanhusak** [comment]
> any ideas how we could tell them apart?

Simplest would be just to set some buffer variable in the agenda buffer and pass it down to the help class when calling it.

**Comment by jgollenz** [comment]
Not sure what you mean with 'buffer variable', but `Help.show(opts)` already excepts opts, they just never get used (apparently). The check for `opts.type` in `_get_content_type` gets never triggered, if I'm not mistaken. Can we use these opts? If not, shall I remove them?

**Comment by kristijanhusak** [comment]
You are right, opts are not used. You can use them for this.

By buffer variable I mean to set something like `vim.b.agenda_view_type = 'agenda' | 'todos' | 'tags' | 'search'` when opening up the view, and then reading that variable when opening the help buffer and pass it down through opts.

Another solution is to just add some type to the all agenda views type, and just read it like `self.agenda.views[1].type`.
I'm ok with any of these.

**Comment by jgollenz** [comment]
The opts are used by `org_edit_src_show_help`, so they are needed. I'd like to use them for this issue as well, but I'm not sure how that would be feasible. There exists only one mapping (`org_agenda_show_help`) and I cannot now what type of agenda view should be passed by the time the mapping is defined. I could do something like the `timestamp_[up|down]` pair of functions that just calls something with different arguments: `org_agenda_show_help_full` and `org_agenda_show_help_partially` (image I came up with a better naming scheme). This is not too much added code, but also not as future proof as we would perhaps like? Then again, I did not intend to handle every agenda view differently, just whether it is the default agenda view or not.

The other options you outlined are possible ofc, but if we already have opts, I'd really like to utilize them. Maybe I'm overlooking something

**Comment by kristijanhusak** [comment]
Since you recently added a fix that opens up the agenda window before rendering the content, for purposes of handling offset, we can attach the current agenda view name to the window or buffer, as we do here for example https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/agenda/init.lua#L82. 
So you would have something like this:

```lua
function Agenda:open_agenda_view(View, opts)
  self:open_window()
  self.win_width = utils.winwidth()
  local view = View:new(vim.tbl_deep_extend('force', opts or {}, {
    filters = self.filters,
    win_width = self.win_width,
  })):build()
  self.views = { view }
  -- In each agenda view add `type` property that describes it, for example:
  -- `type = 'agenda'`, `type = 'search'`, `type = 'tags'`, `type = 'todos'`.
  vim.b.org_agenda_type = view.type
  return self:_render()
end

```
Then, in the `mappings.open_help` function, you can try to read that variable that you set (if it is set), and pass it down to the help class:

```lua
function OrgMappings:show_help()
  local type = vim.b.org_agenda_type
  return Help.show({ type = type })
end
```

Rest of the things you can handle in the Help class as it is done with edit_src.
