### ISSUE TITLE
Use Teal language

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-orgmode/orgmode#467]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

I'm thinking of converting the whole codebase to Teal (https://github.com/teal-language/tl). I think types might help DX and the general stability of the project, but I would need more thoughts, especially from someone who used Teal before.

**Comment by jgollenz** [comment]
I have never heard of Teal, but type-support sounds like a great idea in general :+1:  Do you plan on porting the whole thing at once or do you want to do it piece-by-piece? It could be a great opportunity to review the whole architecture and get rid of some legacy stuff, but it will also be a great effort

**Comment by kristijanhusak** [comment]
> Do you plan on porting the whole thing at once or do you want to do it piece-by-piece?

I'm not sure Teal supports compiling code that is not typed, like for example Typescript does with Javascript + allowJs.
Ideally whole thing would be moved at once, but it's a big effort as you said.

>  I assume you want to generate .lua files with the tl-compiler for the actual users of the plugin, correct?

Yeah, we would have `tl` folder that compiles everything to `lua` folder. We use `.vim` for syntax, ftplugin, etc., but I think that is ok to leave it as it is for the time being.

**Comment by jgollenz** [comment]
> Ideally whole thing would be moved at once

What is your plan for this? Do you want to do this wholly by yourself? One big PR? A branch?

**Comment by tricktux** [comment]
I think it's a great idea!

[packer](https://github.com/wbthomason/packer.nvim/tree/main) has a WIP branch where it was rewritten in Teal by one of the main neovim contributors.

**Comment by kristijanhusak** [comment]
I've decided not to take this path. We should leverage annotations.
