### ISSUE TITLE
:PROPERTIES: unfolding during Shift+Tab

### ISSUE THREAD

**Issue by seantwie03** [nvim-orgmode/orgmode#469]
### Describe the bug

First, just want to say this plugin seems great. I really appreciate the work that has gone into this port. I apologize if this is not the correct repository for this bug report.

The problem I am having is :PROPERTIES: becoming unfolded while pressing Shift+Tab. 

Emacs Orgmode does not unfold :PROPERTIES: unless you specifically move your cursor to them and press Tab.

The use-case is, the Orgzly app adds a CREATED property every time it creates a headline. Most of the time I don't want to see this information, I want it to stay folded.

### Steps to reproduce

Create the following Org file:

```
* Heading
:PROPERTIES:
:CREATED:  [2022-12-11 Sun 14:01]
:END:

Text under heading

** TODO Do a next thing
:PROPERTIES:
:CREATED:  [2022-12-11 Sun 14:01]
:END:

Text under the next thing

```

### Expected behavior

This is what Emacs Orgmode does: From fully folded, pressing Shift+Tab once should reveal the nested TODO. Pressing Shift+Tab a second time should reveal the Text under each heading and PROPERTIES should be shown, but folded. Pressing Shift+Tab a third time should completely fold the document.

### Minimal init.lua

[Default](https://raw.githubusercontent.com/nvim-orgmode/orgmode/master/scripts/minimal_init.lua)

### OS / Distro

Windows 10

### Neovim version/commit

0.8.1

**Comment by jgollenz** [comment]
This is the right place to file bug reports :+1: please share your `minimal_init.lua` if you get it to work under Windows, then we can add it to the repo ;)

**Comment by seantwie03** [comment]
Looks like I was mistaken about the `minimal_init.lua`. I thought since it had paths like `tmp/nvim/site/pack` it wouldn't work on Windows, but it worked just fine. I was able to run `nvim -u minimal_init.lua test.org` and reproduce the folding issue I described above.

**Comment by seantwie03** [comment]
I am using a different task manager now. Going to close this.
