### ISSUE TITLE
Allow using Tab for Folding and Ctrl-I for jumping forwards

### ISSUE THREAD

**Issue by gerazov** [nvim-orgmode/orgmode#474]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

Using `<Tab>` for folding hijacks `<C-i>` for jumping forwards in the jumplist. This can be a hinderance when navigating large `org` files. 

Since it's mapped to the same key in Terminal, one workaround is to check if there are forward jumps possible and then jump, and if none are available then folding can be applied like in [thalesmello/tabfold](https://github.com/thalesmello/tabfold).

**Comment by Maltimore** [comment]
This is fixed now with neovim adopting the kitty keyboard protocol: https://github.com/neovim/neovim/issues/14400

For this to work:
- need to be using a terminal emulator that supports the protocol (kitty, very recent alacritty, foot and a few others do)
- need to not be using tmux (see `:h <Tab>`)

**Comment by kristijanhusak** [comment]
Hey @gerazov 👋🏻 

You can either unmap it by setting `org_cycle = false` (https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_cycle) or map it to something else.

**Comment by gerazov** [comment]
hey - I did remap to `<Space><Space>` for folding - it took a while to get used to it though :sweat_smile: 

@Maltimore sounds good but I'm too dependant on tmux atm, maybe when I move to Zelij at some point in the future :+1:
