### ISSUE TITLE
Add org-store-link and org-insert-link

### ISSUE THREAD

**Issue by the-argus** [nvim-orgmode/orgmode#475]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

[https://orgmode.org/manual/Handling-Links.html](https://orgmode.org/manual/Handling-Links.html)

### Additional context

I think this is a high priority feature- at the moment I can use completion to autocomplete org files _if they're in my current working directory_, so typing ``[[file:`` and then letting autocomplete do the rest sometimes works. Not nearly as good as org-store-link and org-insert-link.

**Comment by jgollenz** [comment]
I started on `org-insert-link` a long time ago, I'll go look for the branch. As for `org-store-link`, this would (currently) only be relevant for org buffers and the agenda.

**Comment by the-argus** [comment]
thanks- keep me updated. I will try to find time to work on this feature if no one gets to it before me. If you had started on ``org-insert-link`` and no longer have time for it, I'd like to at least start working off of your WIP branch.

**Comment by jgollenz** [comment]
Sure thing :) I probably won't get around to it soon, so feel free to implement it. As for what I have so far, it's [not much](https://github.com/nvim-orgmode/orgmode/compare/master...jgollenz:orgmode:insert-link) and only what I personally wanted, not what is actually in Emacs orgmode, so be sure to check out the correct behavior. It's also ~10 months old and presumably outdated  (didn't check). Don't hesitate to ask any questions that come up. I'd suggest to start with `org-insert-link` and add `org-store-link` in a separate MR ;)

**Comment by the-argus** [comment]
I gave up and use obsidian now...

I won't be completing this issue anytime soon, but I'll leave it open because it definitely would help this project.

**Comment by jgollenz** [comment]
Sad to hear that. I hope it's not just because of this issue. Perhaps you have time for a little write-up on why you made the decision to switch. I've been using orgmode for a while now and it's not obvious to me what new users are missing. Thank you :)

**Comment by jgollenz** [comment]
@the-argus I implemented `org-insert-link` in #512 fyi
