### ISSUE TITLE
save to default file when `:wq`

### ISSUE THREAD

**Issue by zdog234** [nvim-orgmode/orgmode#477]
### Does this feature exist in Emacs orgmode core?

N/A

### Additional context

I know this is in theory doable with an autocmd, and it's not necessarily worth making a default behavior or configuration option, but it would at least be nice to document how to do this (namely, I'm not sure what vimscript cmd / lua function to call)

**Comment by kristijanhusak** [comment]
Are you talking about capture? This is already happening if you do `:wq` in the capture buffer.

**Comment by zdog234** [comment]
Oh, my bad. I see that that's been added since the last time I tried to use this. Sorry for the noise!
