### ISSUE TITLE
Text objects and motions for headings, subtrees and etc

### ISSUE THREAD

**Issue by petRUShka** [nvim-orgmode/orgmode#48]
**Does this feature exist in Emacs orgmode?**
N/A

**If answer to first question is "No", elaborate on how this feature is valuable and what problem does it solve.**

One cool feature of [jceb/vim-orgmode](https://github.com/jceb/vim-orgmode) is [text objects for orgmode](https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt#L343). It allows to combine power of orgmode and Vim ideas. Quotation:

>   Vim offers a mighty feature called |[text-objects](http://vimdoc.sourceforge.net/howto/sven/text.html)|. A text object is bound to
>   a certain character sequence that can be used in combination with all kinds
>   of editing and selection tasks.
> 
>   vim-orgmode implements a number of text objects to make editing org files
>   easier:
> 
> ```
>   ih                    inner heading, referring to the current heading
>                         excluding the heading level characters (*)
>   ah                    a heading, referring to the current heading including
>                         everything
>   ir                    inner subtree, starting with the current heading
>   ar                    a subtree, starting with the current heading
>   Oh                    inner outer heading, referring to the parent
>   Or                    inner outer heading, including subtree, referring to
>                         the parent
>   OH                    an outer heading
>   OT                    an outer subtree
> ``` 
>   Motions can be used like text objects as well. See |[orgguide-motion](https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt#L401)|.
> 

I thinks it is a very good idea to use powerful Vim features to interact with Org content.

**Additional context**
P.S. Having [motions](https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt#L401) should be also very useful.

**Comment by kristijanhusak** [comment]
I added support for motions. Check docs from here https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_next_visible_heading.

I'll add text objects separately.
I tested those text objects in `vim-orgmode`, but they don't behave so well for me.

I plan to add these (`v`, `<`, `>` and `^` marks the cursor):

* `ih` - select everything inside a heading except asterisks. By heading I mean the first line:
```
  v---------------------v
* TODO some text  :MYTAG:
  Some content
```
* `ah` - select everything inside a heading, including asterisks.
```
v-----------------------v
* TODO some text  :MYTAG:
  Some content
```

* `ic` - select all content of the subtree
```
* TODO some text  :MYTAG:
> DEADLINE: <2021-07-16 Fri>
  Some content <
```

* `ir` - select everything inside a subtree except asterisks:
```
  v
* TODO some text  :MYTAG:
  Some Content <
```

* `ar` - select everything inside a subtree including asterisks:
```
v  
* TODO some text  :MYTAG:
  Some Content <
```

Do you have some additional suggestions?

**Comment by petRUShka** [comment]
Looks like a great start!

I'm personally pretty happy with this objects but I think it nice to have full list implemented in vim-orgmode.

**Comment by kristijanhusak** [comment]
Could you give me some detailed breakdown what's the difference between some of these? I installed vim-orgmode and some of these behaved completely same to me, like `ih` and `ah` did the same, and `ir` also did the same thing like `ih` and `ah`. Maybe I'm missing something.

**Comment by petRUShka** [comment]
I've tested all the text-objects.

`ih`:

![2021-07-22-005805_253x173_scrot](https://user-images.githubusercontent.com/146893/126565641-60ac7029-9697-424e-9899-3b30f3d77bb3.png)

`ah`:

![2021-07-22-005817_265x186_scrot](https://user-images.githubusercontent.com/146893/126565650-50cc3b07-003a-4f39-b594-38db05317c1a.png)

`ir`:

![2021-07-22-005927_264x202_scrot](https://user-images.githubusercontent.com/146893/126565702-f8be1c65-78d5-4e08-9225-1dbd98244554.png)

`ar`:

![2021-07-22-005950_262x189_scrot](https://user-images.githubusercontent.com/146893/126565745-1cd9c191-548b-4586-a7ef-2ff012567d0a.png)

`Oh`:

![2021-07-22-010038_245x177_scrot](https://user-images.githubusercontent.com/146893/126565815-16290ebf-8461-4cd2-a1a3-6ae06e8205f3.png)

`Or`:

![2021-07-22-010108_275x194_scrot](https://user-images.githubusercontent.com/146893/126565849-f11e18a5-8552-451c-91d5-dcb4b6aab190.png)

`OH`:

![2021-07-22-010132_261x210_scrot](https://user-images.githubusercontent.com/146893/126565872-0dac06de-7f0a-4b06-93f4-7e7c28d0a29e.png)


`OT` doesn't work at all.

**Comment by petRUShka** [comment]
test file:

```org
* Header
** TODO task1
testh 
*** header 3
** TODO task2
* Header #2
```

**Comment by kristijanhusak** [comment]
Thanks @petRUShka , this is really helpful!

**Comment by petRUShka** [comment]
On test file from https://github.com/kristijanhusak/orgmode.nvim/issues/48#issuecomment-884528361 

- `var` and `vir` are working as on screenshot;
- `vah` and `vih` are the same;
- `vOh` doesn't work at all, instead `v0h` works (zero char works but not O char);
- `vOr` doesn't work at all, instead `v0r` works;
- `v0H` works;
- `vOH` works strange, it doesn't select all I want
![2021-10-13-222641_255x170_scrot](https://user-images.githubusercontent.com/146893/137200109-ebf99ee7-b337-4444-b647-3fe662f5b32e.png)

**Comment by kristijanhusak** [comment]
Folds were the issue. I didn't account for those. Pull latest tree-sitter branch and give it a test.

I tried vim-orgmode for some of these, and in certain situations it behaves differently, like when cursor is on an empty line, `vah` selects the stars, but if cursor is on a line with text, it doesn't. I'm not doing that, since it seems like a bug to me.

**Comment by petRUShka** [comment]
It looks like you've fixed this issue. Thanks a lot!

**Comment by petRUShka** [comment]
So what do you think on changing `0` to `O` in keybindings (for example `vOr` instead of `v0r`) to make things:
- compatible with vim-orgmode,
- more vim-like?

**Comment by petRUShka** [comment]
Please look at https://github.com/kristijanhusak/orgmode.nvim/issues/48#issuecomment-942657996 for details.

**Comment by kristijanhusak** [comment]
I updated it to be `O` instead of `0`.

**Comment by petRUShka** [comment]
Great! Thanks a lot

**Comment by kristijanhusak** [comment]
@petRUShka any updates on this?

**Comment by petRUShka** [comment]
Now it seems to work fine. I'll put my eye on it!

**Comment by Maltimore** [comment]
This may be slightly off-topic, but is there a reason why the character for "subtree" is `r` in the textobjects, but for instance in promote/demote heading it is `s`? If there's a good reason, I could make a documentation PR where I explain it.

**Comment by kristijanhusak** [comment]
@Maltimore `s` is used for built in operator motion for sentences. For example, `cis` is "change inside sentence". If we would use `s`, we would break that.
On the other side, `>s` is not an operator mapping so it's perfectly fine to use it there.

**Comment by Maltimore** [comment]
I think this issue could be closed then? Everything seems to be addressed.
I created a continuation of this issue (of sorts), for addition of more textobjects: #332

**Comment by kristijanhusak** [comment]
Yeah I think we are ok with closing this.
