### ISSUE TITLE
More Complete `org-tangle` Support

### ISSUE THREAD

**Issue by submartingales** [nvim-orgmode/orgmode#485]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

`org-tangle` is documented by org-mode official docs provided in https://orgmode.org/manual/Extracting-Source-Code.html

### Feature value

Nearly all famous emacs distributions e.g. `spacemacs` and `doomemacs` have rather good support for `org-tangle` and doom emacs even has an external `org-tangle` tool for extracting code from existing org-mode files without opening emacs   gui. And I hope this functionality can be soon added into `nvim-orgmode` as it serves a crucial part of some kind of typical org-mode practice.

**Comment by danilshvalov** [comment]
Please look at #617. If I haven't implemented something that might be useful to you, let me know about it.

**Comment by kristijanhusak** [comment]
Basic support for tangle and noweb syntax was added in https://github.com/nvim-orgmode/orgmode/pull/685. 
For now I'm closing this issue. If anything else you want to report/request, please open up a separate issue.
