### ISSUE TITLE
Support for .editorconfig defining org_todo_keywords

### ISSUE THREAD

**Issue by mcepl** [nvim-orgmode/orgmode#486]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

This is not exactly a feature of the plugin, just a possibility of the configuration, and frankly I don’t mind if it was a separate plugin like [my other one of the similar style](https://git.sr.ht/~mcepl/editorconfig-spell.nvim).

What I have in mind was an ability to setup per-directory (or per-project, or per-file … `.editorconfig` can do all three of those) value of `org_todo_keywords` via the  unofficial [editorconfig](https://editorconfig.org/) value `orgmode_todo_keywords`. Now, when [nvim supports editorconfig natively](https://github.com/neovim/neovim/issues/3988) and it still supports old [editorconfig.nvim functionality](https://github.com/gpanders/editorconfig.nvim/commit/26620a4d7e4f5a1a8944a825929eb38fc4937b17) of making tiny plugins for it, it seems like an ideal method how to do it.

I tried to do this:

```lua
require('editorconfig').properties.orgmode_todo_keywords = function(bufnr, val)
    local keywords_str = val:upper()
    local keywords = {}
    for k, v in  keywords_str:gmatch('(%S+),?') do
        keywords[k] = v
    end

    if (#keywords > 1) then
        require('orgmode').setup({
          org_todo_keywords = keywords
        })
    end
end
```

and then used this `.editorconfig`:

```ini
[*.org]
orgmode_todo_keywords = TODO,|,DONE,DECLINED
```

But apparently, it is not doing what it is supposed to (`org_todo_keywords` are unchanged). What I am doing wrong?

**Comment by danilshvalov** [comment]
If it's still relevant, try this:

```lua
require("editorconfig").properties.orgmode_todo_keywords = function(_, val)
  local keywords_str = val:upper()
  local lhs, rhs = unpack(vim.split(keywords_str, "|"))

  local keywords = {}
  local parse_keywords = function(str)
    for _, k in ipairs(vim.split(str, ",")) do
      table.insert(keywords, k)
    end
  end

  parse_keywords(lhs)
  if rhs then
    table.insert(keywords, "|")
    parse_keywords(rhs)
  end

  if #keywords > 1 then
    local Config = require("orgmode.config")
    Config:extend({
      org_todo_keywords = keywords,
    })
    require("orgmode.colors.todo_highlighter").add_todo_keyword_highlights()
  end
end
```

**Comment by mcepl** [comment]
That’s cool! Thank you!

**Comment by mcepl** [comment]
Now as a separate plugin at https://git.sr.ht/~mcepl/editorconfig-orgmode.nvim
