### ISSUE TITLE
Adding a Todo gives an error

### ISSUE THREAD

**Issue by raoulg** [nvim-orgmode/orgmode#497]
### Describe the bug

I have disabled all other plugins to make sure it's not caused by any interaction.
I have an empty todo.org file, and a basic setup.

Trying to add a todo causes an error, which is unexpected.

### Steps to reproduce

1. open an empty todo.org file
2. do <leader>oiT
3. `[orgmode] ...e/pack/packer/start/orgmode/lua/orgmode/org/mappings.lua:655: attempt to index local 'item' (a nil value)`

### Expected behavior

To insert a todo

### Minimal init.lua

used the minimal_init.lua unmodified

### OS / Distro

macOS 13.1

### Neovim version/commit

0.8.1

**Comment by jgollenz** [comment]
Can confirm this. It's because we don't handle empty files atm. Working on a fix

**Comment by jgollenz** [comment]
There is more to this issue. Consider this file

```
f|oo

* bar
```
Where the pipe denotes the location of the cursor. Adding a headline with `<leader>oit` should result in:
```
f

* TODO oo

* bar
```

Not sure if the empty lines after `f` and `* TODO oo` are configurable. Probably
