### ISSUE TITLE
spaced repetition extension support like org-drill or org-fc or pamparam?

### ISSUE THREAD

**Issue by ouyangjunyi** [nvim-orgmode/orgmode#498]
### Does this feature exist in Emacs orgmode core?

No

### Orgmode link

org-drill:
https://gitlab.com/phillord/org-drill/

pamparam:
https://github.com/abo-abo/pamparam

org-fc:
https://github.com/l3kn/org-fc

### Feature value

It is necessary to strip out of Anki apps that don't rely on these GUI interfaces at all. For most of the time, plain text support is enough.

I think nvim-orgmode is a good fit for integrating or providing such spaced repetition extension functionality with algorithms such as sm2. Just like the plug-ins for Emacs(org-drill, org-fc, pamparam). 

Supermemo provides some of the algorithms
https://super-memory.com/english/ol/sm2.htm

### Additional context

other TUI cli:

Markdown Flashcards:
https://github.com/bttger/markdown-flashcards

hascard
https://github.com/Yvee1/hascard

speki
https://github.com/TBS1996/speki

**Comment by jgollenz** [comment]
@ouyangjunyi @kristijanhusak I think this can be closed

**Comment by Tecpatl** [comment]
may consider:  https://github.com/Tecpatl/nvim-evidence
