### ISSUE TITLE
[Feature] support inline code

### ISSUE THREAD

**Issue by ray-x** [nvim-orgmode/orgmode#502]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

orgmode allow `~code~` and `=code=` to embed one line code in the doc.
The similar feature in markdown `code`A

reference in StackOverflow https://stackoverflow.com/questions/16186843/inline-code-in-org-mode

### Feature value

It will be more convenient to use inline embedding instead of src_LANG, 
and it is easy to type and easy to remember.

**Comment by Maltimore** [comment]
I think `nvim-orgmode` already has this feature. Did you try it?

**Comment by ray-x** [comment]
Yes, and no. It feel strange 
<img width="390" alt="image" src="https://user-images.githubusercontent.com/1681295/218350993-bd2dade9-f907-48bc-9c90-21194c8839a2.png">
Compared to markdown:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/1681295/218351166-cc29b1a5-81e2-4098-82c7-699924381b62.png">

Is there anything missing, e.g. concellevel etc? ( set to 1 in the above screenshot)

**Comment by kristijanhusak** [comment]
You need to set this to `true` to hide markers https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_hide_emphasis_markers
