### ISSUE TITLE
Allow the omission of `file:` when external linking for special cases.

### ISSUE THREAD

**Issue by sg1fan** [nvim-orgmode/orgmode#514]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

[External Links](https://orgmode.org/manual/External-Links.html)

### Additional context

From the link above: 

> As a special case, “file” prefix may be omitted if the file name is complete, e.g., it starts with ‘./’, or ‘/’.

For example, `[[file:./book/notes.org][notes]]`, `[[file:book/notes.org][notes]]`, and `[[./book/notes.org][notes]]` are all equivalent external links. However, `[[book/notes.org][notes]]` would be an internal link.

I'm currently unable to follow links of this form. For better compatibility with existing org-mode files, I think this type of link should be allowed.

**Comment by jgollenz** [comment]
Am I correct in the assumption that `./` and `/` are the only two cases that this is possible?

**Comment by jgollenz** [comment]
Actually, the external links should work already. Do neither of them work for you? What about `[[/absolute/path/to/book/notes.org][notes]]`.

**Comment by jgollenz** [comment]
So what _does_ the specification actually say on that issue? Should links be calculated relative to the path of the current buffer or relative to some org-directory

**Comment by jgollenz** [comment]
I can't reproduce the behavior you experience. This is what I created:

```
v root/
    root.org
  v test/
      test.org
    v nested/
        nested.org
```
with
```
-- root.org
[[file:./test/nested/nested.org]]

-- nested.org
[[file:../test.org]]
```

-- test.org
[[file:../root.org]]
```

This loop should not be possible, if the cwd of the editor was taken. Am I missing something?

**Comment by jgollenz** [comment]
Oh well, it breaks when I omit the `file:`. There we go. We actually already use the correct strategy, but not when we omit the `file:`.

**Comment by jgollenz** [comment]
My example is flawed. It doesn't say that `../` is a case that allow for omission of the `file:`. This should work:

```
root/
  root.org
  test/
    test.org
    nested/
      nested.org
```
```
-- root.org
[[./test/test.org]]

-- test.org
[[./nested/nested.org]]

-- nested.org
* success
```
but doesn't. I'm working on it.

**Comment by kristijanhusak** [comment]
These issues should've been solved with the recent refactor. If the problem persists, please open up a separate issue.
