### ISSUE TITLE
org id link

### ISSUE THREAD

**Issue by jgollenz** [nvim-orgmode/orgmode#515]
### Discussed in https://github.com/nvim-orgmode/orgmode/discussions/500

<div type='discussions-op-text'>

<sup>Originally posted by **WaytrueDeng** February  4, 2023</sup>
id link is a great feature which heavily used in org-roam, and it is easy to navigate to other file heading by id even after we change the file path.

may I ask do we have a plan to implement this feature?

thanks a lot for devs' hardworking</div>

**Comment by jgollenz** [comment]
I believe this functionality is implemented in [org-id.el](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/org-id.el) for org-mode.  In that file, we can see the various configuration variables. For example the variable `org-id-locations-file` can be set to a specific file, which will contain the id:filepath mappings. 

org-roam simply forces all linkable targets (which they call nodes) to be associated with an id, which is then stored in sqlite (instead of a plaintext file) along with its aliases so it can query for backlinks and aliases. However, if you suddenly turned off org-roam, you would still be able to traverse these id links with vanilla org-mode.

_Originally posted by @sg1fan in https://github.com/nvim-orgmode/orgmode/discussions/500#discussioncomment-5119630_

**Comment by jgollenz** [comment]
@sg1fan if you could point to any high level documentation for id links, I'd be grateful. I don't know any Lisp

**Comment by jgollenz** [comment]
Thanks a lot :pray: this site seems more helpful than [this](https://orgmode.org/manual/Command-and-Function-Index.html) (which seems to only list the functions that are actually used in the manual), but it is orgmode 9.0.9., which is a couple of years old now

**Comment by kristijanhusak** [comment]
This feature was added some time ago. Docs are here https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_id_uuid_program
