### ISSUE TITLE
Performance issues with treesitter when there is entry with :PROPERTIES:

### ISSUE THREAD

**Issue by WhiteBlackGoose** [nvim-orgmode/orgmode#521]
### Describe the bug

Adding a new entry under first level header gets incredibly slow (up to 1s lag). E. g.
```org
...
* Header
<caret>
```
In place of <caret> type *. It will lag for 500ms or so.

When I do it, it tries to redraw the whole thing on the first asterisk inserted. It does it wrong, because on the first asterisk it redraws everything into the color of the first level header. Especially noticeable when everything is expanded. 

### Steps to reproduce

1. Open [file](https://gist.github.com/WhiteBlackGoose/1c4c8b60c88c80d763e56be0fe29e4a4)
2. Go to header "Blog"
3. Type * (asterisk)
4. It redraws the whole thing into pink and lags for a second

### Expected behavior

Adding entries should be instant

### Minimal init.lua

Used the provided `minimal_init.lua` (no my configuration). [link](https://github.com/nvim-orgmode/orgmode/blob/master/scripts/minimal_init.lua)

### OS / Distro

NixOS

### Neovim version/commit

0.9-dev 5c9bf0ea74aa9297227242f17058a9f0c4c0c115

### Additional context

Thank you, this is an amazing plugin

**Comment by WhiteBlackGoose** [comment]
And it throws a lot of errors when I try to use it without TS. Very frustrating :( (in my file, lags can be 2-3 seconds)

**Comment by WhiteBlackGoose** [comment]
Workaround: insert space at the same time as asterisks
```lua
norm = { noremap = true, silent = true }
vim.api.nvim_set_keymap('n', 'c1', 'i*<space>', norm)
vim.api.nvim_set_keymap('n', 'c2', 'i**<space>', norm)
vim.api.nvim_set_keymap('n', 'c3', 'i***<space>', norm)
vim.api.nvim_set_keymap('n', 'c4', 'i****<space>', norm)
```
This works instantly. However, it's key that the space is inserted too. Otherwise, the same bug hits.

**Comment by jgollenz** [comment]
I can confirm this. This looks like a treesitter issue to me. I could narrow it down to

```org
* foo
    SCHEDULED: <2023-03-09 Thu>
    :PROPERTIES:
    :END:
|
* bar
  :PROPERTIES:
  :END:
```
(pipe represents the cursor)

Inserting the `*` at this point should result in an error that is not detected in this case. I'll have to do some further investigation. Another workaround would be to not insert new headings manually but with `<leader>oih` from the previous heading (or its body).

**Comment by WhiteBlackGoose** [comment]
The tree built by the treesitter also breaks often. I couldn't reproduce it yet, except when you type a few asterisks on a few line but not a space. But I feel like sometimes, headings without contents are interpreted compelteley wrong. E. g. folding in this text normally works as expected.

Expanded:
```
* Heading
** Another 1
** Another 2
** Another 3
** Another 4
```
Collapsed:
```
* Heading
```

Sometimes though the collapsed looks like this:

```
* Heading
** Another 3
** Another 4
```

**Comment by WhiteBlackGoose** [comment]
folding breaks too

Here's a correct tree and incorrect folding

![image](https://user-images.githubusercontent.com/31178401/223938048-9ba1a199-f643-4048-84c1-11dcce5a4c8c.png)

![ts-bug](https://user-images.githubusercontent.com/31178401/223938095-e739db8c-7c1d-4a15-9bff-9b377d2e64af.gif)

**Comment by rybaz** [comment]
Glad I'm not the only one having this issue. I have org files that previously worked fine not folding at all until I edit content underneath a heading, then it folds on itself.

**Comment by WhiteBlackGoose** [comment]
@rybaz you can use my fork (#523), folding works perfectly there

**Comment by jgollenz** [comment]
@WhiteBlackGoose @rybaz let's keep this issue on topic and move discussions about folding [here](https://github.com/nvim-orgmode/orgmode/issues/524)

**Comment by kristijanhusak** [comment]
Similar issue was reported here https://github.com/nvim-orgmode/orgmode/issues/625. It should be resolved on latest master + `:TSUpdate`.
