### ISSUE TITLE
cmp autocompletion

### ISSUE THREAD

**Issue by nikouusitalo** [nvim-orgmode/orgmode#522]
I cant get autocompletion for Date Now for deadline in demo i see there is "star" i dont see in my neovim when typing.

**Comment by jgollenz** [comment]
Hi @nikouusitalo :wave: could you please provide steps to reproduce this. An example file would be great!

**Comment by nikouusitalo** [comment]
Hi sure.
![2023-03-07_13-56](https://user-images.githubusercontent.com/54804770/223415911-f1d46593-0069-4512-a8a6-0fbdf0bded17.png)

**Comment by jgollenz** [comment]
I'm not sure if I understand your issue. Where is a 'star'? After `... Sun 17:25>`? That appears to be a trailing white-space. If you want to insert the current time, just write `:now:` in insert-mode and then hit space (or exit insert mode). If you want only the date without a specific time, type `:today:`.
