### ISSUE TITLE
`org-log-repeat`

### ISSUE THREAD

**Issue by xiugaze** [nvim-orgmode/orgmode#530]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

https://doc.endlessparentheses.com/Var/org-log-repeat.html

### Additional context

This would be a very nice to have for building out calendars or class schedules. I would like to be able to disable this globally, or at the very least get rid of the `State "DONE" from TODO` bullet that gets added on a repeat.

**Comment by kristijanhusak** [comment]
Added in https://github.com/nvim-orgmode/orgmode/pull/738.
