### ISSUE TITLE
Flaky test in agenda_item_spec.lua

### ISSUE THREAD

**Issue by Maltimore** [nvim-orgmode/orgmode#537]
### Describe the bug

In rare cases, the following error can happen during `make test`:

```
Fail    ||      Agenda item for today should accept deadline date for today, past unfinished tasks and future tasks within warning period
            .../repos/orgmode/tests/plenary/agenda/agenda_item_spec.lua:112: Expected objects to be the same.
            Passed in:
            (string) 'In 8 d.:'
            Expected:
            (string) 'In 9 d.:'

            stack traceback:
                .../repos/orgmode/tests/plenary/agenda/agenda_item_spec.lua:112: in function <.../repos/orgmode/tests/plenary/agenda/agenda_item_spec.lua:60>
```

### Steps to reproduce

1. Run `make test` many times

### Expected behavior

No error

### Emacs functionality

-

### Minimal init.lua

Used init.lua from tests

### OS / Distro

Ubuntu 22.04

### Neovim version/commit

master

**Comment by kristijanhusak** [comment]
Yeah this is due to DST. I'm not sure what's the best way to handle it. It fails only for a week or two.

**Comment by Maltimore** [comment]
Weird. It doesn't fail most of the time, even now during DST change.
I'm fine with closing this and just ignoring when it happens. We can always reopen the issue once more pressing issues have been resolved.
