### ISSUE TITLE
A few CLOCK in a :LOGBOOK: makes Neovim extremely slow

### ISSUE THREAD

**Issue by dodomorandi** [nvim-orgmode/orgmode#550]
### Describe the bug

Having a relatively high amount of `CLOCK` entries makes Neovim really slow.

### Steps to reproduce

1. Create a new `.org` file
2. Add a heading (i.e. `* Test`)
3. Clock in and clock out
4. Copy paste the `CLOCK` line 20 time (`yy20p`)
5. Try to edit the file furthermore to check for slowdowns (i.e. add a newline with `O`)

### Expected behavior

No slowdowns should be expected (we are not talking about file with thousands of lines), but Neovim at this point is slow performing many simple editing tasks.

### Minimal init.lua

It is just the template, with nothing changed.
```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup({
    {
      'wbthomason/packer.nvim',
      { 'nvim-treesitter/nvim-treesitter' },
      { 'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  })
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })

  vim.cmd([[packadd nvim-treesitter]])
  vim.cmd([[runtime plugin/nvim-treesitter.lua]])
  vim.cmd([[TSUpdateSync org]])

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup()

  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd([[edit!]])
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path })
  load_plugins()
  require('packer').sync()
  vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])
else
  load_plugins()
  load_config()
end
```

### OS / Distro

Arch Linux

### Neovim version/commit

NVIM v0.9.0

**Comment by jgollenz** [comment]
This slowdown is definitely happening for me as well. The issue does not seem to be the `CLOCK` entry but the timestamps that are associated with it. I get the same slowdown when I just add multiple timestamps (under a single heading, having multiple headlines with a single timestamp each seems to be no problem)

**Comment by dodomorandi** [comment]
Definitely! I should have phrased it in a better way, the issue is pretty much related to the timestamp.

> having multiple headlines with a single timestamp each seems to be no problem

Very interesting! I did not notice that.

**Comment by dodomorandi** [comment]
Apparently the slowdown increases linearly with the number of timestamps. Therefore I notice a comparable slowdown between N inactive timestamps and 2*N active timestamps.

Interesting enough, the slowdown is not affected by the fact that the timestamps are inside a `:LOGBOOK:` entry. In fact, if you just keep the timestamps and nothing else, the slowdown is still there.

There is another detail I forgot to mention: when the timestamps are concealed (because for instance you have them inside a section which is concealed), these timestamps *do not* contribute to any slowdown, apparently.

**Comment by jgollenz** [comment]
> Apparently the slowdown increases linearly with the number of timestamps. Therefore I notice a comparable slowdown between N inactive timestamps and 2*N active timestamps.

Interesting. When I turn the 40ish inactive timestamps into active timestamps, the slowdown decreases.

Thanks for the additional testing, I can confirm both behaviors :+1: I suspect this is somehow related to parsing, but I have to do some digging.

**Comment by kristijanhusak** [comment]
@jgollenz This is maybe caused by markup highlighter trying to parse these as hyperlinks. I didn't try, but it's worth checking.

**Comment by jgollenz** [comment]
> trying to parse these as hyperlinks

I think you are correct about that. I've been poking this for a while now and when I change [this line](https://github.com/nvim-orgmode/orgmode/blob/07d412eb15155c8391945a5bbbfd1caa996888bc/queries/org/markup.scm#L14) to 
`((expr "[" "[" @hyperlink.start) (expr "]" "]" @hyperlink.end) (#org-is-valid-hyperlink-range? @hyperlink.start @hyperlink.end))` I get a noticeable improvement. @kristijanhusak I'm not sure if that is the correct way to go. The slowdown appears to be at [iter_matches](https://github.com/nvim-orgmode/orgmode/blob/07d412eb15155c8391945a5bbbfd1caa996888bc/lua/orgmode/colors/markup_highlighter.lua#L246).

**Comment by kristijanhusak** [comment]
@dodomorandi can you pull the latest master and give it another test? Performance should be slightly better now. Slowness is still there while editing, but scrolling and going through the document should be slightly better.

**Comment by jgollenz** [comment]
> I did not find anything about profiling and benchmarking treesitter plugins

I managed to do some profiling with the profiler that is built into luajit (exposed via [plenary](https://github.com/nvim-lua/plenary.nvim#plenaryprofile). It was not exactly easy to setup because if your luajit distribution doesn't have the profiler you need to make some workarounds.

**Comment by kristijanhusak** [comment]
This should be resolved on latest master. Markup rendering performance was improved.
