### ISSUE TITLE
Refile Heading or TODO doesn't adapt the heading level

### ISSUE THREAD

**Issue by lyz-code** [nvim-orgmode/orgmode#557]
### Describe the bug

When refiling a level 3 heading or TODO item to a level 1 heading or TODO the level of the heading is not transformed to a level 2 heading or TODO.

The other way around does work, when refiling a level 1 element to a level 3 element, the refiled element level is transformed from level 1 to level 4.

### Steps to reproduce

1. Open the next file called `test.org` with the minimal configuration below:
```orgmode
* Heading 1
** Subheading 1
** Subheading 2
* Heading 2
*** SubSubheading 1
```
2. Hover with your cursor the `SubSubheading 1` section and press `<leader>or` (in the minimal config `<leader> == <space>`)
3. In the Destination enter `test.org/Heading 1` and press Enter.
4. The result of the refile is the following.
```orgmode
* Heading 1
** Subheading 1
** Subheading 2
*** SubSubheading 1
* Heading 2
```

As you can see now  instead of belonging to `Heading 1` it is listed under `Subheading 2` which is not desirable. When working with TODO items is awful because you may loose the context of what the task is about as it's listed as a subtask of the task you want it to be.

### Expected behavior

The level of the SubSubheading is updated to match the first level children of the target of the refile. In this case the result file would be:

```orgmode
* Heading 1
** Subheading 1
** Subheading 2
** SubSubheading 1
* Heading 2
```

Note that it is `** SubSubheading 1` instead of `*** SubSubheading 1`

### Emacs functionality

No idea

### Minimal init.lua

```lua


vim.g.mapleader = ' '

vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup({
    {
      'wbthomason/packer.nvim',
      { 'nvim-treesitter/nvim-treesitter' },
      { 'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  })
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })

  vim.cmd([[packadd nvim-treesitter]])
  vim.cmd([[runtime plugin/nvim-treesitter.lua]])
  vim.cmd([[TSUpdateSync org]])

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup({
    org_agenda_files = {
      './*'
    }
  }
  )

  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd([[edit!]])
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path })
  load_plugins()
  require('packer').sync()
  vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])
else
  load_plugins()
  load_config()
end


```

### OS / Distro

Linux

### Neovim version/commit

0.8.3

### Additional context

An example that the other way around works as expected is the following:

1. From the original file:
```orgmode
* Heading 1
** Subheading 1
** Subheading 2
* Heading 2
*** SubSubheading 1
```
2. If you refile the `Subheading 1` into `SubSubheading 1` the result file is
```orgmode
* Heading 1
** Subheading 2
* Heading 2    
*** SubSubheading 1
**** Subheading 1  
```

**Comment by lyz-code** [comment]
Is there anything I could do to help move forward on this issue without knowing anything of lua?

**Comment by kristijanhusak** [comment]
This should be fixed now. Please pull latest master and give it a test.
