### ISSUE TITLE
[orgmode] vim/shared.lua:0: The reverse lookup found an existing value for "" while processing key "5"

### ISSUE THREAD

**Issue by mcepl** [nvim-orgmode/orgmode#569]
### Describe the bug

When I run `org_mappings.todo_next_state` (`<Leader>cit`) I get the error message in the title of this issue.

Using neovim-0.9.0+git.1685321092.9dd48f783-6.1.x86_64 (build from https://github.com/neovim/neovim/commit/9dd48f7832f4656af4a2579368641268bb6399e7), the latest nvim-orgmode (https://github.com/nvim-orgmode/orgmode/commit/7d4a3ffe9f766db7eab4c98610078f62f83965df), and I also have enabled my own plugin (https://git.sr.ht/~mcepl/editorconfig-orgmode.nvim).

### Steps to reproduce

1. Open `.org` file,
2. move cursor on some TODO headline
3. press `<Leader>cit`

### Expected behavior

status of the line shifts one event ahead

### Emacs functionality

error message, no change in the status of the keyword.

### Minimal init.lua

```lua

-- Enter your minimal_init.lua here

```

### OS / Distro

openSUSE/Tumbleweed

### Neovim version/commit

9dd48f7832f4656af4a2579368641268bb6399e7

**Comment by jgollenz** [comment]
Can you please first check if the error persists if you use the `minimal_init.lua`? Thanks

**Comment by mcepl** [comment]
Yup, I can safely reproduce just with this diff:

```diff
tumbleweed-pkg~/.l/s/n/s/p/p/s/o/scripts (master *)$ git diff
diff --git a/scripts/minimal_init.lua b/scripts/minimal_init.lua
index 0a54069..b963165 100644
--- a/scripts/minimal_init.lua
+++ b/scripts/minimal_init.lua
@@ -10,6 +10,7 @@ local function load_plugins()
       'wbthomason/packer.nvim',
       { 'nvim-treesitter/nvim-treesitter' },
       { 'kristijanhusak/orgmode.nvim', branch = 'master' },
+      {'https://git.sr.ht/~mcepl/editorconfig-orgmode.nvim'},
     },
     config = {
       package_root = package_root,
tumbleweed-pkg~/.l/s/n/s/p/p/s/o/scripts (master *)$ 
```

**Comment by kristijanhusak** [comment]
If it doesn't happen without that diff then it's an issue in that plugin.

**Comment by mcepl** [comment]
Do you see anything wrong with this piece of code (that’s all really from the plugin)?

```lua
    if #keywords > 1 then
        local Config = require("orgmode.config")
        Config:extend({
            org_todo_keywords = keywords,
        })
        require("orgmode.colors.todo_highlighter").add_todo_keyword_highlights()
    end
```

I cannot find any real documentation to this function (it all comes from https://github.com/nvim-orgmode/orgmode/issues/486).

**Comment by kristijanhusak** [comment]
From the error I would assume that some of the keywords are empty strings. Can you debug and check?

**Comment by mcepl** [comment]
https://git.sr.ht/~mcepl/editorconfig-orgmode.nvim/commit/9506c73442aaa7d94b6166a98ab2b9c240096314

Thank you for your patience.

BTW, could this plugin be added to the list of orgMode plugins?
