### ISSUE TITLE
Cyclic DONE tasks are still displayed in agenda

### ISSUE THREAD

**Issue by WhiteBlackGoose** [nvim-orgmode/orgmode#574]
### Describe the bug

Even though a task is done many months ago, because it used to be a weekly task, it would still be shown on agenda.

### Steps to reproduce

```
* DONE Quack
  SCHEDULED: <2023-04-12 ++1w>
```

### Expected behavior

Should not be displayed. It's over, no need to show it anymore

### Minimal init.lua

irrelevant

### OS / Distro

irrelevant

### Neovim version/commit

NVIM v0.10.0-dev-2028d1e Build type: Release LuaJIT 2.1.0-beta3

**Comment by jgollenz** [comment]
Looking at the [docs](https://orgmode.org/manual/Repeated-tasks.html) I'm not sure what the actual behavior is supposed to be. The examples use `DEADLINE` while you use `SCHEDULED`. We have to look at what emacs does and replicate that.

**Comment by WhiteBlackGoose** [comment]
I have a reliable source that it's indeed a bug in nvim-orgmode :smile: 

![image](https://github.com/nvim-orgmode/orgmode/assets/31178401/54704549-c2da-4a6b-b9ee-0caa5a2a44a7)

**Comment by jgollenz** [comment]
When is it displayed? Every week? According to the docs it should be displayed the amount of displacement (in your case it's a week) plus the days that have passed. It should show up once, if I'm not mistaken.

**Comment by WhiteBlackGoose** [comment]
Yes, every week. I'm done with this task long ago, it's marked as DONE, but it's displayed as DONE every week. Since I used it for schedule in the university, half of my agenda is now filled with DONE tasks

**Comment by WhiteBlackGoose** [comment]
Oh well I even found test
```
should not show scheduled DONE item if disabled in config
```
in `agenda_item_spec.lua:236`
