### ISSUE TITLE
 Performance Issue: Slow File Loading with Multiple Hyperlinks

### ISSUE THREAD

**Issue by ESSO0428** [nvim-orgmode/orgmode#576]
### Describe the bug

Dear orgmode.nvim development team,

I am a user of lunavim with the integrated orgmode.nvim plugin, and I have encountered a performance issue that I would appreciate your assistance and advice on.

When using multiple hyperlinks in my org files, I have noticed that file loading becomes extremely slow, and my CPU usage is also high. I have tested the performance with a small number of hyperlinks (approximately 10 or less), and it functions normally. However, once the number of hyperlinks exceeds a certain threshold, the performance issue arises.

Here is an example of one of the hyperlinks (:e ~/test.org):
[[https://anvilproject.org/guides/content/creating-links][link]]
If I have the same example hyperlink repeated more than 14 times in the file, the CPU usage spikes and the file loading becomes significantly slower.

I have also experimented with the mkdnflow.nvim plugin, which renders markdown hyperlinks, and I have noticed that it does not encounter any performance issues even when the same link is repeated for 100 lines.

Additionally, I have tested the minimal configuration provided by your team (minimal_init.lua) by running nvim -u minimal_init.lua, and I encountered the same performance issue.

I would appreciate any suggestions or solutions you can provide to help resolve this performance issue. Thank you for your assistance!

### Steps to reproduce

Open org file by executing the command :e ~/test.org in your editor.
Create a hyperlink with the following format:
[[https://anvilproject.org/guides/content/creating-links][link]].
Copy and paste this hyperlink more than 10 times in your org file.

### Expected behavior

When there are multiple hyperlinks, the reading of an Org file should be smooth, similar to how the mkdnflow.nvim plugin reads Markdown files.

### Minimal init.lua

```lua

-- Enter your minimal_init.lua here
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup({
    {
      'wbthomason/packer.nvim',
      { 'nvim-treesitter/nvim-treesitter' },
      { 'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  })
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })

  vim.cmd([[packadd nvim-treesitter]])
  vim.cmd([[runtime plugin/nvim-treesitter.lua]])
  vim.cmd([[TSUpdateSync org]])

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup()

  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd([[edit!]])
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path })
  load_plugins()
  require('packer').sync()
  vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])
else
  load_plugins()
  load_config()
end
```

### OS / Distro

Arch Linux on WSL

### Neovim version/commit

0.9.0

**Comment by jgollenz** [comment]
Hi @ESSO0428, thanks for the report. Did you update nvim-orgmode lately? This might	be due to the parsing issue reported in [550](https://github.com/nvim-orgmode/orgmode/issues/550) and [570](https://github.com/nvim-orgmode/orgmode/issues/570). There were recent changes to address this. Please update nvim-orgmode and check if the issue persists :+1:

**Comment by ESSO0428** [comment]
Thank you very much for your response. I have followed the instructions and updated to the latest version. However, I am still encountering performance issues. I have tested it on Arch Linux on WSL, and I'm experiencing subpar performance both in Lunavim and with nvim -u minimal_init.lua.

I have also tested on another Linux distribution, Ubuntu, within my WSL environment using the same minimal_init.lua configuration, and I still observe slow performance. Furthermore, I tested the performance using Lunavim, where I installed the orgmode plugin using lazy loading. Interestingly, when using Lunavim (an nvim pre-configured version that combines nvim with their configuration files and environment variables and utilizes lazy loading for managing packages), the performance improved significantly when loading the example org file. Hyperlinks with more than 60 lines worked smoothly, and I was able to navigate in normal mode using hjkl without any issues. However, there is still some latency when entering insert mode for editing.

PS: The performance has improved on the Ubuntu on WSL with Lunavim installed on my current PC. However, it is still important to explore other possible solutions to address the performance issues. Thank you once again for your response, and I appreciate your understanding.

**Comment by kristijanhusak** [comment]
This issue should be resolved on latest master. If the problem persists, please open up a separate issue. Thanks.

**Comment by ESSO0428** [comment]
> This issue should be resolved on latest master. If the problem persists, please open up a separate issue. Thanks.

Thank you for your response and for the efforts to address this issue. I've updated to the latest master as advised and can confirm that the performance issues when reading org files with many hyperlinks have indeed been resolved. Your support and the team's dedication to improving the experience for all users are truly appreciated.

Thanks!!!
