### ISSUE TITLE
Hangs when opening neovim

### ISSUE THREAD

**Issue by joshpetit** [nvim-orgmode/orgmode#581]
### Describe the bug

Org causes my neovim instance to need 4 seconds to load. Which I know relatively fast, but still is inconvenient when I'm opening to do non-org related tasks or reopening neovim a lot.

### Steps to reproduce

1. Have a huge org direcotry (like 10 files with thousands of lines)
2. Open up neovim anywhere

### Expected behavior

Possibly parse all the org files on a separate, non blocking thread? Faster parsing speeds? Not sure.

### Minimal init.lua

Only settings I add:
```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"

local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{ "nvim-treesitter/nvim-treesitter" },
			{ "kristijanhusak/orgmode.nvim", branch = "master" },
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
		},
	})
end

_G.load_config = function()
	require("orgmode").setup_ts_grammar()
	require("nvim-treesitter.configs").setup({
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = { "org" },
		},
	})

	vim.cmd([[packadd nvim-treesitter]])
	vim.cmd([[runtime plugin/nvim-treesitter.lua]])
	vim.cmd([[TSUpdateSync org]])

	-- Close packer after install
	if vim.bo.filetype == "packer" then
		vim.api.nvim_win_close(0, true)
	end

	require("orgmode").setup_ts_grammar()
	require("orgmode").setup({
		org_agenda_files = { "~/sync/org/**/*" },
		org_default_notes_file = "~/sync/org/refile.org",
		org_deadline_warning_days = 5,
		org_agenda_start_on_weekday = 7,
		org_highlight_latex_and_related = "native",
		highlight = {
			additional_vim_regex_highlighting = { "org" },
		},
		mappings = {
			org = {
				org_next_visible_heading = "g}",
				org_previous_visible_heading = "g{",
			},
		},
		notifications = { enabled = true },
		org_agenda_templates = {
			m = {
				description = "Working on Ms5",
				template = "** Working on Ms5 %<%Y-%m-%d>\nSCHEDULED: %t\n:LOGBOOK:\nCLOCK: %U\n:END:",
				target = "~/sync/org/programming/ms5.org",
				headline = "MS5 Timesheet",
			},
			i = {
				description = "Thoughts",
				template = "** %?",
				target = "~/sync/org/life.org",
				headline = "Thoughts",
			},
			n = {
				description = "Random note",
				template = "* %?",
			},
			t = {
				description = "MS5 Task",
				target = "~/sync/org/programming/ms5.org",
				headline = "MS5 Refile",
				template = "** %?\nSCHEDULED: %t",
			},
		},
	})

	-- Reload current file if it's org file to reload tree-sitter
	if vim.bo.filetype == "org" then
		vim.cmd([[edit!]])
	end
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
	vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])
else
	load_plugins()
	load_config()
end

```

### OS / Distro

Arch

### Neovim version/commit

0.10

**Comment by kristijanhusak** [comment]
4 seconds to open Neovim? Orgmode should not affect your startup time if configured correctly. Provide minimum init please.

> Have a huge org direcotry (like 10 files with thousands of lines)

Did you try this in Emacs? Huge files need time to be fully parsed. First time is slower, but every other time in the same session should be faster.

**Comment by joshpetit** [comment]
Man I really thought I was exempt from the template lol. After running the minimal init.lua It dropped from like 4 seconds to like half a second. I suppose other things are loading while org loads the file? I updated the issue with the minimal init

**Comment by kristijanhusak** [comment]
Org files should not be loaded until you do some of these things:
* Open up an org file
* Open up agenda prompt
* Open up capture prompt

Are you using some orgmode plugin, or maybe some of the API?

**Comment by joshpetit** [comment]
Yea, I had a few custom functions to parse files but after commenting them out the delay still happens. You can see the hang in this video since telescope takes 4 seconds to display any files (when disabling orgmode though I don't have the delay)


https://github.com/nvim-orgmode/orgmode/assets/59021155/6e62f1d0-3e75-463d-b64a-2c88336da245

**Comment by kristijanhusak** [comment]
Please give it a test with latest master branch. If the problem persists, please open up a separate issue and link this one there. Thanks.
