### ISSUE TITLE
Compatibility with nvim-ufo

### ISSUE THREAD

**Issue by Zhou-Yicheng** [nvim-orgmode/orgmode#599]
### Describe the bug

Fold automatically every time type `ESC` in insert mode

### Steps to reproduce

0. Install Neovim
1. Install nvim-orgmode with nvim-ufo
2. Setup orgmode treesitter grammar
3. Setup UFO with folding provider of treesitter indent
4. Run `:TSUpdate org`
5. Open an org file
6. Enter insert mode then type `ESC`

### Expected behavior

Back to normal mode without folding

### Minimal init.lua

```lua
    require('orgmode').setup()
    require('orgmode').setup_ts_grammar()
```
```lua
    require('ufo').setup({
      provider_selector = function(bufnr, filetype, buftype)
        return { 'treesitter', 'indent' }
      end,
    })
```

### OS / Distro

Gentoo 2.14

### Neovim version/commit

v0.9.1

**Comment by UTFeight** [comment]
It's reproducible yes.
But strangely <C-c> achieves the same thing while keeping the folds there!

**Comment by treatybreaker** [comment]
This is *really* an issue with UFO in some aspects. A good work around is to disable UFO in org buffers. I ran into this myself just now while migrating to orgmode.

Here's how I disable UFO in certain buffers:

```lua
local ft_options = {
    norg = "", -- Neorg had the same issue
    org = "" -- We "disable" ufo in org files by giving back an empty provider to UFO
}

require('ufo').setup({
    provider_selector = function(_, filetype, _)
        return ft_options[filetype] or { "treesitter", "indent" }
    end,
})
```

I still get folding in `org` files without the weird "auto-folding" going on from UFO. Recommend you give it a shot.

**Comment by UTFeight** [comment]
@treatybreaker This didn't solve the issue on #614 Thanks for sharing anyway!
but using:

```lua
vim.cmd [[setlocal nofoldenable]] -- No folds initially
```

disables folds. You can use it with an autocmd.

**Comment by treatybreaker** [comment]
> @treatybreaker This didn't solve the issue on #614 Thanks for sharing anyway! but using:
> 
> ```lua
> vim.cmd [[setlocal nofoldenable]] -- No folds initially
> ```
> 
> disables folds. You can use it with an autocmd.

It still seems as though UFO's folds are much superior to what we get out the gate with orgmode here.

`nofoldenable` still leads to some folds being incorrectly calculated like in #614, UFO works around that but introduces the `esc/undo` bug here.

Somewhat frustrating, I think I'll set aside some time later to find the root cause.

**Comment by treatybreaker** [comment]
Hey @Zhou-Yicheng, @UTFeight, @m3xan1k,

With the merging of #615 UFO should play nice with Orgmode if you set `org_startup_folded` to `inherit` or `showeverything`.

```lua
require("orgmode").setup({
    -- ...
    org_startup_folded = "inherit"
})
```

Give it a shot, that fixes UFO issues for me.

**Comment by UTFeight** [comment]
The issue solved!
Thanks for the PR!
