### ISSUE TITLE
code block syntax highlighting not working (Tree-sitter highlight injections through #BEGIN_SRC filetype blocks)

### ISSUE THREAD

**Issue by mcsimw** [nvim-orgmode/orgmode#605]
Everything seems to work for me except the code block syntax highlighting and I am really not sure why. 

I pasted it just like that in my config and it's not working. 

-- init.lua

-- Load custom treesitter grammar for org filetype
require('orgmode').setup_ts_grammar()

-- Treesitter configuration
require('nvim-treesitter.configs').setup {
  -- If TS highlights are not enabled at all, or disabled via `disable` prop,
  -- highlighting will fallback to default Vim syntax highlighting
  highlight = {
    enable = true,
    -- Required for spellcheck, some LaTex highlights and
    -- code block highlights that do not have ts grammar
    additional_vim_regex_highlighting = {'org'},
  },
  ensure_installed = {'org'}, -- Or run :TSUpdate org
}

require('orgmode').setup({
  org_agenda_files = {'~/Dropbox/org/*', '~/my-orgs/**/*'},
  org_default_notes_file = '~/Dropbox/org/refile.org',
})

**Comment by szaffarano** [comment]
Do you have the following treesitter config?

```lua
    -- Setup treesitter
    require('nvim-treesitter.configs').setup({
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = { 'org' },
      },
      ensure_installed = { 'org' },
    })
```
