### ISSUE TITLE
Extend date picker (Calendar) with time

### ISSUE THREAD

**Issue by seflue** [nvim-orgmode/orgmode#607]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

I'm not sure, if Emacs really has a time picker for scheduling dates. But it is [mentioned](https://orgmode.org/manual/Deadlines-and-Scheduling.html), that times are allowed to be used for scheduling and deadline entries.

### Feature value

I missed a convenient picker for times, so I sat down and [implemented it](https://github.com/seflue/nvim-orgmode/commit/6b83392eefcebb569216515cf2d8c755b3da35a5).

![image](https://github.com/nvim-orgmode/orgmode/assets/952313/c4e40260-8eca-43da-9a24-56635f6da920)

I will add an PR as soon as #588 is merged.

**Comment by azycat** [comment]
are you still working on this? i was just thinking today about how convenient this feature would be... thanks

**Comment by seflue** [comment]
I have it on my daily used branch, but not driven it forward. There are still some usability quirks I need to fix. But if you are curious, feel free to try it out on my fork, I rebase it onto upstream master regularly. And I would be happy for some feedback.

**Comment by seflue** [comment]
@azycat I filed a PR, let's see if @kristijanhusak finds it also useful. 🙏

**Comment by seflue** [comment]
Implemented, closed.
