### ISSUE TITLE
Installation fails with the basic lazy.nvim install script

### ISSUE THREAD

**Issue by ChausseBenjamin** [nvim-orgmode/orgmode#612]
### Describe the bug

I get an error when launching nvim with the lazy.nvim snippet from the readme.md.
Here is what I get:

```
Failed to run `config` for orgmode                                                                                                                   .../current/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 2992 for language lua
# stacktrace:
  - ~/scoop/apps/neovim/current/share/nvim/runtime/lua/vim/treesitter/query.lua:259 _in_ **get**
  - ~/scoop/apps/neovim/current/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:110 _in_ **new**
  - ~/scoop/apps/neovim/current/share/nvim/runtime/lua/vim/treesitter.lua:61 _in_ **_create_parser**
  - ~/scoop/apps/neovim/current/share/nvim/runtime/lua/vim/treesitter.lua:131 _in_ **get_parser**
  - ~/scoop/apps/neovim/current/share/nvim/runtime/lua/vim/treesitter.lua:459 _in_ **start**
  - plugins.lua:54 _in_ **config**
```

### Steps to reproduce

Install orgmode with `lazy.nvim`.

### Expected behavior

Flawless installation

### Minimal init.lua

```lua
-- Bootstrap installation of lazy.nvim on a new system:
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Installed plugins:
require("lazy").setup({

  -- Org Mode {{{
  {
    'nvim-orgmode/orgmode',
    dependencies = {
      { 'nvim-treesitter/nvim-treesitter', lazy = true },
    },
    event = 'VeryLazy',
    config = function()
      -- Load treesitter grammar for org
      require('orgmode').setup_ts_grammar()
      -- Setup treesitter
      require('nvim-treesitter.configs').setup({
        highlight = {
          enable = true,
          additional_vim_regex_highlighting = { 'org' },
        },
        ensure_installed = { 'org' },
      })
      -- Setup orgmode
      require('orgmode').setup({
        org_agenda_files = '~/orgfiles/**/*',
        org_default_notes_file = '~/orgfiles/refile.org',
      })
    end,
  }, -- }}}

})
```

### OS / Distro

Windows 11

### Neovim version/commit

0.9.1

**Comment by kristijanhusak** [comment]
Do you have any issues with other package managers?

Can you post the full configuration with lazy? Maybe I need to add more context to the installation part. It assumes that you do something like this:

```lua
require('lazy').setup({
{
  'nvim-orgmode/orgmode',
  dependencies = {
    { 'nvim-treesitter/nvim-treesitter', lazy = true },
  },
  event = 'VeryLazy',
  config = function()
    -- Load treesitter grammar for org
    require('orgmode').setup_ts_grammar()

    -- Setup treesitter
    require('nvim-treesitter.configs').setup({
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = { 'org' },
      },
      ensure_installed = { 'org' },
    })

    -- Setup orgmode
    require('orgmode').setup({
      org_agenda_files = '~/orgfiles/**/*',
      org_default_notes_file = '~/orgfiles/refile.org',
    })
  end,
}
})

**Comment by juridiener** [comment]
> I just noticed this setting:
> 
> ```lua
> highlight = {
>   enable = false, -- <<< This is now set to false
>   additional_vim_regex_highlighting = { 'org' },
> },
> ```
> 
> When configured that way, all errors go away and orgmode starts working. I'm gonna take a closer look at my treesitter configuration to see if it's the culprit.

Hi did you figured it out? I have same problems that if I try to install nvim-orgmode. And try to open the agenda view nothin happens.

**Comment by kristijanhusak** [comment]
Minimal init is now updated to use `lazy.nvim` since packer is no longer maintained.
You can see it here https://github.com/nvim-orgmode/orgmode/blob/master/scripts/minimal_init.lua.

To use it, just download it and do `nvim -u minimal_init.lua`

**Comment by juridiener** [comment]
> nvim -u minimal_init.lua

I donwloaded and run the command. But nothing happens, no plugins were installed??

**Comment by kristijanhusak** [comment]
@juridiener which system are you running? It should install everything in the background. Once it's done, try doing `\oa` to open the agenda.

**Comment by juridiener** [comment]
> @juridiener which system are you running? It should install everything in the background. Once it's done, try doing `\oa` to open the agenda.

macOs Ventura 13.5.2

**Comment by Termanater13** [comment]
I have a similar issue, maybe the same, my error is the same, but the line **Start** says line 460 not line 459. I'm using Neovim version v0.9.5 on Windows 11. trying their change of true to false also makes the error go away.

**Comment by kristijanhusak** [comment]
@Termanater13 can you try on latest master? Windows should be supported with minimal init now.

**Comment by ChausseBenjamin** [comment]
Lazy Installation seems to be working flawlessly for me since June. Should this be kept open for others or is it OK to close?
There have been no new developments for over 6 months anyways...

**Comment by kristijanhusak** [comment]
Closing, thanks everyone.
