### ISSUE TITLE
treesitterattempt to index local `node` (a nil value)

### ISSUE THREAD

**Issue by cip123** [nvim-orgmode/orgmode#619]
### Describe the bug

I just installed a plugin and wrote the first TODO. Whenever I tried to toggle the TODO state using `Ctrl + Space`.

`.../share/nvim/lazy/orgmode/lua/orgmode/utils/treesitter.lua:98: attempt to index local 'node' ( a nil value)`

### Steps to reproduce

Toggle a TODO item using `Ctrl + Space`

### Expected behavior

The TODO to toggle.

### Minimal init.lua

```lua

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)


require("lazy").setup(
{
  'nvim-orgmode/orgmode',
  dependencies = {
    { 'nvim-treesitter/nvim-treesitter', lazy = true },
  },
  event = 'VeryLazy',
  config = function()
    -- Load treesitter grammar for org
    require('orgmode').setup_ts_grammar()

    -- Setup treesitter
    require('nvim-treesitter.configs').setup({
	    highlight = {
		    enable = true,
		    additional_vim_regex_highlighting = { 'org' },
	    },
	    ensure_installed = { 'org' },
    })

    -- Setup orgmode
    require('orgmode').setup({
	    org_agenda_files = '~/orgfiles/**/*',
	    org_default_notes_file = '~/orgfiles/refile.org',
    })
  end,
}
)
```

### Screenshots and recordings

![image](https://github.com/nvim-orgmode/orgmode/assets/1565500/a4047765-25d9-4604-af40-c03008ffc3f9)

### OS / Distro

Linux Mint 21.02

### Neovim version/commit

v0.9.2

**Comment by kristijanhusak** [comment]
Changing TODO state is done with `cit`. Ctrl + Space toggles the checkboxes, and it fails because there's no checkbox on the line. I'll leave it open since it should just ignore the command in that case.

**Comment by kristijanhusak** [comment]
This issue should be fixed with latest master.
