### ISSUE TITLE
org_archive_location doesn't work with full paths

### ISSUE THREAD

**Issue by nicolasdumitru** [nvim-orgmode/orgmode#628]
### Describe the bug

I tried to set the directory where files (or headings) get archived to a subdirectory called "archive" in my org files directory. It does not seem to work with absolut paths.

### Steps to reproduce

Try to archive a headline.

### Expected behavior

If HOME is the current user's home directory, the heading that you are trying to archive should get placed in ~/org/archive/<name_of_the_initial_file>.org_archive. Instead, it currently gets placed in ~/org/home/<your_user_name>/org/archive/<name_of_the_initial_file>.org_archive.

### Minimal init.lua

```lua

local org_directory = {}

org_directory.root = os.getenv("HOME") .. "/org/"
org_directory.archive = org_directory.root .. "archive/"

local function configuration()
	local org = require("orgmode")
	-- Load treesitter grammar for org
	org.setup_ts_grammar()

	-- Setup treesitter
	require("nvim-treesitter.configs").setup({
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = { "org" },
		},
		ensure_installed = { "org" },
	})

	-- Setup orgmode
	org.setup({
		org_agenda_files = org_directory.root .. "**/*",
		org_default_notes_file = org_directory.root .. "refile.org",
		org_capture_templates = {
			-- TODO: add useful templates (maybe for backlog) and remove this one
			r = {
				description = "Repo",
				template = "* [[%x][%(return string.match('%x', '([^/]+)$'))]]%?",
				target = org_directory.root .. "repos.org",
			}
		},
		org_todo_keywords = { "TODO", "WAITING", "|", "DONE", "DELEGATED" },
		org_todo_keyword_faces = {
			WAITING = ":weight bold",
			DELEGATED = ":slant italic :underline on",
		},
		org_archive_location = org_directory.archive .. "%s_archive",
	})
end

local nvim_root = '/tmp/nvim_orgmode'
local lazy_root = nvim_root .. '/lazy'
local lazypath = lazy_root .. '/lazy.nvim'

-- Install lazy.nvim if not already installed
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'nvim-orgmode/orgmode',
    dependencies = {
      { 'nvim-treesitter/nvim-treesitter', lazy = true },
    },
    event = 'VeryLazy',
    config = configuration,
  },
}, {
  root = lazy_root,
  lockfile = nvim_root .. '/lazy.json',
  install = {
    missing = false,
  },
})

require('lazy').sync({
  wait = true,
  show = false,
})

```

### OS / Distro

Arch Linux

### Neovim version/commit

0.9.4 (build type: release; LuaJIT 2.1.1699392533

**Comment by Avimitin** [comment]
Get same error here. nvim-orgmode doesn't parse the string as a path, instead it will create a full path under the current directory. 
![image](https://github.com/nvim-orgmode/orgmode/assets/30021675/f8610d8a-54fc-422e-bc4f-b3b05f2585f7)

**Comment by kristijanhusak** [comment]
This should be fixed now. Let me know if it's still broken.

**Comment by nicolasdumitru** [comment]
I'm sorry, but I won't test it, as I don't use this plugin anymore. I have started using it the original Org mode and Emacs (for and only for Org mode), despite the fact that I think Emacs itself is a steaming pile of hot garbage. The reason is threefold:

- I need something that is fully functional ASAP.
- There is a (real) ecosystem around Emacs Org mode (cool things like Org Roam)
- I don't see why Org mode should be specific to one text editor or another. I might as well just use the more supported and popular original. There are also some subtle differences that I'd like to not have to account for.

I wish you and your project all the best!

**Comment by kristijanhusak** [comment]
No worries, thanks for reporting the issue anyway.

**Comment by nicolasdumitru** [comment]
Happy to help!
