### ISSUE TITLE
Leader Hotkeys not Working for Nvim-Org-Mode

### ISSUE THREAD

**Issue by shawn-peery** [nvim-orgmode/orgmode#631]
### Describe the bug

#Issue
My problem stated plainly is that the following leader key keybinds for nvim-orgmode are not working:

Open agenda prompt: {Leader}oa
Open capture prompt: {Leader}oc

# Additional Context

I am running Windows 11 executing commands in a git-bash terminal. I just recently started working with NeoVim so as shown I have very recent versions for NeoVim and Lua:
NeoVim Version:v0.9.4
Lua 5.1.5

Additionally as shown in my init.lua file below I am referencing the dependencies directly from the github links. From my understanding due to that reason they should also be the latest release.

I am using Lazy plugin manager with the following init.lua:

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
    { 'nvim-reesitter/nvim-treesitter' },
    { "nvim-tokyonight", "https://github.com/folke/tokyonight.nvim"
    },
    {
      'nvim-orgmode/orgmode',
      'https://github.com/nvim-orgmode/orgmode',
      dependencies = {
        { 'nvim-treesitter/nvim-treesitter', lazy = true },
      },
      event = 'VeryLazy',
      config = function()
       -- Load treesitter grammar for org
       require('orgmode').setup_ts_grammar()

      -- Setup treesitter
      require('nvim-treesitter.configs').setup({
        highlight = {
	enable = true,
	additional_vim_regex_highlighting = { 'org' },
      },
      ensure_installed = { 'org' },
    })

    -- Setup orgmode
    require('orgmode').setup({
      org_agenda_files = '~/orgfiles/**/*',
      org_default_notes_file = '~/orgfiles/refile.org',
    })
  end,

}

}

require("lazy").setup(plugins, opts)

  vim.cmd([[colorscheme tokyonight]])

vim.g.mapleader = ","

vim.keymap.set('n', '<leader>w', '<cmd>write<cr>')
```

When I do :Lazy home I get this display:
https://i.stack.imgur.com/rrVqE.png

Note: Originally, when I did that before it would show treesitter as unloaded. That's when I had it set to 'lazy': true. But putting 'lazy': false (or I believe just removing the lazy property) made it be loaded. I apologize if I incorrectly setup my init.lua file.

Please let me know if there's any additional information you'd like to know regarding this issue.

In my init.lua I have the leader key set to ',' but I was also trying to use the '\\' key by default.

I tried restarting my computer to see if it needed to be reloaded to take affect.
I also setup a keybind in my init.lua that uses the leaderkey (I have as ','). This leader key works with no problem when I hit , + w it saves the file. However, no leader keybinds from the nvim-org-mode repo work.

I was expecting for pressing this key combination:
{Leader}oa

Would result in this screen:

https://i.stack.imgur.com/PkcyC.png

Any help would be greatly appreciated!

### Steps to reproduce

- Have NeoVIm 0.9.4
- Have Lua 5.1.5
- Have my init file specified in description of the but.
- When I open a file (whether it's .org or any other file) and hit "," + "o" + "a" it doesn't work.
- I see the "," show up and when I hit "o" it makes a new line and goes into insert mode ( the expected behavior if I didn't prefix it with the leader key.)

### Expected behavior

I expected the Agenda page to show:
![image](https://github.com/nvim-orgmode/orgmode/assets/26285018/f9bce2b4-321d-4055-813f-b1efc67dc3f1)

### Emacs functionality

I don't know if it exists in original org mode from emacs

### Minimal init.lua

```lua

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
    { 'nvim-reesitter/nvim-treesitter' },
    {
      'nvim-orgmode/orgmode',
      'https://github.com/nvim-orgmode/orgmode',
      dependencies = {
        { 'nvim-treesitter/nvim-treesitter', lazy = true },
      },
      event = 'VeryLazy',
      config = function()
       -- Load treesitter grammar for org
       require('orgmode').setup_ts_grammar()

      -- Setup treesitter
      require('nvim-treesitter.configs').setup({
        highlight = {
	enable = true,
	additional_vim_regex_highlighting = { 'org' },
      },
      ensure_installed = { 'org' },
    })

    -- Setup orgmode
    require('orgmode').setup({
      org_agenda_files = '~/orgfiles/**/*',
      org_default_notes_file = '~/orgfiles/refile.org',
    })
  end,

}

}

require("lazy").setup(plugins, opts)


vim.g.mapleader = ","

vim.keymap.set('n', '<leader>w', '<cmd>write<cr>')
```

### Screenshots and recordings

Please reference description

### OS / Distro

windows 11

### Neovim version/commit

0.9.4

**Comment by kristijanhusak** [comment]
This is most likely the configuration issue. Did you try with the minimal init provided in the repo https://github.com/nvim-orgmode/orgmode/blob/master/scripts/minimal_init.lua ?

**Comment by shawn-peery** [comment]
> This is most likely the configuration issue. Did you try with the minimal init provided in the repo https://github.com/nvim-orgmode/orgmode/blob/master/scripts/minimal_init.lua ?

Thank you very much for that reply!

I have added the minimal_lua  code. I hadn't seen that before so thanks for recommending it. However, after setting my init.lua to have that code I get the following error when I launch neovim:

```
Error detected while processing C:\Users\rocke\AppData\Local\nvim\init.lua:
Error executing vim.schedule lua callback: /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:58: module 'lazy.manage.checker' not found:
        no field package.preload['lazy.manage.checker']
cache_loader: module lazy.manage.checker not found
cache_loader_lib: module lazy.manage.checker not found
        no file '.\lazy\manage\checker.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\manage\checker.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\manage\checker\init.lua'
        no file 'C:\Program Files (x86)\Lua\5.1\lua\lazy\manage\checker.luac'
        no file '.\lazy\manage\checker.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy\manage\checker.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
        no file '.\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:58: in function </tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:55>
        [C]: in function 'wait'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/runner.lua:168: in function 'wait'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:65: in function 'run'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:204: in function 'clean'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:189: in function 'sync'
        C:\Users\rocke\AppData\Local\nvim\init.lua:50: in main chunk
E5113: Error while calling lua chunk: /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:208: module 'lazy.manage.lock' not found:
        no field package.preload['lazy.manage.lock']
cache_loader: module lazy.manage.lock not found
cache_loader_lib: module lazy.manage.lock not found
        no file '.\lazy\manage\lock.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\manage\lock.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\manage\lock\init.lua'
        no file 'C:\Program Files (x86)\Lua\5.1\lua\lazy\manage\lock.luac'
        no file '.\lazy\manage\lock.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy\manage\lock.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
        no file '.\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:208: in function 'cb'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/runner.lua:158: in function 'clean'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/manage/init.lua:189: in function 'sync'
        C:\Users\rocke\AppData\Local\nvim\init.lua:50: in main chunk
Press ENTER or type command to continue
```

When I hit enter, I get this:

```
Error detected while processing User Autocommands for "VeryLazy":
Error executing lua callback: /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/core/config.lua:264: module 'lazy.manage.reloader' not found:

        no field package.preload['lazy.manage.reloader']
cache_loader: module lazy.manage.reloader not found
cache_loader_lib: module lazy.manage.reloader not found
        no file '.\lazy\manage\reloader.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\manage\reloader.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\manage\reloader\init.lua'
        no file 'C:\Program Files (x86)\Lua\5.1\lua\lazy\manage\reloader.luac'
        no file '.\lazy\manage\reloader.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy\manage\reloader.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
        no file '.\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/core/config.lua:264: in function </tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/core/config.lua:261>
        [C]: in function 'nvim_exec_autocmds'
        /tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/core/util.lua:152: in function </tmp/nvim_orgmode/lazy/lazy.nvim/lua/lazy/core/util.lua:147>
```

When I press enter again I get this:

```
Error detected while processing User Autocommands for "VeryLazy":
Plugin orgmode is not installed
Press ENTER or type command to continue
```

And then once I press enter, it brings up the file I wanted to open.

Have you seen these kinds of errors before? I would think I haven't installed something yet but since I use Lazy in the init.lua the minimal init.lua should take care of it.

**Comment by kristijanhusak** [comment]
Minimal lua needs to be used as a separate configuration, not to be pasted into your `init.vim`.

```
nvim -u minimal_init.lua
```

Try that and let me know.

**Comment by shawn-peery** [comment]
> Minimal lua needs to be used as a separate configuration, not to be pasted into your `init.vim`.
> 
> ```
> nvim -u minimal_init.lua
> ```
> 
> Try that and let me know.

Thank you very much!

Should I run this command in the directory where my init.lua is? And should I remove my init.lua before running this command or leave it there? Thanks for the clarification!

**Comment by shawn-peery** [comment]
I made a minimal_init.lua file with the contents of the link you game me and tried to do nvim -u minimal_init.lua while in the same directory as the file I made but it appears it game me the same error.

**Comment by kristijanhusak** [comment]
I see that you are using windows. I'm not 100% sure if minimal init works with Windows. Can you paste the error you got from the last command? It should not be the same.

**Comment by shawn-peery** [comment]
It basically prints out this:

C:\Users\rocke\AppData\Local\Temp\nvim.0\zCQ1L9\1

The zCQ1L9 folder exists but there's no '1' folder or file in there.

**Comment by kristijanhusak** [comment]
Ok, update the first line in `minimal_init.lua` to this:

```
vim.opt.shellslash = true
local nvim_root = 'C:/Users/rocke/AppData/Local/Temp/nvim_orgmode'
```

and give it another try.

**Comment by shawn-peery** [comment]
Thanks!

I have this on my minimal_init.lua:

vim.opt.shellslash = true
local nvim_root = '/tmp/nvim_orgmode'
local lazy_root = nvim_root .. '/lazy'
local lazypath = lazy_root .. '/lazy.nvim'

However, when running nvim -u minimal_init.lua it seems to be giving me the same error unfortunately :/

I appreciate your help :D

**Comment by kristijanhusak** [comment]
You need to replace the 2nd line with what I suggested. First 4 lines should be this:

```
vim.opt.shellslash = true
local nvim_root = 'C:/Users/rocke/AppData/Local/Temp/nvim_orgmode'
local lazy_root = nvim_root .. '/lazy'
local lazypath = lazy_root .. '/lazy.nvim'
```

**Comment by shawn-peery** [comment]
> You need to replace the 2nd line with what I suggested. First 4 lines should be this:
> 
> ```
> vim.opt.shellslash = true
> local nvim_root = 'C:/Users/rocke/AppData/Local/Temp/nvim_orgmode'
> local lazy_root = nvim_root .. '/lazy'
> local lazypath = lazy_root .. '/lazy.nvim'
> ```

Ah thank you. I apologize for missing that. I do the command nvim -u minimal_init.lua and it gave me a message of initalizing treesitter. And then after it loaded I tried opening a .txt file and doing {leader}oa and it gave me this erro rmessage:
```
E5108: Error executing lua Failed to load parser for language 'org': uv_dlopen: The specified procedure could not be found.

stack traceback:
        [C]: in function '_ts_add_language'
        ...win64/share/nvim/runtime/lua/vim/treesitter/language.lua:98: in function 'add'
        ...im-win64/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'get'
        ...e/lazy/orgmode/lua/orgmode/colors/markup_highlighter.lua:210: in function 'load_deps'
        ...e/lazy/orgmode/lua/orgmode/colors/markup_highlighter.lua:509: in function 'setup'
        ...e/lazy/orgmode/lua/orgmode/colors/custom_highlighter.lua:21: in function 'setup'
        ...ocal/Temp/nvim_orgmode/lazy/orgmode/lua/orgmode/init.lua:27: in function 'init'
        ...ocal/Temp/nvim_orgmode/lazy/orgmode/lua/orgmode/init.lua:154: in function 'action'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

And I'm expecting it to provide me with the agneda view.

I'm going ot head to work now but I appreciate your help so far!

**Comment by shawn-peery** [comment]
Okay after researching that error I'm getting I'm starting to think I missed an install step for treesitter or something else.

I'm going to go through each repo again and make sure I follow all of the install steps (specifically Windows install steps). 

However, if I'm not able to get it working I might switch to use a WSL2 Ubuntu thing and see how that goes for me.

Anyways, thank you very much for the help @kristijanhusak

**Comment by treatybreaker** [comment]
Hey @shawn-peery, sorry about being late on this. If it helps at all, I recommend you take a look at your C compiler. On Windows I'm able to use Orgmode as intended via [LLVM](https://github.com/llvm/llvm-project/releases). The latest compiler they provide for Windows (64 bit) can be found [here](https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.5/LLVM-17.0.5-win64.exe). A good Minimal init to use for testing would actually be the minimal init Orgmode has in its `tests` directory. Take a look [here](https://github.com/nvim-orgmode/orgmode/blob/master/tests/minimal_init.lua) for that file.

After installing `LLVM` and copying down that minimal init, I'm able to use agenda etc. in Orgmode just fine. After you get `LLVM` installed, you should be able to check if it works (assuming you have git installed as well) by running in *Powershell*: `git clone https://github.com/nvim-orgmode/orgmode Orgmode && nvim -nu Orgmode/tests/minimal_init.lua`. After that just hit `,oa` to open the agenda. In the scenario in which this doesn't work, check if you have another C compiler besides `LLVM` installed, that's probably causing the issue.

You can read more about Windows Treesitter support with nvim-treesitter [here](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support).

Hope that helps, best of luck 🙂.
