### ISSUE TITLE
Toggle timestamp with a keybinding between active and inactive (org-toggle-timestamp-type)

### ISSUE THREAD

**Issue by seflue** [nvim-orgmode/orgmode#652]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

See:
- https://doc.endlessparentheses.com/Fun/org-toggle-timestamp-type.html
- https://emacs.stackexchange.com/questions/38062/configure-key-to-toggle-between-active-and-inactive-timestamps/38064#38064

### Feature value

Personally I am often in the situation, where I use timestamps to make sections visible in the agenda and then want to make them invisible again (but keep the timestamp for tracability). I don't want to schedule the items for this purpose.

### Additional context

I implemented the feature in PR #651

**Comment by kristijanhusak** [comment]
Closing since this was implemented.
