### ISSUE TITLE
Refresh agenda each time an agenda file has changed

### ISSUE THREAD

**Issue by lyz-code** [nvim-orgmode/orgmode#656]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

I'm used to have an open window with the agenda and do changes on the other window. With the current refresh rate of the agenda I'm running into some UI issues:

1. Saving an agenda file:
  - If I press enter on an agenda item it gets open in the other window
  - Then if I do changes on that file and save the result is not refreshed in the agenda until you press `r`.
  - If you for example mark another element of the agenda as done or as archived, the actions are going to be done on the wrong item
3. Archiving an agenda item: If you have 3 items in the agenda that belong to the first file
  - If you archive the first element of the agenda it does not get refreshed until you press `r`
  - If you then act on the rest of the agenda elements you are going to again act on the wrong item.

Right now manually refreshing the agenda is kind of slow for me, so the need to do it after processing each element of the agenda is breaking my workflow.

### Additional context

Maybe we could use something like inotify to monitor the changes in the files.

Could be related to https://github.com/nvim-orgmode/orgmode/issues/596

**Comment by kristijanhusak** [comment]
> If you for example mark another element of the agenda as done or as archived, the actions are going to be done on the wrong item

This should not happen unless the change to the agenda item adds some content to it's subtree. For example if you have a headline with a deadline that repeats, each time you mark it as done it adds entry to the logbook, and shifts all headlines below. This caused wrong item to be updated in the agenda.

I solved that in https://github.com/nvim-orgmode/orgmode/commit/1425b3609500442afd331aae8feb2e7357bfbac1, so now agenda will automatically reload if there is a need for it. 

It will not reload if you archive a headline by adding ARCHIVE tag, or marking a nonrepeater task as done, but that should not cause any issues with the wrong item being updated. The idea is to be able to undo these changes easily in the agenda in case you made a mistake.

I also just pushed https://github.com/nvim-orgmode/orgmode/commit/66591caa247c2e59197e0a763de31460602b9be4 that should allow reloading agenda window remotely.

So to achieve what you want here you can add this to your configuration:

```lua
vim.api.nvim_create_autocmd('BufWritePost', {
  pattern = '*.org',
  callback = function()
    local bufnr = vim.fn.bufnr('orgagenda') or -1
    if bufnr > -1 then
      require('orgmode').agenda:redo()
    end
  end
})
```

This will reload agenda window if it's open each time you write any org file.

I think this should solve both this issue and https://github.com/nvim-orgmode/orgmode/issues/596. @Maltimore can yo check?

**Comment by lyz-code** [comment]
It works beautifully @kristijanhusak thank you so much as always, you don't know how happy you make me xD.

I'm fine closing the issue as is, but just one more question. The autocmd works only if I save the file where I archived the element. But there are cases where I just archive an element without saving so the agenda is not refreshed. To solve this I'm thinking of two solutions:

- That nvim-orgmode has this functionality
- To create a keybinding that saves the file when archiving an element. I suppose this solution is the cleanest for this (I guess) corner case. I have no idea though on how to do this. I'll search online the code to save a file from a lua function, but can you help me with the archiving lua code for the function? Only if it's trivial for you and don't have to search in the code (I can do that myself)

Thanks as always <3

**Comment by Maltimore** [comment]
Hi both of you,
I have tested the new code and can confirm that the issue described here is fixed, thanks @kristijanhusak!
There's still one case that doesn't work though, and that is simply if I have the agenda open in one `nvim` instance, and in another `nvim` instance I change a `.org` file. I do this quite frequently to be honest. I wonder, now that we have the `require('orgmode').agenda:redo()` function, could we have a loop that just refreshes the agenda every x minutes (with x configurable)?

**Comment by kristijanhusak** [comment]
@Maltimore you can probably do that with timers `:h vim.loop`, but i haven't tested.

**Comment by Maltimore** [comment]
Yes, that sounds quite straightforward, thanks!

**Comment by lyz-code** [comment]
@Maltimore If you finally go in the `vim.loop` direction could you please post here the solution? It's also the last feature I'm missing on this issue

**Comment by Maltimore** [comment]
Will do! :)

**Comment by kristijanhusak** [comment]
@lyz-code This should do the trick:

```lua
local timer = vim.loop.new_timer()
timer:start(
  0,
  10000,
  vim.schedule_wrap(function()
    local bufnr = vim.fn.bufnr('orgagenda') or -1
    if bufnr > -1 then
      require('orgmode').agenda:redo()
    end
  end)
)
```

This will reload the agenda if it's opened every 10 sec.
Note that you need to pull latest master. I found some bugs around reloading that I fixed in the meantime.

**Comment by lyz-code** [comment]
Damn @kristijanhusak each morning a new gift `(╥﹏╥)`. It works like a charm. 

For those of you that doubt where to put that snippet, I've added it to a `FileType` autocommand

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "org",
  group = vim.api.nvim_create_augroup("orgmode", { clear = true }),
  callback = function()
    -- Reload the agenda each second if its opened so that unsaved changes 
    -- in the files are shown
    local timer = vim.loop.new_timer()
    timer:start(
      0,
      10000,
      vim.schedule_wrap(function()
        local bufnr = vim.fn.bufnr("orgagenda") or -1
        if bufnr > -1 then
          require("orgmode").agenda:redo()
        end
      end)
    )
  end,
})

**Comment by lyz-code** [comment]
I've detected a little bug when using the timer. Each time the agenda reloads the cursor is moved to the top of the day. Imagine that we have this agenda:

```
Tuesday    05 March 2024
  inbox:           18:00......  Do X
  inbox:           19:30...... Do Y  <-- cursor is here
```

When the agenda is reloaded, the cursor is moved to the top of the day

```
Tuesday    05 March 2024  <-- cursor is moved here
  inbox:           18:00......  Do X
  inbox:           19:30...... Do Y  
```

10 seconds was too much for me, so I set the agenda reload each second. If I have 10 elements in a day agenda I don't have time to reach the bottom before I'm moved back up xD.

Would it be possible to remember the position where the cursor was so that it's stable after the agenda refresh?

I don't know if that is one of the fixes you made. I'm at `779a568`.

**Comment by lyz-code** [comment]
I feel that's fine because if no org file is opened then there is no need to reload the agenda as there will be no changes. I guess the other place to add the snippet is in the `setup` of the plugin.

Setting `true` to `redo` fixes it indeed ^^

**Comment by lyz-code** [comment]
Another solution to avoid using the timer is to use [the auto-save plugin](https://github.com/okuuva/auto-save.nvim?tab=readme-ov-file#-installation) I found it really elegant

**Comment by cyanpencil** [comment]
@lyz-code or anyone else needing this:

I found a bit of a better solution than just a timer, it is based on fs events:

```lua
vim.api.nvim_create_autocmd("FileType", {
  once = true,
  pattern = "org",
  callback = function()
    local watch_dir_path = vim.fn.expand("~/Sync")
    if vim.loop.fs_stat(watch_dir_path) then
      local fs_handle = vim.loop.new_fs_event()
      if fs_handle then
        print("Starting file watcher for: " .. watch_dir_path)
        fs_handle:start(watch_dir_path, {}, vim.schedule_wrap(function(err, filename, events)
          if err then print("Watcher error: " .. err) return end
          if events.change then
            local bufnr = vim.fn.bufnr "orgagenda" or -1
            if bufnr > -1 then
              vim.notify("File changed: " .. filename, vim.log.levels.WARN, { title = "File Watcher" })
              require("orgmode").agenda:redo(true)
            end
          end
        end))
      else print("Error: Could not create fs_event handle for " .. watch_dir_path)
      end
    else print("Warning: Watch directory does not exist, watcher not started: " .. watch_dir_path)
    end
  end,
})

```

This will reload the agenda whenever one of the files inside `watch_dir_path` is changed.
