### ISSUE TITLE
Being able to refile from the agenda view

### ISSUE THREAD

**Issue by lyz-code** [nvim-orgmode/orgmode#657]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

I do most of my work from the Agenda. Right now refiling items there is not possible. An error is shown saying `E21: Cannot make changes, 'modifiable' is off`

**Comment by kristijanhusak** [comment]
This is now added. Shortcut is the same as for org file https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_agenda_refile
