### ISSUE TITLE
Highlighting of folded text

### ISSUE THREAD

**Issue by ser3n1ty87** [nvim-orgmode/orgmode#661]
### Does this feature exist in Emacs orgmode core?

N/A

### Additional context

The current neovim nightly release v0.10.0 natively allows syntax highlighting of folded lines by setting the `foldtext` to an empty string. Could we somehow use this in the orgmode plugin? I am not 100% sure, however, if and how we can also get syntax highlighting if `foldtext` is set to a custom string (which orgmode is currently constructing).

**Comment by kristijanhusak** [comment]
I plan to add this, but until then you can add this to your configuration to make it work:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "org",
  callback = function(ev)
    vim.opt_local.foldtext = ''
  end
})
```
