### ISSUE TITLE
No updates on org_timestamp_up, no date selector on cid

### ISSUE THREAD

**Issue by chrimbo** [nvim-orgmode/orgmode#666]
### Describe the bug

The date does not update on C-a or C-x but just uses regular vim decrement/increment.

`cid` does not spawn the date selector either.

set ft gives org as filetype

### Steps to reproduce

1. Create new todo `<Leader>oct`
```
* Todo
 <2024-02-15 Do>
```
2. Move cursor to the day (15) in the date and press `<C-a>`
```
* Todo
 <2024-02-14 Do>
```
3. Press `14<C-a>`
```
* Todo
 <2024-020 Do>
```

### Expected behavior

1. Create new todo `<Leader>oct`
```
* Todo
 <2024-02-15 Do>
```
2. Move cursor to the day (15) in the date and press `<C-a>`
```
* Todo
 <2024-02-16 Fr>
```
3. Press `14<C-a>`
```
* Todo
 <2024-03-01 Fr>
```

`cid` spawns date selector window.

### Minimal init.lua

```lua

user = {}
user.confdir = "C:/Users/chrimbo/AppData/Local"

vim.cmd("source " .. user.confdir .. "/nvim/plug.vim")
vim.cmd("call plug#begin(\"" .. user.confdir .. "/nvim-data/plugged\")")
vim.cmd([[
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'nvim-orgmode/orgmode'
call plug#end()
]])
require('nvim-treesitter.configs').setup {
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = {'org'},
    disable = {"vim"},
  },
  ensure_installed = {'org'}
}

require('orgmode').setup_ts_grammar()
require('orgmode').setup({
org_agenda_files = {'C:/Nextcloud/Notes/**/*.org'},
org_default_notes_file = 'C:\\Nextcloud\\Notes\\refile.org',
org_capture_templates = {
    t = {
      description = "Todo",
      template = "* TODO %?\n %t",
      },
  }
})



```

### OS / Distro

Windows 10

### Neovim version/commit

0.9.4

### Additional context

What makes me curious is, if I type  `:today: ` I get the correct date, but can't edit it like mentioned. If I type `:today: ` for the second time, the date can be adjusted like expected. Even the `cid` is working on this date.

**Comment by kristijanhusak** [comment]
Should be fixed on latest master. Thanks for reporting.

**Comment by chrimbo** [comment]
Confirmed. After updating to master the problem is gone.
