### ISSUE TITLE
Add new capture items from template to top of file instead of bottom of file

### ISSUE THREAD

**Issue by GitMurf** [nvim-orgmode/orgmode#667]
### Does this feature exist in Emacs orgmode core?

N/A

### Additional context

Maybe there are already ways to accomplish this but I would like a way to add a capture template item to a target file at the top of the file instead of the bottom. Essentially to prepend instead of append. In a perfect world I could just specify the line number for the target file and it could add to bottom if you set line number as -1, add to the very top if line number set as 0, and any other number (e.g., 5) would be inserted below that line number... so for 5, that means it would essentially become line 6.

Let me know if you have any questions and/or if there is already a mechanism to accomplish this. Thanks!

**Comment by kristijanhusak** [comment]
This option is used in Emacs orgmode for that https://emacs.stackexchange.com/a/58346 . I'll look into implementing it at some point.

**Comment by GitMurf** [comment]
Here is even clearer information on emacs prepend feature. I guess they actually have a property for it called prepend! This isn't exactly what I need, but close because this required you put under a headline and not just the top of the note. But actually both these options would be important and valuable :) 

https://orgmode.org/manual/Template-elements.html

![image](https://github.com/nvim-orgmode/orgmode/assets/64155612/9446d829-84ba-428d-8a8d-4e342b444e3d)

**Comment by GitMurf** [comment]
@kristijanhusak if you want to point me in the right direction, I would be happy to take a look at a PR.

**Comment by GitMurf** [comment]
@kristijanhusak another thought I had, is there a way as is today to use the title of a file to put a template capture under instead of a headline? if so, that would also accomplish what I am looking to do.

**Comment by GitMurf** [comment]
@kristijanhusak amazing work! Thank you! This is perfect :)
