### ISSUE TITLE
Bold/italic emphasis syntax is not rendered in headlines

### ISSUE THREAD

**Issue by ourigen** [nvim-orgmode/orgmode#67]
### Describe the bug

Emphasis syntax such as `*bold*`, `/italic/`, `_underlined_`, etc. don't seem to render in headlines. I take notes in bullets so I make use of bolded/italicized words in headlines often. 

With the top level headline I can understand why bolding doesn't show since the entire headline is bolded. But italicizing doesn't work for all headlines and bolding doesn't work for subheadlines

### Steps to reproduce

This is what I used in my example text
```
* This is a test: *bold* /italic/ _underlined_
** This is a test: *bold* /italic/ _underlined_
*** This is a test: *bold* /italic/ _underlined_
This is a test: *bold* /italic/ _underlined_
```

### Expected behavior

For `*bold*`, `/italic/`, and `_underlined_`, I expected each word to render in the right face and be concealed (if the setting is set to true) even in headlines. The syntax properly shows and is concealed in normal text.

### Screenshots and recordings

![github](https://user-images.githubusercontent.com/79729735/130148945-01ca9d17-cd1f-44ad-b9e5-9dfc87dd3484.png)

### OS / Distro

Arch Linux

### Neovim version/commit

v0.6.0-dev

**Comment by kristijanhusak** [comment]
This is currently really hard to achieve without defining bunch of new syntax hl groups to handle each headline level for specific headline color, which I want to avoid for now. If i would enable it, this is what it would look like:
![screenshot](https://i.imgur.com/hlon5fW.png)
Once treesitter support is added, this should be an easily solvable issue.

**Comment by kristijanhusak** [comment]
@ourigen partial support for this is added on [tree-sitter](https://github.com/kristijanhusak/orgmode.nvim/tree/tree-sitter) branch. Here's how above content looks now:

![screenshot](https://i.imgur.com/66DIFUU.png)

Bold is still a bit problematic because headlines start with `*` and it messes up the highlights.

**Comment by ourigen** [comment]
Good to hear about the tree-sitter support! I'll help to test the branch when I have time

**Comment by kristijanhusak** [comment]
@ourigen this should be working more less ok at this moment. Bold issue should also be fixed. Let me know.

**Comment by ourigen** [comment]
@kristijanhusak Works well enough for me. Thanks for the great work!
