### ISSUE TITLE
Work Log entries, add under dynamic headline that has date

### ISSUE THREAD

**Issue by karampok** [nvim-orgmode/orgmode#672]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

Given that
```
(setq org-capture-templates
      '(    
        ("j" "Work Log Entry"
         entry (file+datetree "~/org/work-log.org")
         "* %?"
         :empty-lines 0)
        ))

```

### Additional context

Hi great work thanks!
this https://github.com/james-stoup/emacs-org-mode-tutorial?tab=readme-ov-file#configuration-1---work-log describes what I am trying to achive using the plugin? Is it possible?

**Comment by kristijanhusak** [comment]
This is now added. You can define it like this:
```lua
  org_capture_templates = {
    j = {
      description = 'Log entry',
      template = '* %?',
      target = '~/org/work-log.org',
      datetree = true,
      -- Or if you want to pick a date
      datetree = { time_prompt = true }
    },
  },

```

**Comment by karampok** [comment]
Many thanks it works very nice. Two small questions (no idea if org-mode supports that or not), would it possible the org file to be reversed? Like the newest day always on top and the oldest on the bottom? Also is is it possible to have week number? Thanks

**Comment by kristijanhusak** [comment]
Orgmode doesn't support that out of the box, there is package to do that (https://github.com/akirak/org-reverse-datetree). I'll see if we can extend the functionality here to support the reversed datetree and providing custom formatting for each level. I'll keep you posted.

**Comment by kristijanhusak** [comment]
@karampok Support for reversed datetree was added. Just pass reversed flag to the datetree opts:

```lua
  org_capture_templates = {
    j = {
      description = 'Log entry',
      template = '* %?',
      target = '~/org/work-log.org',
      datetree = { reversed = true }
    },
  },
```

I'll be adding support for custom date formats next.
