### ISSUE TITLE
Actions on text objects are not performed if the cursor is positioned before the text object

### ISSUE THREAD

**Issue by rwmpelstilzchen** [nvim-orgmode/orgmode#686]
### Describe the bug

Following [this](https://github.com/nvim-orgmode/orgmode/issues/332#issuecomment-1963066857) I did some testing, and found that if the cursor is positioned in the text object, actions are performed as expected, but if it is positioned *before* the text object, they are ignored. The default (Neo)Vim behaviour is that if a text-object action is called when the cursor is not within a text object of that type, it is performed on the *next* text object of the same type in the same line, if there is one.

### Steps to reproduce

Consider this line:

```
hello "world" ~blabla~
```

If the cursor is at the beginning of the line and `di"` is called, the word `world` will be deleted. Now, if `di~` is called, nothing happens (unless the cursor is within `~blabla~`, of course).

### Expected behavior

The expected behaviour would be for `~blabla~` to be deleted.

### Minimal init.lua

```lua

-- Enter your minimal_init.lua here

```

### OS / Distro

Arch Linux

### Neovim version/commit

0.9.4

**Comment by PriceHiller** [comment]
I'll take a look at this by this weekend and see about resolving it if nobody else does as a heads up.

**Comment by rwmpelstilzchen** [comment]
Thx ^_^

**Comment by rwmpelstilzchen** [comment]
Thank you for resolving this issue, @PriceHiller 🌼
