### ISSUE TITLE
Add a note to the entry (org-agenda-add-note)

### ISSUE THREAD

**Issue by ktsujister** [nvim-orgmode/orgmode#703]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

- https://orgmode.org/manual/Agenda-Commands.html#index-z
- https://orgmode.org/org.html#index-org_002dagenda_002dadd_002dnote

### Additional context

When I take notes using org-mode in emacs, I often use `(org-agenda-add-note)` `C-c C-z` to add notes to particular entry.
This is very helpful because it inserts timestamps when adding some notes in specified entry.

This was part of #455, but #455 was closed when #531 got merged, but left out `org-agenda-add-note` feature.

**Comment by kristijanhusak** [comment]
Support for this is now added. See https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_add_note and for agenda https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_agenda_add_note
