### ISSUE TITLE
Date/Time prompts in Capture Templates

### ISSUE THREAD

**Issue by rajatvd** [nvim-orgmode/orgmode#704]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

[Can we include variables like %^t to prompt the user for a date or time in a capture template](https://orgmode.org/manual/Template-expansion.html#:~:text=all%20agenda%20files.-,%E2%80%98%25%5Et%E2%80%99,-Like%20%E2%80%98%25t)

**Comment by kristijanhusak** [comment]
These are now added:

- `%^t`: Prompt for current date (Example: <2021-06-10 Thu>)
- `%^{Name}t`: Prompt for current date for given Name (visible in calendar title) (Example: <2021-06-10 Thu>)
- `%^T:` Prompt for current date and time (Example: <2021-06-10 Thu 12:30>)
- `%^{Name}T`: Prompt for current date and time for given Name (visible in calendar title) (Example: <2021-06-10 Thu 12:30>)
- `%^u`: Prompt for current date in inactive format (Example: [2021-06-10 Thu])
- `%^{Name}u`: Prompt for current date in inactive format for given Name (visible in calendar title) (Example: [2021-06-10 Thu])
- `%^U`: Prompt for current date and time in inactive format (Example: [2021-06-10 Thu 12:30])

https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_capture_templates
