### ISSUE TITLE
Loading org file causes expected string, got table error

### ISSUE THREAD

**Issue by schultzter** [nvim-orgmode/orgmode#705]
### Describe the bug

When I load an org file I get the error message:
![image](https://github.com/nvim-orgmode/orgmode/assets/30871/4602b72f-e3b1-42c1-9086-c91636a7ebed)

Using a simple org file:
![image](https://github.com/nvim-orgmode/orgmode/assets/30871/c9aa239d-5f34-45c7-aa23-53b496b94112)

### Steps to reproduce

Open the following org file:
``` org
* This is the first header
  
  This is a paragraph in the first section

** TODO This needs to get done :tag1:tag2:
   SCHEDULED: <2023-11-04 Sat 16:00>
*** HEADING
```

### Expected behavior

No errors! 

### Minimal init.lua

```lua
require("nvim-treesitter.install").command_extra_args = {
  curl = { "-k" },
}
require('nvim-treesitter.configs').setup({
  highlight = {
    enable = true; 
    disable = {'org'}, 
    additional_vim_regex_highlighting = {'org'},
  }, 
  ensure_installed = {'org'},
})
require('orgmode').setup_ts_grammar() 
require('orgmode').setup({
  org_agenda_files = {'~/Documents/Notes/*'},
  org_default_notes_file = {'~Documents/Notes/refile.org'} 
})
```

### OS / Distro

Windows 11

### Neovim version/commit

0.9.5

**Comment by schultzter** [comment]
There's a similar error when I press **Tab** on a heading to collapse or expand it: 
![image](https://github.com/nvim-orgmode/orgmode/assets/30871/1155a04d-05b0-423e-ab64-4be33644902e)

**Comment by kristijanhusak** [comment]
Something's wrong with your `org_capture_template` configuration. Can you paste that part of your config?

**Comment by schultzter** [comment]
Thanks. I never changed that config - where would I find it?

**Comment by kristijanhusak** [comment]
Your `org_default_notes_file` should be a string, not a table. This is the correct config:

```lua
require('orgmode').setup({
  org_agenda_files = {'~/Documents/Notes/*'},
  org_default_notes_file = '~Documents/Notes/refile.org'
})
```
