### ISSUE TITLE
How to change highlighting of folded lines?

### ISSUE THREAD

**Issue by gerazov** [nvim-orgmode/orgmode#755]
I would like to gray out folded lines in my Org files.

I've moved to the treesitter based highlighting and figured out that I can override highlights using:
```lua
          ["@org.headline.level1"] = { fg = colors.blue },
          ["@org.headline.level2"] = { fg = colors.teal },
          ["@org.headline.level3"] = { fg = colors.mauve },
          ["@org.headline.level4"] = { fg = colors.sapphire },
          ["@org.headline.level5"] = { fg = colors.pink },
```

However I can't seem to setup the folded line highlighting. What are the highlight groups used for the folded lines?

**Comment by kristijanhusak** [comment]
What Neovim version are you using? Only versions >= 0.10 support highlighting folded lines.

**Comment by gerazov** [comment]
I updated to 0.10.

If I do:
```vim
    hi! folded gui=italic guifg=#E78284 guibg=#E78284
```
it does get the folded lines italic but the coloring is as if they're unfolded (i.e. TODO highlighted and headline highlighted as normal)

**Comment by kristijanhusak** [comment]
> it does get the folded lines italic but the coloring is as if they're unfolded (i.e. TODO highlighted and headline highlighted as normal)

And you would like to have it old way?

**Comment by gerazov** [comment]
Currently it's colored:

![image](https://github.com/nvim-orgmode/orgmode/assets/15214418/c0f7f887-475c-41eb-b7f4-304c7db21ea5)


I'd like to gray out the folded lines like so:
![image](https://github.com/nvim-orgmode/orgmode/assets/15214418/15fce776-074d-4f95-9261-177384edae7f)

**Comment by kristijanhusak** [comment]
Ah, ok. Nvim 0.10 added support for colored folds, so I added it as a default, since it's the same in Emacs.

I just pushed an option for this, so get the latest master.
You can add it to your orgmode setup to make it the old way:

```lua
require('orgmode').setup({
  ui = {
    folds = {
      colored = false
    }
  }
})
```

Docs: https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#folds

**Comment by gerazov** [comment]
Perfect! Hvala puno :pray:
