### ISSUE TITLE
Give an option to change keybinding in calendar popup

### ISSUE THREAD

**Issue by Crdr0122** [nvim-orgmode/orgmode#763]
### Does this feature exist in Emacs orgmode core?

N/A

### Additional context

I am not sure if this is present in emacs or if I missed this functionality in this plugin, but there doesnt seem to be a way to change the keybindings in the calendar popup. It is set to using the hjkl keys for movement. Is there any way to change this or to let users customize it?

**Comment by seflue** [comment]
Allow configurable keybindings would need  some general overhaul of the calendar widget (which is on my list, if @kristijanhusak doesn't have other plans :wink: ). But for the time being, do you just miss the cursor keys work as well as hjkl?

**Comment by Crdr0122** [comment]
True, it would be great if the arrows keys can work as well

**Comment by seflue** [comment]
@Crdr0122: Please try out #767 , it should resolve your main issue.

**Comment by Crdr0122** [comment]
Yes, the arrows keys work in the calendar now. Thank you
