### ISSUE TITLE
Support for org-shiftmetaleft, org-outdent-item and org-shiftmetaright, org-indent-item

### ISSUE THREAD

**Issue by wolfv6** [nvim-orgmode/orgmode#765]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

https://orgmode.org/manual/Plain-Lists.html  > Unordered list
  M-LEFT/M-RIGHT Decrease/increase the indentation of an item, leaving children alone.

https://orgmode.org/worg/doc.html > org-metaleft  <M-left>
    Promote heading, list item at point or move table column left.
    Calls ‘org-do-promote’, ‘**org-outdent-item**’ or ‘org-table-move-column’, depending on context.
    With no specific context, calls the Emacs default ‘backward-word’.
   See the individual commands for more information.
    This function runs the hook ‘org-metaleft-hook’ as a first step, and returns at first non-nil value.

https://orgmode.org/worg/doc.html > org-outdent-item
    Outdent a local list item, but not its children.
    If a region is active, all items inside will be moved.

Similar descriptions for org-metaright and org-indent-item functions.

### Feature value

Used to indent/outdent bullets.

**Comment by seflue** [comment]
This is supported. 

For just changing the level of the current headline (leaving the child nodes untouched) you can use `org_do_promote` and `org_do_demote`. Default mapping is `<<` and `>>`. If you actually want to keep the child headline structure, than use `org_promote_subtree` (mapped mapped by default to `<s`) and `org_demote_subtree` (mapped by default to `>s`).

**Comment by wolfv6** [comment]
That is correct.
Used to indent/outdent bullets and list items.

**Comment by seflue** [comment]
I just implemented the feature in PR #779.

**Comment by seflue** [comment]
> Thanks seflue! That was fast.

Took me an evening. :wink: Now let's hope that @kristijanhusak will merge this soon into upstream.
