### ISSUE TITLE
failing unit test

### ISSUE THREAD

**Issue by snoblenet** [nvim-orgmode/orgmode#788]
### Describe the bug

I've forked the repo to make a contribution.

I've made no changes so far.

When I run the unit tests, it fails on line 48 in `tests/plenary/init_spec.lua`.

```lua
org.files:add_to_paths_sync(fname)
assert.is.Not.Nil(org.files.files[fname])
```

It's because this line changes the filepath before adding it to the table.

```lua
-- /var/folders/d3/24_x70js67s5bb9g6bdy8cg00000gn/T/nvim.steven/N5iaBo/0.org 
filename = vim.fn.resolve(vim.fn.fnamemodify(filename, ':p'))
-- /private/var/folders/d3/24_x70js67s5bb9g6bdy8cg00000gn/T/nvim.steven/N5iaBo/0.org
```

So, trying to find the file in the table using the original filepath does not work.

Any suggestions?

### Steps to reproduce

1. git clone
2. change nothing
3. run `make test`

### Expected behavior

All tests pass.

### Minimal init.lua

```lua

-- Enter your minimal_init.lua here

```

### OS / Distro

Mac OS X 14.6

### Neovim version/commit

v0.10.1

**Comment by snoblenet** [comment]
Yes, that works.

I believe that `/private` is a Mac-only directory of symlinks, and tests assume real files, so we should probably be doing something like:

```diff
-    local fname = vim.fn.tempname() .. '.org'
+    local fname = vim.resolve(vim.fn.tempname() .. '.org')
```

**Comment by snoblenet** [comment]
BTW, I am now onto the failure on this line:

```lua
 assert.are.same('Appended', org.files:find_headlines_by_title('Appended')[1]:get_title())
```

The value of `org.files:find_headlines_by_title('Appended')[1]` is `nil`

**Comment by snoblenet** [comment]
I fixed this issue in this PR -- review appreciated

https://github.com/nvim-orgmode/orgmode/pull/789

**Comment by seflue** [comment]
@kristijanhusak, @snoblenet As the PR is merged, this issue can be closed, right?
