### ISSUE TITLE
Error when using nvim-orgmode on files without an extension after setting `filetype=org`

### ISSUE THREAD

**Issue by ipstone** [nvim-orgmode/orgmode#808]
### Describe the bug

When using nvim-orgmode, everything works fine with files that have the `.org` extension. However, if I open a file without an extension (e.g., a cheat sheet file) and manually set the filetype to `org` using `:set filetype=org`, the initial folding levels appear correctly, indicating that orgmode recognizes the file.

The problem arises when I try to interact with the org structure, such as attempting to unfold headings. I receive the following error:

```
Error: Current file is not found or not an org file.
```

This error points to line **134** in `lua/orgmode/files/init.lua`, which contains an `assert` function related to `get_current_file()`.

### Steps to reproduce

1. Open a file without an extension in Neovim (e.g., `nvim cheatsheet`).
2. Manually set the filetype to org: `:set filetype=org`.
3. Attempt to unfold an org heading or interact with the org structure.

### Expected behavior

- Orgmode should fully recognize the file as an org file after setting the filetype.
- All org functionalities, including folding and unfolding sections, should work without errors.

### Emacs functionality

NA

### Minimal init.lua

```lua

-- Enter your minimal_init.lua here

```

### OS / Distro

macOS 14.6.1 intel

### Neovim version/commit

0.10.0

### Additional context

**Actual Behavior**:

- An error is thrown when interacting with the org structure.
- The error message states that the current file is not found or not an org file.
- Points to line 134 in `lua/orgmode/files/init.lua`.

**Additional Information**:

- The issue seems to occur because the plugin does not recognize files without an extension as org files, even after setting `filetype=org`.
- Line 134 in `init.lua` is within the `get_current_file()` function, which asserts the presence of the current file in the list of org files.

**Comment by kristijanhusak** [comment]
The filename needs to end in `.org` or `.org_archive` to be properly loaded as an org file. I'm not sure if I understand your use case here. Why would your cheet sheet not be an org file if you need to treat it as such?

**Comment by ipstone** [comment]
Thanks for the note @kristijanhusak - good question: the **scenario** is that lots of command line/utilities would use markdown as the default format (such as cheat, obsidian) - which uses the text file in markdown format (though file are not with .md alias);  I am trying to use those utilities with the text file, but I prefer all the great functionalitiies of orgmode, so I would like to load orgmode, even though these text files don't have .org alias 

I have tried to find a good markdown plugin for those files, but none is as useful as orgmode ...

Any ideas/suggestions on a solution? Thanks

**Comment by kristijanhusak** [comment]
@ipstone I added a support for this. It should work now.

@chipsenkbeil let me know if this change breaks something in org-roam. Hopefully it shouldn't, but I know you do some stuff for the backlinks buffer.

**Comment by ipstone** [comment]
this is amazing, thanks! @kristijanhusak @a006c93181
