### ISSUE TITLE
Lowercase `#+(begin|end)_src` blocks not syntax highlighted

### ISSUE THREAD

**Issue by ourigen** [nvim-orgmode/orgmode#86]
### Are you using "tree-sitter" branch?

No

### Describe the bug

`#+BEGIN_SRC` and `#+END_SRC` block is properly syntax highlighted, but `#+begin_src` and `#+end_src` block is not.

### Steps to reproduce

This is my test block:
```
#+BEGIN_SRC r
library(tidyverse)
#+END_SRC

#+begin_src r
library(tidyverse)
#+end_src
```

I then saved and reloaded the file.

### Expected behavior

Both blocks should have syntax highlighting for the language specified

### Emacs functionality

Conventionally, uppercase `BEGIN_|END_` is used, but [lowercase is also accepted](https://orgmode.org/manual/Conventions.html)

### Screenshots and recordings

![](https://user-images.githubusercontent.com/79729735/132959383-a5dd885c-8e70-44a8-bf5a-532785d400ea.png)

### OS / Distro

Arch Linux

### Neovim version/commit

v0.6.0-dev+218-g3f526feeb

**Comment by tecosaur** [comment]
A little comment on the general situation, lowercase keywords are actually the norm in Org, uppercase is just used in the manuals to make them stand out more.
